//! Phase 1 Poseidon-port verification (axiom backend migration — see
//! `docs/axiom-backend-migration.md`).
//!
//! Proves the audited `halo2_base::poseidon` chip, configured with the
//! project's Circom parameters, is correct in three independent ways:
//!
//! 1. **Parameters + permutation are Circom / light-poseidon identical.** The
//!    raw Grain-LFSR permutation generated by `OptimizedPoseidonSpec`
//!    reproduces `light_poseidon::Poseidon::hash` byte-for-byte for both
//!    arities (t=2 leaf, t=3 interior). This is the "must match circom params"
//!    requirement, checked at the strongest level — full permutation output
//!    equality — and is independent of halo2-base's optimized in-circuit form.
//! 2. **The `PoseidonChip` constructor (the handoff-specified API) runs.**
//!    Instantiating it loads every round constant / MDS entry in-circuit and
//!    MockProver asserts all constraints are satisfied.
//! 3. **The in-circuit gadget matches a native sponge.** The gadget's output
//!    equals a native reference under halo2-base's sponge convention
//!    (capacity `2^64`, squeeze permutation, digest at `state[1]`). Together
//!    with (1), this confirms the chip uses the Circom permutation *and*
//!    implements halo2-base's sponge correctly.
//!
//! The sponge-convention divergence between halo2-base and light-poseidon
//! (same permutation, different hash) is documented in
//! `circuits/src/poseidon_axiom.rs` as a Phase 3 reconciliation item.

use ark_ff::{BigInteger, PrimeField};
use ff::{Field, PrimeField as FfPrimeField};
use halo2_base::{
    halo2_proofs::halo2curves::bn256::Fr, poseidon::PoseidonChip, utils::testing::base_test,
};
use light_poseidon::{Poseidon as LightPoseidon, PoseidonHasher};
use num_bigint::BigUint;
use poseidon_primitives::poseidon::primitives::Spec;

use zkmist_circuits::poseidon_axiom::{hash_interior, hash_leaf, interior_spec, leaf_spec};

// ── Native Poseidon reference (raw Grain-LFSR constants + dense MDS) ─────
//
// Implements the standard (non-optimized) Poseidon permutation exactly as
// `poseidon-primitives` does, using constants from the SAME Grain-LFSR
// algorithm light-poseidon / Circom use. This is independent of halo2-base's
// optimized in-circuit form, so matching it is a meaningful check. (halo2-base
// computes the optimized form from these same raw constants; the optimization
// is a documented mathematical identity, and halo2-base's own suite proves its
// optimized chip equals the standard sponge.)

#[derive(Debug)]
struct Pow5Gen<
    const T: usize,
    const RATE: usize,
    const R_F: usize,
    const R_P: usize,
    const SECURE_MDS: usize,
>;

impl<
        const T: usize,
        const RATE: usize,
        const R_F: usize,
        const R_P: usize,
        const SECURE_MDS: usize,
    > Spec<Fr, T, RATE> for Pow5Gen<T, RATE, R_F, R_P, SECURE_MDS>
{
    fn full_rounds() -> usize {
        R_F
    }
    fn partial_rounds() -> usize {
        R_P
    }
    fn sbox(val: Fr) -> Fr {
        val.pow([5u64])
    }
    fn secure_mds() -> usize {
        SECURE_MDS
    }
}

/// Standard (non-optimized) Poseidon permutation, mirroring
/// `poseidon_primitives::poseidon::primitives::permute`.
fn native_permute(state: &mut [Fr], mds: &[Vec<Fr>], rc: &[Vec<Fr>], r_f: usize, r_p: usize) {
    let t = state.len();
    let half = r_f / 2;
    let apply_mds = |state: &mut [Fr]| {
        let mut ns = vec![Fr::ZERO; t];
        for i in 0..t {
            for j in 0..t {
                ns[i] += mds[i][j] * state[j];
            }
        }
        state.copy_from_slice(&ns);
    };
    let mut round = 0usize;
    // first half — full rounds
    for _ in 0..half {
        for i in 0..t {
            state[i] = (state[i] + rc[round][i]).pow([5u64]);
        }
        apply_mds(state);
        round += 1;
    }
    // partial rounds
    for _ in 0..r_p {
        for i in 0..t {
            state[i] += rc[round][i];
        }
        state[0] = state[0].pow([5u64]);
        apply_mds(state);
        round += 1;
    }
    // second half — full rounds
    for _ in 0..half {
        for i in 0..t {
            state[i] = (state[i] + rc[round][i]).pow([5u64]);
        }
        apply_mds(state);
        round += 1;
    }
}

/// Native Poseidon hash under an explicit sponge convention, using the raw
/// (non-optimized) Grain-LFSR permutation. `inputs` must fill exactly `RATE`
/// slots (the only case ZKMist uses: 1 input @ t=2, 2 inputs @ t=3).
///
/// * `capacity`        — initial `state[0]` (`0` for Circom, `2^64` for halo2-base).
/// * `squeeze_extra` — run a second (empty-absorb) permutation after the first, as halo2-base does when `len % RATE == 0`.
/// * `out_idx`         — digest state index (`0` for Circom, `1` for halo2-base).
fn native_hash<const T: usize, const RATE: usize, const R_F: usize, const R_P: usize>(
    inputs: &[Fr],
    capacity: Fr,
    squeeze_extra: bool,
    out_idx: usize,
) -> Fr {
    assert_eq!(inputs.len(), RATE, "reference only hashes full RATE blocks");
    let (rc_arr, mds_arr, _mds_inv) =
        <Pow5Gen<T, RATE, R_F, R_P, 0> as Spec<Fr, T, RATE>>::constants();
    let rc: Vec<Vec<Fr>> = rc_arr.iter().map(|r| r.to_vec()).collect();
    let mds: Vec<Vec<Fr>> = mds_arr.iter().map(|r| r.to_vec()).collect();

    let mut state = vec![Fr::ZERO; T];
    state[0] = capacity;
    for (j, inp) in inputs.iter().enumerate() {
        state[1 + j] += inp;
    }
    native_permute(&mut state, &mds, &rc, R_F, R_P);
    if squeeze_extra {
        // halo2-base pads the first rate slot with 1 on the empty squeeze absorb.
        state[1] += Fr::ONE;
        native_permute(&mut state, &mds, &rc, R_F, R_P);
    }
    state[out_idx]
}

fn axiom_fr_to_biguint(f: Fr) -> BigUint {
    BigUint::from_bytes_le(f.to_repr().as_ref())
}

fn ark_fr_to_biguint(f: ark_bn254::Fr) -> BigUint {
    BigUint::from_bytes_be(&f.into_bigint().to_bytes_be())
}

// ── Test 1: parameters + permutation are Circom / light-poseidon identical ─

#[test]
fn test_axiom_poseidon_params_match_light_poseidon() {
    // --- t=2 leaf hasher (1 input) ---
    {
        let input: u64 = 0xA1B2_C3D4_E5F6_u64;
        let native = native_hash::<2, 1, 8, 56>(&[Fr::from(input)], Fr::ZERO, false, 0);

        let mut lp = LightPoseidon::<ark_bn254::Fr>::new_circom(1).expect("leaf params");
        let lp_out = lp.hash(&[ark_bn254::Fr::from(input)]).expect("leaf hash");

        assert_eq!(
            axiom_fr_to_biguint(native),
            ark_fr_to_biguint(lp_out),
            "t=2 axiom permutation != light-poseidon (params not Circom-compatible)"
        );
    }
    // --- t=3 interior hasher (2 inputs) ---
    {
        let a: u64 = 123_456_789u64;
        let b: u64 = 987_654_321u64;
        let native = native_hash::<3, 2, 8, 57>(&[Fr::from(a), Fr::from(b)], Fr::ZERO, false, 0);

        let mut lp = LightPoseidon::<ark_bn254::Fr>::new_circom(2).expect("interior params");
        let lp_out = lp
            .hash(&[ark_bn254::Fr::from(a), ark_bn254::Fr::from(b)])
            .expect("interior hash");

        assert_eq!(
            axiom_fr_to_biguint(native),
            ark_fr_to_biguint(lp_out),
            "t=3 axiom permutation != light-poseidon (params not Circom-compatible)"
        );
    }
}

// ── Test 2: the PoseidonChip constructor (handoff-specified API) runs ──────

#[test]
fn test_axiom_poseidon_chip_constructor() {
    // The exact constructor from docs/SESSION_HANDOFF.md step 1. Building the
    // chip loads every round constant / MDS entry in-circuit; MockProver (via
    // base_test) then asserts every constraint is satisfied.
    base_test().k(12).lookup_bits(8).run(|ctx, range| {
        let _leaf_chip = PoseidonChip::new(ctx, leaf_spec(), range);
    });
    base_test().k(12).lookup_bits(8).run(|ctx, range| {
        let _interior_chip = PoseidonChip::new(ctx, interior_spec(), range);
    });
}

// ── Test 3: the in-circuit gadget matches the native sponge convention ────

#[test]
fn test_axiom_poseidon_gadget_matches_native() {
    let halo2base_cap = Fr::from_u128(1u128 << 64);

    // --- leaf: poseidon(x), t=2 ---
    {
        let x_val: u64 = 0xDEAD_BEEFu64;
        let circuit_out = base_test().k(12).lookup_bits(8).run(|ctx, range| {
            let x = ctx.load_witness(Fr::from(x_val));
            *hash_leaf(ctx, range, x).value()
        });
        let native_out = native_hash::<2, 1, 8, 56>(
            &[Fr::from(x_val)],
            halo2base_cap,
            true, // 1 % 1 == 0 → squeeze permutation
            1,
        );
        assert_eq!(
            circuit_out, native_out,
            "t=2 in-circuit gadget != native halo2-base sponge"
        );
    }
    // --- interior: poseidon(a, b), t=3 ---
    {
        let a_val: u64 = 7u64;
        let b_val: u64 = 11u64;
        let circuit_out = base_test().k(12).lookup_bits(8).run(|ctx, range| {
            let a = ctx.load_witness(Fr::from(a_val));
            let b = ctx.load_witness(Fr::from(b_val));
            *hash_interior(ctx, range, a, b).value()
        });
        let native_out = native_hash::<3, 2, 8, 57>(
            &[Fr::from(a_val), Fr::from(b_val)],
            halo2base_cap,
            true, // 2 % 2 == 0 → squeeze permutation
            1,
        );
        assert_eq!(
            circuit_out, native_out,
            "t=3 in-circuit gadget != native halo2-base sponge"
        );
    }
}
