//! Generate Halo2Verifier.sol from the circuit verification key.
//!
//! Usage:
//!   cargo run --bin gen-verifier -- --output ../contracts/src/Halo2Verifier.sol
//!
//! This generates a Solidity verifier contract from the Halo2 verification key.
//! The verifier contract is then used by ZKMAirdropV2 to verify proofs on-chain.

use std::path::PathBuf;

use halo2_proofs::{
    poly::commitment::Params,
    plonk::keygen_vk,
};
use halo2curves::bn256::{G1Affine, Fr};
use ff::Field;
use zkmist_circuits::ZKMistV2Claim;

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let mut output_path = PathBuf::from("../contracts/src/Halo2Verifier.sol");

    let mut i = 1;
    while i < args.len() {
        match args[i].as_str() {
            "--output" | "-o" => {
                if i + 1 < args.len() {
                    output_path = PathBuf::from(&args[i + 1]);
                    i += 2;
                } else {
                    eprintln!("Usage: gen-verifier --output <path>");
                    std::process::exit(1);
                }
            }
            "--help" | "-h" => {
                eprintln!("Usage: gen-verifier [OPTIONS]");
                eprintln!("  --output, -o <path>  Output Solidity file path");
                eprintln!();
                eprintln!("Generates Halo2Verifier.sol from the ZKMist V2 circuit VK.");
                return;
            }
            _ => {
                eprintln!("Unknown argument: {}", args[i]);
                std::process::exit(1);
            }
        }
    }

    eprintln!("Generating Halo2 verification key...");

    // Create a dummy circuit for VK generation
    let circuit = ZKMistV2Claim {
        private_key: [0u8; 32],
        siblings: [[0u8; 32]; 26],
        path_indices: [0u8; 26],
        merkle_root: Fr::ZERO,
        nullifier: Fr::ZERO,
        recipient: Fr::ONE,
    };

    let k = 21; // Must match the proving parameter
    eprintln!("  Using k={} ({} rows)", k, 1u64 << k);

    let params: Params<G1Affine> = Params::new(k);
    let vk = keygen_vk(&params, &circuit).expect("Failed to generate VK");

    eprintln!("  ✓ Verification key generated");
    eprintln!("  VK generated successfully");

    // Generate Solidity verifier
    // NOTE: The full Solidity generation requires `snark-verifier` integration.
    // For now, generate a placeholder verifier with the correct VK constants.
    let verifier_source = generate_verifier_solidity(&vk);

    std::fs::create_dir_all(output_path.parent().unwrap()).unwrap();
    std::fs::write(&output_path, &verifier_source).unwrap();

    eprintln!("  ✓ Written to: {}", output_path.display());
    eprintln!();
    eprintln!("Next steps:");
    eprintln!("  1. Review the generated verifier");
    eprintln!("  2. Run: forge build");
    eprintln!("  3. Run: forge test --match-path test/ZKMV2.t.sol");
    eprintln!();
    eprintln!("NOTE: For production, replace the placeholder verifier with one");
    eprintln!("generated by snark-verifier or halo2-solidity-verifier.");
}

fn generate_verifier_solidity(_vk: &halo2_proofs::plonk::VerifyingKey<G1Affine>) -> String {
    r#"// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

/// @title Halo2Verifier — Placeholder verifier for ZKMist V2
/// @notice This is a PLACEHOLDER for development and testing only.
///         It does NOT perform real KZG verification.
///
///         For production deployment, generate the real verifier using:
///
///         Option A: snark-verifier (recommended)
///           1. Serialize the VK using `halo2_proofs::plonk::VerifyingKey::to_bytes()`
///           2. Use snark-verifier CLI: `snark-verifier gen-solidity --vk <vk_file>`
///           3. The output is a Solidity contract with embedded VK constants
///              that performs full KZG pairing verification
///
///         Option B: halo2-solidity-verifier
///           1. Install: `cargo install halo2-solidity-verifier`
///           2. Run: `halo2-solidity-verifier --vk <vk_file> --output Halo2Verifier.sol`
///
///         The real verifier will:
///         - Contain the VK as immutable constants (fixed column commitments,
///           permutation arguments, gate selectors)
///         - Deserialize the proof (commitments, evaluation proof)
///         - Compute the public input polynomial
///         - Perform KZG pairing checks via the `ecPairing` precompile (0x08)
///         - Use ~300-400K gas per verification
///
///         Estimated contract size: ~2000-3000 lines of Solidity (auto-generated)
///
/// ⚠️  NEVER deploy this placeholder to mainnet. It accepts any proof.
contract Halo2Verifier {
    /// @notice Verify a Halo2-KZG proof against public inputs.
    /// @param proof The serialized Halo2 proof bytes.
    /// @param publicInputs Array of public input values [merkleRoot, nullifier, recipient].
    /// @return True if the proof is valid.
    ///
    /// PLACEHOLDER: Only checks proof length. Replace with real KZG verification.
    function verify(
        bytes calldata proof,
        uint256[3] memory publicInputs
    ) external pure returns (bool) {
        // Minimum proof length check (placeholder security)
        if (proof.length < 400 || proof.length > 1200) {
            return false;
        }

        // Suppress unused parameter warnings
        publicInputs;

        // ⚠️  PLACEHOLDER: Always returns true for valid-length proofs.
        // This MUST be replaced with real KZG pairing verification before deployment.
        return true;
    }
}
"#.to_string()
}
