//! Pre-deployment readiness checker for ZKMist.
//!
//! Validates that all prerequisites are met before deploying to mainnet.
//!
//! Checks:
//!
//! - 1. Halo2Verifier.sol has real KZG pairing verification (ecPairing precompile)
//! - 1b. Halo2VerifyingKey.sol has non-zero VK data and correct k-value
//! - 2. Merkle root matches the known eligibility tree root
//! - 3. Constants are consistent between CLI and contracts
//! - 3b. VK k-value matches prover CIRCUIT_K
//! - 4. No placeholder values remain
//! - 5. Cargo clippy passes
//! - 6. Cargo fmt passes
//! - 7. Forge tests pass
//! - 8. Cargo tests pass
//!
//! Usage:
//!
//! ```sh
//! # PR gate (advisory on known deploy blockers; fails only on regressions):
//! cargo run -p zkmist-tools --bin readiness -- --skip-slow
//! # Deploy gate (fails on ANY blocker, including the known ones):
//! cargo run -p zkmist-tools --bin readiness -- --strict
//! ```
//!
//! # Known-blocker / regression split
//
//! A handful of checks are EXPECTED to fail until the operator completes a
//! documented pre-deploy step — VK regeneration (`1b`), SRS hash pinning
//! (`1d`), and the post-deploy `AIRDROP_CONTRACT` placeholder (`4`). On a PR
//! (default mode) these are counted as *known blockers* and do NOT fail the
//! run, so the gate stays green unless something that should be green truly
//! *regresses*. Under `--strict` (the manual/scheduled deploy gate) every
//! known blocker also fails the run, so you cannot deploy past them.

use std::path::{Path, PathBuf};

/// Find the project root directory by searching upward for the workspace Cargo.toml.
fn find_project_root() -> Option<PathBuf> {
    let mut dir = std::env::current_dir().ok()?;
    loop {
        let cargo_toml = dir.join("Cargo.toml");
        if cargo_toml.exists() {
            if let Ok(content) = std::fs::read_to_string(&cargo_toml) {
                if content.contains("[workspace]") {
                    return Some(dir);
                }
            }
        }
        dir = dir.parent()?.to_path_buf();
    }
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let skip_slow = args.iter().any(|a| a == "--skip-slow");
    // `--strict` fails the run on KNOWN deployment blockers (VK regen, SRS
    // pinning, placeholder AIRDROP_CONTRACT) too — use it for the manual /
    // scheduled deploy gate. The default (PR) mode treats those blockers as
    // advisory so the gate is green unless something genuinely *regresses*.
    let strict = args.iter().any(|a| a == "--strict");

    if args.iter().any(|a| a == "--help" || a == "-h") {
        eprintln!("ZKMist Pre-Deployment Readiness Checker");
        eprintln!();
        eprintln!("Usage: readiness [OPTIONS]");
        eprintln!();
        eprintln!("Options:");
        eprintln!("  --skip-slow   Skip slow checks (MockProver, forge test)");
        eprintln!("  --strict      Fail on KNOWN deploy blockers too (deploy gate)");
        eprintln!("  --help        Show this help");
        std::process::exit(0);
    }

    eprintln!("╔════════════════════════════════════════════════════════════╗");
    eprintln!("║  ZKMist Pre-Deployment Readiness Check                     ║");
    eprintln!("╚════════════════════════════════════════════════════════════╝");
    eprintln!();

    let root = find_project_root().expect("Cannot find project root (workspace Cargo.toml)");
    eprintln!("  Project root: {}", root.display());
    eprintln!();

    let mut passed = 0usize;
    let mut failed = 0usize;
    // Failures from checks tagged as known deployment blockers (VK regen, SRS
    // pinning, placeholder AIRDROP_CONTRACT). Advisory unless `--strict`.
    let mut known_blockers = 0usize;
    let mut skipped = 0usize;

    // ── Check 1: Halo2Verifier.sol integrity ─────────────────────────
    eprintln!("[1/8] Checking Halo2Verifier.sol integrity...");
    let verifier_path = root.join("contracts/src/Halo2Verifier.sol");
    if let Ok(content) = std::fs::read_to_string(&verifier_path) {
        let has_verify_proof = content.contains("verifyProof");
        let has_ecpairing = content.contains("staticcall(gas(), 0x08")
            || content.contains("ecPairing")
            || content.contains("0x08");
        let has_bn254 = content.contains(
            "21888242871839275222246405745257275088696311157297823662689037894645226208583",
        );

        if has_verify_proof && has_ecpairing && has_bn254 {
            eprintln!(
                "      ✅ Halo2Verifier.sol has KZG pairing verification (ecPairing precompile)"
            );
            passed += 1;
        } else if has_verify_proof {
            eprintln!(
                "      ⚠️  Halo2Verifier.sol has verifyProof but may not have full KZG pairing"
            );
            eprintln!("         Verify it was generated by halo2-solidity-verifier");
            passed += 1;
        } else {
            eprintln!("      ❌ Halo2Verifier.sol does not appear to be a valid verifier");
            failed += 1;
        }
    } else {
        eprintln!(
            "      ⚠️  Halo2Verifier.sol not found at {}",
            verifier_path.display()
        );
        failed += 1;
    }

    // ── Check 1b: Halo2VerifyingKey.sol has non-zero VK data and correct k ──
    eprintln!("[1b/8] Checking Halo2VerifyingKey.sol...");
    let vk_path = root.join("contracts/src/Halo2VerifyingKey.sol");
    if let Ok(vk_content) = std::fs::read_to_string(&vk_path) {
        // Check that permutation commitments are non-zero (indicating real VK)
        let has_perm_comms = vk_content.contains("permutation_comms");
        let has_nonzero_data = vk_content.contains("0x")
            && !vk_content.lines().all(|l| {
                l.contains("0x0000000000000000000000000000000000000000000000000000000000000000")
                    || !l.contains("0x")
            });

        // Check that fixed commitments are not all zero (indicating real keygen)
        let all_fixed_zero = vk_content
            .lines()
            .filter(|l| l.contains("fixed_comms"))
            .all(|l| {
                l.contains("0x0000000000000000000000000000000000000000000000000000000000000000")
            });

        // Extract k value from VK
        let vk_k = extract_vk_k(&vk_content);

        // Get expected k from prover
        let expected_k = extract_prover_k(&root.join("cli/src/halo2_prover.rs"));

        if has_perm_comms && has_nonzero_data && !all_fixed_zero {
            eprintln!("      ✅ Halo2VerifyingKey.sol has VK data with non-zero commitments");
            passed += 1;
        } else if has_perm_comms && has_nonzero_data && all_fixed_zero {
            eprintln!("      ⚠️  Halo2VerifyingKey.sol has permutation commitments but ALL fixed commitments are zero");
            eprintln!("         This means the VK was generated with an empty synthesize() —");
            eprintln!("         the on-chain verifier will reject every real proof.");
            eprintln!(
                "         Fix: regenerate with gen-production-verifier (now loads range tables)"
            );
            record_known_blocker(&mut failed, &mut known_blockers, strict);
        } else {
            eprintln!("      ⚠️  Halo2VerifyingKey.sol may contain placeholder VK data");
            eprintln!("         Regenerate after full E2E MockProver test passes");
            skipped += 1;
        }

        // Check k-value consistency
        match (vk_k, expected_k) {
            (Some(vk), Some(exp)) if vk == exp => {
                eprintln!("      ✅ VK k-value ({}) matches prover CIRCUIT_K", vk);
            }
            (Some(vk), Some(exp)) => {
                eprintln!(
                    "      ❌ VK k-value MISMATCH: VK has k={} but prover uses CIRCUIT_K={}",
                    vk, exp
                );
                eprintln!(
                    "         Proofs generated at k={} will NOT verify against a k={} VK.",
                    exp, vk
                );
                eprintln!(
                    "         Fix: regenerate VK with gen-production-verifier --k {}",
                    exp
                );
                record_known_blocker(&mut failed, &mut known_blockers, strict);
            }
            (Some(vk), None) => {
                eprintln!(
                    "      ⚠️  VK k-value is {} but could not read prover CIRCUIT_K",
                    vk
                );
            }
            _ => {
                eprintln!("      ⚠️  Could not extract k-values for comparison");
            }
        }
    } else {
        eprintln!("      ⚠️  Halo2VerifyingKey.sol not found");
        skipped += 1;
    }

    // ── Check 1c: KZG SRS soundness (prover params source) ───────────
    // The on-chain verifier is only as trustworthy as the SRS the prover
    // commits against. `Params::new(k)` / `ParamsKZG::setup(k, rng)` derive a
    // RANDOM SRS whose trapdoor is known to the operator — proofs are forgeable
    // by whoever generated it. Mainnet MUST load the Ethereum KZG ceremony
    // SRS from a trusted transcript instead. This is a soundness blocker, so
    // it fails the readiness gate (not just a warning).
    eprintln!("[1c/8] Checking KZG SRS soundness (prover params source)...");
    let prover_path = root.join("cli/src/halo2_prover.rs");
    if let Ok(prover_src) = std::fs::read_to_string(&prover_path) {
        if uses_random_srs(&prover_src) {
            eprintln!("      ❌ Prover generates KZG params via Params::new / ParamsKZG::setup");
            eprintln!("         (random SRS). Whoever ran it knows the trapdoor and can forge");
            eprintln!("         proofs. This is dev/test ONLY — mainnet MUST load the Ethereum");
            eprintln!("         KZG ceremony SRS from a trusted transcript (Params::read). This");
            eprintln!("         also explains the >4 min cold params-generation cost at k=23.");
            failed += 1;
        } else {
            eprintln!("      ✅ Prover does not generate a random SRS (loads a transcript)");
            passed += 1;
        }
    } else {
        eprintln!("      ⚠️  cli/src/halo2_prover.rs not found — cannot check SRS source");
        skipped += 1;
    }

    // ── Check 1d: KZG SRS trust root pinned in constants.rs ───────────
    // `uses_random_srs` confirms the prover LOADS a transcript rather than
    // generating one, but that only matters if a real transcript is pinned.
    // KZG_SRS_URL + KZG_SRS_SHA256 are the sole trust root of the whole
    // system: each claimant downloads the file and verifies its SHA-256
    // against this hash, so the deployer cannot tamper with the SRS after
    // publication. An empty hash means the prover falls back to the dev
    // (forgeable) SRS — a hard mainnet blocker.
    eprintln!("[1d/8] Checking KZG SRS trust root (constants.rs)...");
    let srs_hash = extract_constant(&root.join("cli/src/constants.rs"), "KZG_SRS_SHA256");
    let srs_url = extract_constant(&root.join("cli/src/constants.rs"), "KZG_SRS_URL");
    match (srs_hash.as_deref(), srs_url.as_deref()) {
        (Some(h), Some(u)) => {
            eprintln!(
                "      ✅ KZG SRS pinned: SHA-256={}… URL={}",
                &h[..h.len().min(12)],
                u
            );
            passed += 1;
        }
        _ => {
            eprintln!(
                "      ❌ KZG SRS trust root not pinned (KZG_SRS_URL / KZG_SRS_SHA256 empty)"
            );
            eprintln!(
                "         Without a pinned public SRS the prover falls back to a self-generated"
            );
            eprintln!(
                "         (forgeable) SRS — proofs would be forgeable by whoever generated them."
            );
            eprintln!(
                "         See docs/kzg-srs.md to obtain, independently verify, and pin the PSE"
            );
            eprintln!("         perpetual powers-of-tau halo2 params file before mainnet.");
            record_known_blocker(&mut failed, &mut known_blockers, strict);
        }
    }

    // ── Check 2: Merkle root consistency ─────────────────────────────
    eprintln!("[2/8] Checking merkle root consistency...");
    let cli_root = extract_constant(&root.join("cli/src/constants.rs"), "KNOWN_MERKLE_ROOT");
    let deploy_root =
        extract_solidity_constant(&root.join("contracts/script/Deploy.s.sol"), "MERKLE_ROOT");
    let airdrop_test_root = find_test_merkle_root(&root.join("contracts/test"));

    match (cli_root.as_deref(), deploy_root.as_deref()) {
        (Some(cli), Some(deploy)) if !cli.is_empty() && cli == deploy => {
            eprintln!(
                "      ✅ Merkle root consistent: {}...{}",
                &cli[..18],
                &cli[cli.len() - 8..]
            );
            passed += 1;
        }
        (Some(cli), Some(deploy)) if !cli.is_empty() && !deploy.is_empty() => {
            eprintln!(
                "      ❌ Merkle root MISMATCH: CLI={} vs Deploy={}",
                cli, deploy
            );
            failed += 1;
        }
        _ => {
            eprintln!("      ⚠️  Could not extract merkle roots for comparison");
            failed += 1;
        }
    }

    if let Some(test_root) = airdrop_test_root {
        if test_root == cli_root.as_deref().unwrap_or("") {
            eprintln!("      ✅ Test merkle root matches");
        } else {
            eprintln!("      ⚠️  Test merkle root differs from CLI constant (may be intentional for tests)");
        }
    }

    // ── Check 3: Constants consistency ───────────────────────────────
    eprintln!("[3/8] Checking constants consistency...");
    let cli_deadline =
        extract_constant_value(&root.join("cli/src/constants.rs"), "CLAIM_DEADLINE: u64");
    let cli_claim_amount =
        extract_constant_value(&root.join("cli/src/constants.rs"), "CLAIM_AMOUNT: u64");
    let cli_max_claims =
        extract_constant_value(&root.join("cli/src/constants.rs"), "MAX_CLAIMS: u64");

    let mut constants_ok = true;
    if let Some(ref d) = cli_deadline {
        let clean = d.replace('_', "");
        if clean != "1798761600" {
            eprintln!("      ⚠️  CLAIM_DEADLINE = {} (expected 1798761600)", d);
            constants_ok = false;
        }
    }
    if let Some(ref a) = cli_claim_amount {
        let clean = a.replace('_', "");
        if clean != "10000" {
            eprintln!("      ⚠️  CLAIM_AMOUNT = {} (expected 10000)", a);
            constants_ok = false;
        }
    }
    if let Some(ref c) = cli_max_claims {
        let clean = c.replace('_', "");
        if clean != "1000000" {
            eprintln!("      ⚠️  MAX_CLAIMS = {} (expected 1000000)", c);
            constants_ok = false;
        }
    }
    if constants_ok {
        eprintln!("      ✅ CLI constants consistent");
        passed += 1;
    } else {
        failed += 1;
    }

    // ── Check 4: No placeholder values (besides VK) ──────────────────
    eprintln!("[4/8] Checking for placeholder values...");
    let mut placeholder_found = false;
    if let Ok(content) = std::fs::read_to_string(root.join("cli/src/constants.rs")) {
        if content.contains("0x000000000000000000000000000000000000dEaD") {
            eprintln!("      ⚠️  AIRDROP_CONTRACT is still placeholder (0x...dEaD)");
            eprintln!("         Update after deployment");
            placeholder_found = true;
        }
        if content.contains("TODO") {
            eprintln!("      ⚠️  TODO comments found in constants.rs");
            placeholder_found = true;
        }
    }
    if placeholder_found {
        eprintln!(
            "      ⚠️  Placeholders found (expected before deployment, must fix before mainnet)"
        );
        // Placeholders are a known pre-deploy blocker (AIRDROP_CONTRACT is
        // filled in only after deployment). Advisory on PRs; fails the run
        // under --strict (deploy gate).
        record_known_blocker(&mut failed, &mut known_blockers, strict);
    } else {
        eprintln!("      ✅ No placeholder values");
        passed += 1;
    }

    // ── Check 5: Cargo clippy ────────────────────────────────────────
    eprintln!("[5/8] Running cargo clippy...");
    let clippy_output = std::process::Command::new("cargo")
        .args(["clippy", "--workspace", "--", "-D", "warnings"])
        .current_dir(&root)
        .output();
    match clippy_output {
        Ok(output) if output.status.success() => {
            eprintln!("      ✅ Cargo clippy clean");
            passed += 1;
        }
        Ok(output) => {
            eprintln!("      ❌ Cargo clippy warnings/errors:");
            let stderr = String::from_utf8_lossy(&output.stderr);
            for line in stderr
                .lines()
                .filter(|l| l.contains("warning") || l.contains("error"))
                .take(5)
            {
                eprintln!("         {}", line);
            }
            failed += 1;
        }
        Err(e) => {
            eprintln!("      ⚠️  Could not run cargo clippy: {}", e);
            skipped += 1;
        }
    }

    // ── Check 6: Cargo fmt ──────────────────────────────────────────
    eprintln!("[6/8] Checking cargo fmt...");
    let fmt_output = std::process::Command::new("cargo")
        .args(["fmt", "--all", "--", "--check"])
        .current_dir(&root)
        .output();
    match fmt_output {
        Ok(output) if output.status.success() => {
            eprintln!("      ✅ Cargo fmt clean");
            passed += 1;
        }
        Ok(_) => {
            eprintln!("      ❌ Cargo fmt: unformatted files found. Run: cargo fmt --all");
            failed += 1;
        }
        Err(e) => {
            eprintln!("      ⚠️  Could not run cargo fmt: {}", e);
            skipped += 1;
        }
    }

    // ── Check 7: Forge tests ────────────────────────────────────────
    if skip_slow {
        eprintln!("[7/8] Skipping forge tests (--skip-slow)");
        skipped += 1;
    } else {
        eprintln!("[7/8] Running forge tests...");
        let forge_output = std::process::Command::new("forge")
            .args(["test", "--summary"])
            .current_dir(root.join("contracts"))
            .output();
        match forge_output {
            Ok(output) if output.status.success() => {
                let stdout = String::from_utf8_lossy(&output.stdout);
                if let Some(line) = stdout.lines().find(|l| l.contains("tests passed")) {
                    eprintln!("      ✅ {}", line.trim());
                } else {
                    eprintln!("      ✅ Forge tests passed");
                }
                passed += 1;
            }
            Ok(output) => {
                let stderr = String::from_utf8_lossy(&output.stderr);
                eprintln!("      ❌ Forge tests failed:");
                for line in stderr
                    .lines()
                    .filter(|l| l.contains("fail") || l.contains("error"))
                    .take(5)
                {
                    eprintln!("         {}", line);
                }
                failed += 1;
            }
            Err(e) => {
                eprintln!("      ⚠️  Could not run forge test: {}", e);
                eprintln!("         Is Foundry installed?");
                skipped += 1;
            }
        }
    }

    // ── Check 8: Cargo test ─────────────────────────────────────────
    if skip_slow {
        eprintln!("[8/8] Skipping cargo test (--skip-slow)");
        skipped += 1;
    } else {
        eprintln!("[8/8] Running cargo test...");
        let test_output = std::process::Command::new("cargo")
            .args(["test", "--workspace"])
            .current_dir(&root)
            .output();
        match test_output {
            Ok(output) if output.status.success() => {
                let stdout = String::from_utf8_lossy(&output.stdout);
                let total: usize = stdout
                    .lines()
                    .filter_map(|l| {
                        if l.contains("test result:") && l.contains("passed") {
                            l.split_whitespace()
                                .find(|w| w.chars().all(|c| c.is_ascii_digit()))
                                .and_then(|n| n.parse::<usize>().ok())
                        } else {
                            None
                        }
                    })
                    .sum();
                eprintln!("      ✅ Cargo tests passed ({} tests)", total);
                passed += 1;
            }
            Ok(output) => {
                let stderr = String::from_utf8_lossy(&output.stderr);
                eprintln!("      ❌ Cargo tests failed:");
                for line in stderr
                    .lines()
                    .filter(|l| l.contains("FAILED") || l.contains("failures"))
                    .take(5)
                {
                    eprintln!("         {}", line);
                }
                failed += 1;
            }
            Err(e) => {
                eprintln!("      ⚠️  Could not run cargo test: {}", e);
                skipped += 1;
            }
        }
    }

    // ── Summary ──────────────────────────────────────────────────────
    eprintln!();
    eprintln!("════════════════════════════════════════════════════════════");
    eprintln!(
        "  Results: {} passed, {} regression(s), {} known blocker(s), {} skipped",
        passed, failed, known_blockers, skipped
    );
    eprintln!("════════════════════════════════════════════════════════════");

    // Exit policy:
    //   - A *regression* (failed > 0) always fails the run — on a PR this is
    //     the signal that a check which should be green has broken.
    //   - A *known deployment blocker* (VK regen, SRS pinning, placeholder
    //     AIRDROP_CONTRACT) only fails under `--strict` (the deploy gate). On
    //     a PR it is advisory, so the gate stays green while the documented
    //     pre-deploy steps are still pending.
    if failed > 0 {
        eprintln!();
        eprintln!(
            "  ❌ NOT READY — {} regression(s) detected (not counting known blockers)",
            failed
        );
        std::process::exit(1);
    }
    if known_blockers > 0 {
        eprintln!();
        eprintln!(
            "  ⚠️  {} known deployment blocker(s) remain (VK regen / SRS pin / post-deploy address).",
            known_blockers
        );
        if strict {
            eprintln!("  ❌ Failing under --strict — resolve the blockers before deploying.");
            std::process::exit(1);
        }
        eprintln!("  (advisory on PRs; run with --strict to gate the deploy)");
        std::process::exit(0);
    }

    // Fully green — no regressions, no known blockers.
    {
        eprintln!();
        eprintln!("  ✅ All automated checks passed!");
        eprintln!();
        eprintln!("  Remaining steps before mainnet deployment:");
        eprintln!("    ┌──────────────────────────────────────────────────────────────");
        eprintln!("    │ CRITICAL (blocks deployment):");
        eprintln!("    │ [ ] Re-run full E2E MockProver test (k=23, ~15 min):  ✅ 2026 PASS");
        eprintln!("    │     cargo test -p zkmist-circuits -- --ignored --nocapture");
        eprintln!("    │ [ ] Regenerate Halo2Verifier.sol + Halo2VerifyingKey.sol with");
        eprintln!("    │     gen-production-verifier (now loads range tables, k=23)");
        eprintln!("    │ [ ] Verify VK k-value matches CIRCUIT_K (checked above)");
        eprintln!("    │ [ ] Verify VK has non-zero fixed commitments (checked above)");
        eprintln!("    │ [ ] External security audit of secp256k1 non-native field arithmetic");
        eprintln!("    │     → See: circuits/src/secp256k1.rs security note");
        eprintln!("    │ [ ] Testnet deployment on Base Sepolia with full claim flow");
        eprintln!("    │     → ./scripts/testnet-deploy.sh");
        eprintln!("    │");
        eprintln!("    │ HIGH PRIORITY:");
        eprintln!("    │ [ ] Generate real proof and validate size in [4000, 8000] byte range");
        eprintln!("    │     → cargo run --release -p zkmist-cli -- bench");
        eprintln!("    │ [ ] Benchmark proving time on reference hardware (<60 sec target)");
        eprintln!("    │ [ ] Update AIRDROP_CONTRACT in cli/src/constants.rs after deployment");
        eprintln!("    │ [ ] Set up on-chain monitor: cargo run -p zkmist-tools --bin monitor");
        eprintln!("    │");
        eprintln!("    │ RECOMMENDED:");
        eprintln!("    │ [ ] Run full E2E test suite: ./scripts/e2e-test.sh");
        eprintln!("    │ [ ] Set up monitoring/alerting (BaseScan, Tenderly, Dune)");
        eprintln!("    │ [ ] Consider replacing hand-rolled secp256k1 with audited library");
        eprintln!("    └──────────────────────────────────────────────────────────────");
    }
}

/// Record a *known deployment blocker* (VK regen, SRS pinning, or the
/// post-deploy `AIRDROP_CONTRACT` placeholder). On a PR (default) these are
/// advisory so the gate only fails on genuine regressions; under `--strict`
/// (the manual/scheduled deploy gate) they also fail the run.
fn record_known_blocker(failed: &mut usize, known_blockers: &mut usize, strict: bool) {
    if strict {
        *failed += 1;
    } else {
        *known_blockers += 1;
    }
}

fn extract_constant(file_path: &Path, const_name: &str) -> Option<String> {
    let content = std::fs::read_to_string(file_path).ok()?;
    // Normalize multi-line declarations into single lines
    let normalized: String = content
        .lines()
        .filter(|l| !l.trim().starts_with("//"))
        .collect::<Vec<&str>>()
        .join(" ");
    // Split by semicolons to get individual statements
    for statement in normalized.split(';') {
        if statement.contains(const_name) {
            if let Some(idx) = statement.find('=') {
                let val = statement[idx + 1..].trim().trim_matches('"').trim();
                let clean = val.strip_prefix("0x").unwrap_or(val).replace('_', "");
                if !clean.is_empty() {
                    return Some(clean);
                }
            }
        }
    }
    None
}

fn extract_constant_value(file_path: &Path, const_name: &str) -> Option<String> {
    let content = std::fs::read_to_string(file_path).ok()?;
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("pub const") && trimmed.contains(const_name.split(':').next()?) {
            if let Some(idx) = trimmed.find('=') {
                // Extract value between '=' and ';', stripping comments
                let after_eq = &trimmed[idx + 1..];
                let val = after_eq.split(';').next().unwrap_or("").trim().to_string();
                if !val.is_empty() {
                    return Some(val);
                }
            }
        }
    }
    None
}

fn extract_solidity_constant(file_path: &Path, const_name: &str) -> Option<String> {
    let content = std::fs::read_to_string(file_path).ok()?;
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.contains(const_name) && trimmed.contains("constant") {
            if let Some(idx) = trimmed.find('=') {
                let val = trimmed[idx + 1..]
                    .trim()
                    .trim_end_matches(';')
                    .trim()
                    .replace("0x", "");
                return Some(val);
            }
        }
    }
    None
}

fn find_test_merkle_root(test_dir: &Path) -> Option<String> {
    if let Ok(entries) = std::fs::read_dir(test_dir) {
        for entry in entries.flatten() {
            if let Ok(content) = std::fs::read_to_string(entry.path()) {
                for line in content.lines() {
                    if line.contains("MERKLE_ROOT") && line.contains("0x") {
                        if let Some(start) = line.find("0x") {
                            let hex = &line[start + 2..];
                            let hex_clean: String =
                                hex.chars().take_while(|c| c.is_ascii_hexdigit()).collect();
                            if hex_clean.len() == 64 {
                                return Some(hex_clean);
                            }
                        }
                    }
                }
            }
        }
    }
    None
}

/// Extract the k-value from `Halo2VerifyingKey.sol`.
///
/// Matches the line `mstore(0x0040, 0x...0015) // k` and returns the **value**
/// (the second hex literal, after the comma) — *not* the memory **offset**.
///
/// Earlier versions grabbed the FIRST `0x` on the line, which is the `mstore`
/// offset (`0x0040` = 64), and so reported `k=64` instead of the value
/// (`0x15` = 21). That offset/value mix-up made the k-consistency check report
/// nonsense; the regression is pinned by the `extract_vk_k_*` unit tests below.
fn extract_vk_k(vk_content: &str) -> Option<u32> {
    for line in vk_content.lines() {
        let trimmed = line.trim();
        if !trimmed.contains("// k") {
            continue;
        }
        // `mstore(0xOFFSET, 0xVALUE)` — the value is everything after the first
        // comma. Taking the first `0x` on the line would return the offset.
        let after_comma = match trimmed.split_once(',') {
            Some((_, rest)) => rest,
            None => continue,
        };
        let start = match after_comma.find("0x") {
            Some(s) => s,
            None => continue,
        };
        let hex = &after_comma[start + 2..];
        let hex_clean: String = hex.chars().take_while(|c| c.is_ascii_hexdigit()).collect();
        if let Ok(val) = u32::from_str_radix(&hex_clean, 16) {
            return Some(val);
        }
    }
    None
}

/// Extract `CIRCUIT_K` from the prover source.
fn extract_prover_k(prover_path: &Path) -> Option<u32> {
    let content = std::fs::read_to_string(prover_path).ok()?;
    extract_prover_k_from_str(&content)
}

/// String-parsing core of [`extract_prover_k`], split out so it can be unit
/// tested without writing a temporary file.
fn extract_prover_k_from_str(content: &str) -> Option<u32> {
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.contains("CIRCUIT_K") && trimmed.contains('=') && !trimmed.starts_with("//") {
            if let Some(idx) = trimmed.find('=') {
                let val = trimmed[idx + 1..].trim().trim_end_matches(';').trim();
                if let Ok(k) = val.parse::<u32>() {
                    return Some(k);
                }
            }
        }
    }
    None
}

/// Detect whether a prover source generates KZG params from scratch with an
/// RNG (an untrusted/toy SRS) instead of loading a ceremony transcript.
///
/// `ParamsKZG::setup(k, rng)` and `Params::<...>::new(k)` both derive a
/// structured reference string whose trapdoor is known to whoever ran them —
/// anyone holding it can forge proofs. Mainnet MUST load the Ethereum/PSE KZG
/// ceremony SRS from a trusted transcript (e.g. `Params::read(...)`). This
/// returns `true` when such a generation call is present on a non-comment line
/// AND the source is not behind an explicit dev gate.
///
/// Convention: the ONLY permitted `Params::new` / `setup` must sit behind an
/// explicit `ZKMIST_DEV_SRS` env-var gate (see `load_or_download_params` in
/// halo2_prover.rs). If the file references `ZKMIST_DEV_SRS`, the random-SRS
/// call is assumed to be the dev-gated fallback and is NOT flagged. Removing
/// the gate (or adding an ungated `Params::new`) flips this back to `true`,
/// failing the readiness gate.
///
/// Note: the good path (`Params::<...>::read(&mut reader)`) contains `Params`
/// but neither `::new(` nor `setup(`, so it is correctly NOT flagged.
fn uses_random_srs(prover_src: &str) -> bool {
    let has_random_call = prover_src.lines().any(|line| {
        let t = line.trim();
        if t.starts_with("//") {
            return false;
        }
        let uses_setup = t.contains("ParamsKZG") && t.contains("setup(");
        let uses_new = t.contains("Params") && t.contains("::new(");
        uses_setup || uses_new
    });
    has_random_call && !prover_src.contains("ZKMIST_DEV_SRS")
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn repo_root() -> PathBuf {
        // tools/ is one level below the workspace root.
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .expect("tools/ should have a parent dir")
            .to_path_buf()
    }

    // ── record_known_blocker (PR-advisory vs --strict deploy gate) ───────

    #[test]
    fn test_record_known_blocker_is_advisory_by_default() {
        let (mut failed, mut known) = (0usize, 0usize);
        record_known_blocker(&mut failed, &mut known, false);
        assert_eq!((failed, known), (0, 1));
    }

    #[test]
    fn test_record_known_blocker_fails_under_strict() {
        let (mut failed, mut known) = (0usize, 0usize);
        record_known_blocker(&mut failed, &mut known, true);
        assert_eq!((failed, known), (1, 0));
    }

    // ── extract_vk_k: must read the VALUE, not the OFFSET ───────────────

    #[test]
    fn test_extract_vk_k_real_k21_line() {
        // Real line from the currently-committed Halo2VerifyingKey.sol.
        let line = "            mstore(0x0040, 0x0000000000000000000000000000000000000000000000000000000000000015) // k\n";
        assert_eq!(extract_vk_k(line), Some(21));
    }

    #[test]
    fn test_extract_vk_k_regenerated_k24_line() {
        // The form gen-production-verifier emits once the real VK lands at k=23.
        let line = "            mstore(0x0040, 0x0000000000000000000000000000000000000000000000000000000000000018) // k\n";
        assert_eq!(extract_vk_k(line), Some(24));
    }

    #[test]
    fn test_extract_vk_k_does_not_return_the_offset() {
        // The bug reported 0x0040 (= 64, the offset) instead of the value.
        // Here the value is 0x18 = 24; it must NOT return 0x40 = 64.
        let line = "            mstore(0x0040, 0x18) // k\n";
        let got = extract_vk_k(line);
        assert_eq!(got, Some(24));
        assert_ne!(got, Some(0x40));
    }

    #[test]
    fn test_extract_vk_k_ignores_non_k_mstore_lines() {
        // Every VK constant uses mstore(...) with a trailing comment; only the
        // `// k` line must match.
        let vk = "\
            mstore(0x0000, 0x07d6cec294b3ee601635fc1b2bfa4b13c3c277629cacf756a13aec10ec7cf917) // vk_digest\n\
            mstore(0x0020, 0x3) // num_instances\n\
            mstore(0x0040, 0x15) // k\n\
            mstore(0x0060, 0x30644cefbebe09202b4ef7f3ff53a4511d70ff06da772cc3785d6b74e0536081) // n_inv\n";
        assert_eq!(extract_vk_k(vk), Some(21));
    }

    #[test]
    fn test_extract_vk_k_returns_none_without_k_marker() {
        let vk = "mstore(0x0000, 0x07d6) // vk_digest\nmstore(0x0060, 0x3064) // n_inv\n";
        assert_eq!(extract_vk_k(vk), None);
    }

    // ── extract_prover_k_from_str ───────────────────────────────────────

    // ── uses_random_srs ───────────────────────────────────────────────

    #[test]
    fn test_uses_random_srs_flags_params_new() {
        // The exact form used in cli/src/halo2_prover.rs::load_or_gen_params.
        let src = "    let params = Params::<G1Affine>::new(k);\n";
        assert!(uses_random_srs(src));
    }

    #[test]
    fn test_uses_random_srs_flags_paramskzg_setup() {
        // The form gen-production-verifier uses.
        let src = "    let params = ParamsKZG::<halo2curves::bn256::Bn256>::setup(k, &mut rng);\n";
        assert!(uses_random_srs(src));
    }

    #[test]
    fn test_uses_random_srs_ignores_comments() {
        // A doc/comment line mentioning Params::new must NOT trip the check —
        // only real code calls do. (The prover has comment lines like this.)
        let src = "// WARNING: Params::new(k) generates a random SRS.\nfn main() {}\n";
        assert!(!uses_random_srs(src));
    }

    #[test]
    fn test_uses_random_srs_allows_ceremony_load() {
        // The correct mainnet path: loading a trusted transcript. Must NOT flag.
        let src = "    let params = Params::<G1Affine>::read(&mut reader)?;\n";
        assert!(!uses_random_srs(src));
    }

    #[test]
    fn test_uses_random_srs_allows_dev_gated_params_new() {
        // Convention: a Params::new behind an explicit ZKMIST_DEV_SRS gate is
        // the accepted dev fallback and must NOT be flagged. (This is exactly
        // the shape of load_or_download_params in halo2_prover.rs.)
        let src = "    if std::env::var(\"ZKMIST_DEV_SRS\").is_ok() {\n        let params = Params::<G1Affine>::new(k);\n    }\n";
        assert!(!uses_random_srs(src));
    }

    #[test]
    fn test_uses_random_srs_returns_false_on_clean_source() {
        assert!(!uses_random_srs("fn main() {}\n"));
    }

    // ── Parser guards against the real committed prover/constants ────────
    //
    // After the SRS-loading rewrite the prover LOADS a transcript in
    // production and only falls back to Params::new behind an explicit
    // ZKMIST_DEV_SRS gate. So uses_random_srs() must be FALSE on the real
    // prover now. The trust root IS now pinned (KZG_SRS_SHA256 set) — guarded
    // by test_real_committed_kzg_srs_hash_is_pinned, which asserts the hash
    // stays a well-formed 64-hex value (a change requires regenerating the VK
    // and rerunning the on-chain round-trip; see docs/kzg-srs.md §2.2).
    #[test]
    fn test_real_committed_prover_srs_is_dev_gated() {
        let prover_path = repo_root().join("cli/src/halo2_prover.rs");
        let src = std::fs::read_to_string(&prover_path)
            .unwrap_or_else(|e| panic!("read {}: {}", prover_path.display(), e));
        assert!(
            src.contains("ZKMIST_DEV_SRS"),
            "dev gate removed — re-add the ZKMIST_DEV_SRS gate around any Params::new"
        );
        assert!(
            !uses_random_srs(&src),
            "prover has an ungated Params::new/setup (no ZKMIST_DEV_SRS gate) — \
             that is a soundness bug, re-gate it"
        );
    }

    #[test]
    fn test_real_committed_kzg_srs_hash_is_pinned() {
        // Trust root is now pinned. This tripwire guards against two silent
        // regressions: (a) KZG_SRS_SHA256 being cleared back to empty, and
        // (b) it being repinned to a malformed value. Repinning to a DIFFERENT
        // digest also requires regenerating Halo2VerifyingKey.sol (via
        // gen-production-verifier --emit) and rerunning ZKM.realroundtrip.t.sol
        // — see docs/kzg-srs.md §2.2 (provenance must be re-confirmed).
        let constants_path = repo_root().join("cli/src/constants.rs");
        let hash = extract_constant(&constants_path, "KZG_SRS_SHA256")
            .expect("KZG_SRS_SHA256 must be pinned (readiness [1d/8] fails without it)");
        assert_eq!(
            hash.len(),
            64,
            "KZG_SRS_SHA256 must be a 64-char SHA-256 digest"
        );
        assert!(
            hash.chars().all(|c| c.is_ascii_hexdigit()),
            "KZG_SRS_SHA256 must be lowercase hex, got: {hash}"
        );
        assert_eq!(
            hash,
            hash.to_ascii_lowercase(),
            "KZG_SRS_SHA256 must be lowercase"
        );
    }

    #[test]
    fn test_extract_prover_k_real_definition() {
        let src = "// header\nconst CIRCUIT_K: u32 = 24;\nfn main() {}\n";
        assert_eq!(extract_prover_k_from_str(src), Some(24));
    }

    #[test]
    fn test_extract_prover_k_skips_comment_lines_mentioning_circuit_k() {
        // halo2_prover.rs has comment lines mentioning CIRCUIT_K before the
        // real const; those start with `//` and must be skipped.
        let src = "\
            // MUST match CIRCUIT_K in cli/src/halo2_prover.rs (k=24 after the rewrite)\n\
            const CIRCUIT_K: u32 = 24;\n";
        assert_eq!(extract_prover_k_from_str(src), Some(24));
    }

    #[test]
    fn test_extract_prover_k_skips_local_let_lines_mentioning_circuit_k() {
        // `let mut k: u32 = 24; // ... CIRCUIT_K` mentions CIRCUIT_K and has an
        // '=', but the value token is `24;` — which fails to parse, so the
        // search must continue to the real `const CIRCUIT_K: u32 = 24;` line.
        let src = "\
            let mut k: u32 = 24; // MUST match CIRCUIT_K\n\
            const CIRCUIT_K: u32 = 24;\n";
        assert_eq!(extract_prover_k_from_str(src), Some(24));
    }

    #[test]
    fn test_extract_prover_k_returns_none_when_absent() {
        assert_eq!(extract_prover_k_from_str("fn main() {}\n"), None);
    }

    // ── Parser guard against the real committed files ───────────────────
    //
    // Reads the actual Halo2VerifyingKey.sol and cli/src/halo2_prover.rs so the
    // parsers are validated against the real file format (not just fixtures).
    // VK and prover are both regenerated/pinned at k=23; this now asserts they
    // AGREE (a future circuit rewrite that moves k must update both in
    // lockstep, or this fails — preventing a silent verifier/prover k drift).
    #[test]
    fn test_real_committed_files_k_values() {
        let vk_path = repo_root().join("contracts/src/Halo2VerifyingKey.sol");
        let prover_path = repo_root().join("cli/src/halo2_prover.rs");
        let vk_content = std::fs::read_to_string(&vk_path)
            .unwrap_or_else(|e| panic!("read {}: {}", vk_path.display(), e));
        let prover_content = std::fs::read_to_string(&prover_path)
            .unwrap_or_else(|e| panic!("read {}: {}", prover_path.display(), e));

        let vk_k = extract_vk_k(&vk_content);
        let prover_k = extract_prover_k_from_str(&prover_content);

        // Parser sanity: both real files must be parsed, not return None.
        let vk_k = vk_k.expect("VK k line should parse");
        let prover_k = prover_k.expect("prover CIRCUIT_K should parse");

        // VK and prover are both at k=23. Both equality checks below MUST hold;
        // if either moves, the circuit was changed and the VK must be
        // regenerated (gen-production-verifier --emit) before this passes again.
        assert_eq!(
            prover_k, 23,
            "prover CIRCUIT_K moved — update CIRCUIT_K doc/CI and regenerate the VK"
        );
        assert_eq!(
            vk_k, 23,
            "VK k moved — regenerate Halo2VerifyingKey.sol at the prover's k"
        );
        assert_eq!(
            vk_k, prover_k,
            "VK k and prover k drifted out of sync — proofs would verify against a \
             different domain than the prover committed to (on-chain failure)"
        );
    }
}
