//! Pre-deployment readiness checker for ZKMist.
//!
//! Validates that all prerequisites are met before deploying to mainnet.
//!
//! Checks:
//!
//! - 1. Halo2Verifier.sol has real KZG pairing verification (ecPairing precompile)
//! - 1b. Halo2VerifyingKey.sol has non-zero VK data and correct k-value
//! - 2. Merkle root matches the known eligibility tree root
//! - 3. Constants are consistent between CLI and contracts
//! - 3b. VK k-value matches prover CIRCUIT_K
//! - 4. No placeholder values remain
//! - 5. Cargo clippy passes
//! - 6. Cargo fmt passes
//! - 7. Forge tests pass
//! - 8. Cargo tests pass
//!
//! Usage:
//!
//! ```sh
//! cargo run -p zkmist-tools --bin readiness
//! cargo run -p zkmist-tools --bin readiness -- --skip-slow
//! ```

use std::path::{Path, PathBuf};

/// Find the project root directory by searching upward for the workspace Cargo.toml.
fn find_project_root() -> Option<PathBuf> {
    let mut dir = std::env::current_dir().ok()?;
    loop {
        let cargo_toml = dir.join("Cargo.toml");
        if cargo_toml.exists() {
            if let Ok(content) = std::fs::read_to_string(&cargo_toml) {
                if content.contains("[workspace]") {
                    return Some(dir);
                }
            }
        }
        dir = dir.parent()?.to_path_buf();
    }
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let skip_slow = args.iter().any(|a| a == "--skip-slow");

    if args.iter().any(|a| a == "--help" || a == "-h") {
        eprintln!("ZKMist Pre-Deployment Readiness Checker");
        eprintln!();
        eprintln!("Usage: readiness [OPTIONS]");
        eprintln!();
        eprintln!("Options:");
        eprintln!("  --skip-slow   Skip slow checks (MockProver, forge test)");
        eprintln!("  --help        Show this help");
        std::process::exit(0);
    }

    eprintln!("╔════════════════════════════════════════════════════════════╗");
    eprintln!("║  ZKMist Pre-Deployment Readiness Check                     ║");
    eprintln!("╚════════════════════════════════════════════════════════════╝");
    eprintln!();

    let root = find_project_root().expect("Cannot find project root (workspace Cargo.toml)");
    eprintln!("  Project root: {}", root.display());
    eprintln!();

    let mut passed = 0usize;
    let mut failed = 0usize;
    let mut skipped = 0usize;

    // ── Check 1: Halo2Verifier.sol integrity ─────────────────────────
    eprintln!("[1/8] Checking Halo2Verifier.sol integrity...");
    let verifier_path = root.join("contracts/src/Halo2Verifier.sol");
    if let Ok(content) = std::fs::read_to_string(&verifier_path) {
        let has_verify_proof = content.contains("verifyProof");
        let has_ecpairing = content.contains("staticcall(gas(), 0x08")
            || content.contains("ecPairing")
            || content.contains("0x08");
        let has_bn254 = content.contains(
            "21888242871839275222246405745257275088696311157297823662689037894645226208583",
        );

        if has_verify_proof && has_ecpairing && has_bn254 {
            eprintln!(
                "      ✅ Halo2Verifier.sol has KZG pairing verification (ecPairing precompile)"
            );
            passed += 1;
        } else if has_verify_proof {
            eprintln!(
                "      ⚠️  Halo2Verifier.sol has verifyProof but may not have full KZG pairing"
            );
            eprintln!("         Verify it was generated by halo2-solidity-verifier");
            passed += 1;
        } else {
            eprintln!("      ❌ Halo2Verifier.sol does not appear to be a valid verifier");
            failed += 1;
        }
    } else {
        eprintln!(
            "      ⚠️  Halo2Verifier.sol not found at {}",
            verifier_path.display()
        );
        failed += 1;
    }

    // ── Check 1b: Halo2VerifyingKey.sol has non-zero VK data and correct k ──
    eprintln!("[1b/8] Checking Halo2VerifyingKey.sol...");
    let vk_path = root.join("contracts/src/Halo2VerifyingKey.sol");
    if let Ok(vk_content) = std::fs::read_to_string(&vk_path) {
        // Check that permutation commitments are non-zero (indicating real VK)
        let has_perm_comms = vk_content.contains("permutation_comms");
        let has_nonzero_data = vk_content.contains("0x")
            && !vk_content.lines().all(|l| {
                l.contains("0x0000000000000000000000000000000000000000000000000000000000000000")
                    || !l.contains("0x")
            });

        // Check that fixed commitments are not all zero (indicating real keygen)
        let all_fixed_zero = vk_content
            .lines()
            .filter(|l| l.contains("fixed_comms"))
            .all(|l| {
                l.contains("0x0000000000000000000000000000000000000000000000000000000000000000")
            });

        // Extract k value from VK
        let vk_k = extract_vk_k(&vk_content);

        // Get expected k from prover
        let expected_k = extract_prover_k(&root.join("cli/src/halo2_prover.rs"));

        if has_perm_comms && has_nonzero_data && !all_fixed_zero {
            eprintln!("      ✅ Halo2VerifyingKey.sol has VK data with non-zero commitments");
            passed += 1;
        } else if has_perm_comms && has_nonzero_data && all_fixed_zero {
            eprintln!("      ⚠️  Halo2VerifyingKey.sol has permutation commitments but ALL fixed commitments are zero");
            eprintln!("         This means the VK was generated with an empty synthesize() —");
            eprintln!("         the on-chain verifier will reject every real proof.");
            eprintln!(
                "         Fix: regenerate with gen-production-verifier (now loads range tables)"
            );
            failed += 1;
        } else {
            eprintln!("      ⚠️  Halo2VerifyingKey.sol may contain placeholder VK data");
            eprintln!("         Regenerate after full E2E MockProver test passes");
            skipped += 1;
        }

        // Check k-value consistency
        match (vk_k, expected_k) {
            (Some(vk), Some(exp)) if vk == exp => {
                eprintln!("      ✅ VK k-value ({}) matches prover CIRCUIT_K", vk);
            }
            (Some(vk), Some(exp)) => {
                eprintln!(
                    "      ❌ VK k-value MISMATCH: VK has k={} but prover uses CIRCUIT_K={}",
                    vk, exp
                );
                eprintln!(
                    "         Proofs generated at k={} will NOT verify against a k={} VK.",
                    exp, vk
                );
                eprintln!(
                    "         Fix: regenerate VK with gen-production-verifier --k {}",
                    exp
                );
                failed += 1;
            }
            (Some(vk), None) => {
                eprintln!(
                    "      ⚠️  VK k-value is {} but could not read prover CIRCUIT_K",
                    vk
                );
            }
            _ => {
                eprintln!("      ⚠️  Could not extract k-values for comparison");
            }
        }
    } else {
        eprintln!("      ⚠️  Halo2VerifyingKey.sol not found");
        skipped += 1;
    }

    // ── Check 2: Merkle root consistency ─────────────────────────────
    eprintln!("[2/8] Checking merkle root consistency...");
    let cli_root = extract_constant(&root.join("cli/src/constants.rs"), "KNOWN_MERKLE_ROOT");
    let deploy_root =
        extract_solidity_constant(&root.join("contracts/script/Deploy.s.sol"), "MERKLE_ROOT");
    let airdrop_test_root = find_test_merkle_root(&root.join("contracts/test"));

    match (cli_root.as_deref(), deploy_root.as_deref()) {
        (Some(cli), Some(deploy)) if !cli.is_empty() && cli == deploy => {
            eprintln!(
                "      ✅ Merkle root consistent: {}...{}",
                &cli[..18],
                &cli[cli.len() - 8..]
            );
            passed += 1;
        }
        (Some(cli), Some(deploy)) if !cli.is_empty() && !deploy.is_empty() => {
            eprintln!(
                "      ❌ Merkle root MISMATCH: CLI={} vs Deploy={}",
                cli, deploy
            );
            failed += 1;
        }
        _ => {
            eprintln!("      ⚠️  Could not extract merkle roots for comparison");
            failed += 1;
        }
    }

    if let Some(test_root) = airdrop_test_root {
        if test_root == cli_root.as_deref().unwrap_or("") {
            eprintln!("      ✅ Test merkle root matches");
        } else {
            eprintln!("      ⚠️  Test merkle root differs from CLI constant (may be intentional for tests)");
        }
    }

    // ── Check 3: Constants consistency ───────────────────────────────
    eprintln!("[3/8] Checking constants consistency...");
    let cli_deadline =
        extract_constant_value(&root.join("cli/src/constants.rs"), "CLAIM_DEADLINE: u64");
    let cli_claim_amount =
        extract_constant_value(&root.join("cli/src/constants.rs"), "CLAIM_AMOUNT: u64");
    let cli_max_claims =
        extract_constant_value(&root.join("cli/src/constants.rs"), "MAX_CLAIMS: u64");

    let mut constants_ok = true;
    if let Some(ref d) = cli_deadline {
        let clean = d.replace('_', "");
        if clean != "1798761600" {
            eprintln!("      ⚠️  CLAIM_DEADLINE = {} (expected 1798761600)", d);
            constants_ok = false;
        }
    }
    if let Some(ref a) = cli_claim_amount {
        let clean = a.replace('_', "");
        if clean != "10000" {
            eprintln!("      ⚠️  CLAIM_AMOUNT = {} (expected 10000)", a);
            constants_ok = false;
        }
    }
    if let Some(ref c) = cli_max_claims {
        let clean = c.replace('_', "");
        if clean != "1000000" {
            eprintln!("      ⚠️  MAX_CLAIMS = {} (expected 1000000)", c);
            constants_ok = false;
        }
    }
    if constants_ok {
        eprintln!("      ✅ CLI constants consistent");
        passed += 1;
    } else {
        failed += 1;
    }

    // ── Check 4: No placeholder values (besides VK) ──────────────────
    eprintln!("[4/8] Checking for placeholder values...");
    let mut placeholder_found = false;
    if let Ok(content) = std::fs::read_to_string(root.join("cli/src/constants.rs")) {
        if content.contains("0x000000000000000000000000000000000000dEaD") {
            eprintln!("      ⚠️  AIRDROP_CONTRACT is still placeholder (0x...dEaD)");
            eprintln!("         Update after deployment");
            placeholder_found = true;
        }
        if content.contains("TODO") {
            eprintln!("      ⚠️  TODO comments found in constants.rs");
            placeholder_found = true;
        }
    }
    if placeholder_found {
        eprintln!(
            "      ⚠️  Placeholders found (expected before deployment, must fix before mainnet)"
        );
        // Don't count as failure — placeholders are expected pre-deployment
        skipped += 1;
    } else {
        eprintln!("      ✅ No placeholder values");
        passed += 1;
    }

    // ── Check 5: Cargo clippy ────────────────────────────────────────
    eprintln!("[5/8] Running cargo clippy...");
    let clippy_output = std::process::Command::new("cargo")
        .args(["clippy", "--workspace", "--", "-D", "warnings"])
        .current_dir(&root)
        .output();
    match clippy_output {
        Ok(output) if output.status.success() => {
            eprintln!("      ✅ Cargo clippy clean");
            passed += 1;
        }
        Ok(output) => {
            eprintln!("      ❌ Cargo clippy warnings/errors:");
            let stderr = String::from_utf8_lossy(&output.stderr);
            for line in stderr
                .lines()
                .filter(|l| l.contains("warning") || l.contains("error"))
                .take(5)
            {
                eprintln!("         {}", line);
            }
            failed += 1;
        }
        Err(e) => {
            eprintln!("      ⚠️  Could not run cargo clippy: {}", e);
            skipped += 1;
        }
    }

    // ── Check 6: Cargo fmt ──────────────────────────────────────────
    eprintln!("[6/8] Checking cargo fmt...");
    let fmt_output = std::process::Command::new("cargo")
        .args(["fmt", "--all", "--", "--check"])
        .current_dir(&root)
        .output();
    match fmt_output {
        Ok(output) if output.status.success() => {
            eprintln!("      ✅ Cargo fmt clean");
            passed += 1;
        }
        Ok(_) => {
            eprintln!("      ❌ Cargo fmt: unformatted files found. Run: cargo fmt --all");
            failed += 1;
        }
        Err(e) => {
            eprintln!("      ⚠️  Could not run cargo fmt: {}", e);
            skipped += 1;
        }
    }

    // ── Check 7: Forge tests ────────────────────────────────────────
    if skip_slow {
        eprintln!("[7/8] Skipping forge tests (--skip-slow)");
        skipped += 1;
    } else {
        eprintln!("[7/8] Running forge tests...");
        let forge_output = std::process::Command::new("forge")
            .args(["test", "--summary"])
            .current_dir(root.join("contracts"))
            .output();
        match forge_output {
            Ok(output) if output.status.success() => {
                let stdout = String::from_utf8_lossy(&output.stdout);
                if let Some(line) = stdout.lines().find(|l| l.contains("tests passed")) {
                    eprintln!("      ✅ {}", line.trim());
                } else {
                    eprintln!("      ✅ Forge tests passed");
                }
                passed += 1;
            }
            Ok(output) => {
                let stderr = String::from_utf8_lossy(&output.stderr);
                eprintln!("      ❌ Forge tests failed:");
                for line in stderr
                    .lines()
                    .filter(|l| l.contains("fail") || l.contains("error"))
                    .take(5)
                {
                    eprintln!("         {}", line);
                }
                failed += 1;
            }
            Err(e) => {
                eprintln!("      ⚠️  Could not run forge test: {}", e);
                eprintln!("         Is Foundry installed?");
                skipped += 1;
            }
        }
    }

    // ── Check 8: Cargo test ─────────────────────────────────────────
    if skip_slow {
        eprintln!("[8/8] Skipping cargo test (--skip-slow)");
        skipped += 1;
    } else {
        eprintln!("[8/8] Running cargo test...");
        let test_output = std::process::Command::new("cargo")
            .args(["test", "--workspace"])
            .current_dir(&root)
            .output();
        match test_output {
            Ok(output) if output.status.success() => {
                let stdout = String::from_utf8_lossy(&output.stdout);
                let total: usize = stdout
                    .lines()
                    .filter_map(|l| {
                        if l.contains("test result:") && l.contains("passed") {
                            l.split_whitespace()
                                .find(|w| w.chars().all(|c| c.is_ascii_digit()))
                                .and_then(|n| n.parse::<usize>().ok())
                        } else {
                            None
                        }
                    })
                    .sum();
                eprintln!("      ✅ Cargo tests passed ({} tests)", total);
                passed += 1;
            }
            Ok(output) => {
                let stderr = String::from_utf8_lossy(&output.stderr);
                eprintln!("      ❌ Cargo tests failed:");
                for line in stderr
                    .lines()
                    .filter(|l| l.contains("FAILED") || l.contains("failures"))
                    .take(5)
                {
                    eprintln!("         {}", line);
                }
                failed += 1;
            }
            Err(e) => {
                eprintln!("      ⚠️  Could not run cargo test: {}", e);
                skipped += 1;
            }
        }
    }

    // ── Summary ──────────────────────────────────────────────────────
    eprintln!();
    eprintln!("════════════════════════════════════════════════════════════");
    eprintln!(
        "  Results: {} passed, {} failed, {} skipped",
        passed, failed, skipped
    );
    eprintln!("════════════════════════════════════════════════════════════");

    if failed > 0 {
        eprintln!();
        eprintln!(
            "  ❌ NOT READY for deployment — fix {} failing check(s)",
            failed
        );
        std::process::exit(1);
    } else {
        eprintln!();
        eprintln!("  ✅ All automated checks passed!");
        eprintln!();
        eprintln!("  Remaining steps before mainnet deployment:");
        eprintln!("    ┌──────────────────────────────────────────────────────────────");
        eprintln!("    │ CRITICAL (blocks deployment):");
        eprintln!("    │ [ ] Re-run full E2E MockProver test (k=24, ~30 min):  ✅ 2026 PASS");
        eprintln!("    │     cargo test -p zkmist-circuits -- --ignored --nocapture");
        eprintln!("    │ [ ] Regenerate Halo2Verifier.sol + Halo2VerifyingKey.sol with");
        eprintln!("    │     gen-production-verifier (now loads range tables, k=24)");
        eprintln!("    │ [ ] Verify VK k-value matches CIRCUIT_K (checked above)");
        eprintln!("    │ [ ] Verify VK has non-zero fixed commitments (checked above)");
        eprintln!("    │ [ ] External security audit of secp256k1 non-native field arithmetic");
        eprintln!("    │     → See: circuits/src/secp256k1.rs security note");
        eprintln!("    │ [ ] Testnet deployment on Base Sepolia with full claim flow");
        eprintln!("    │     → ./scripts/testnet-deploy.sh");
        eprintln!("    │");
        eprintln!("    │ HIGH PRIORITY:");
        eprintln!("    │ [ ] Generate real proof and validate size in [4000, 8000] byte range");
        eprintln!("    │     → cargo run --release -p zkmist-cli -- bench");
        eprintln!("    │ [ ] Benchmark proving time on reference hardware (<60 sec target)");
        eprintln!("    │ [ ] Update AIRDROP_CONTRACT in cli/src/constants.rs after deployment");
        eprintln!("    │ [ ] Set up on-chain monitor: cargo run -p zkmist-tools --bin monitor");
        eprintln!("    │");
        eprintln!("    │ RECOMMENDED:");
        eprintln!("    │ [ ] Run full E2E test suite: ./scripts/e2e-test.sh");
        eprintln!("    │ [ ] Set up monitoring/alerting (BaseScan, Tenderly, Dune)");
        eprintln!("    │ [ ] Consider replacing hand-rolled secp256k1 with audited library");
        eprintln!("    └──────────────────────────────────────────────────────────────");
    }
}

fn extract_constant(file_path: &Path, const_name: &str) -> Option<String> {
    let content = std::fs::read_to_string(file_path).ok()?;
    // Normalize multi-line declarations into single lines
    let normalized: String = content
        .lines()
        .filter(|l| !l.trim().starts_with("//"))
        .collect::<Vec<&str>>()
        .join(" ");
    // Split by semicolons to get individual statements
    for statement in normalized.split(';') {
        if statement.contains(const_name) {
            if let Some(idx) = statement.find('=') {
                let val = statement[idx + 1..].trim().trim_matches('"').trim();
                let clean = val.strip_prefix("0x").unwrap_or(val).replace('_', "");
                if !clean.is_empty() {
                    return Some(clean);
                }
            }
        }
    }
    None
}

fn extract_constant_value(file_path: &Path, const_name: &str) -> Option<String> {
    let content = std::fs::read_to_string(file_path).ok()?;
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("pub const") && trimmed.contains(const_name.split(':').next()?) {
            if let Some(idx) = trimmed.find('=') {
                // Extract value between '=' and ';', stripping comments
                let after_eq = &trimmed[idx + 1..];
                let val = after_eq.split(';').next().unwrap_or("").trim().to_string();
                if !val.is_empty() {
                    return Some(val);
                }
            }
        }
    }
    None
}

fn extract_solidity_constant(file_path: &Path, const_name: &str) -> Option<String> {
    let content = std::fs::read_to_string(file_path).ok()?;
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.contains(const_name) && trimmed.contains("constant") {
            if let Some(idx) = trimmed.find('=') {
                let val = trimmed[idx + 1..]
                    .trim()
                    .trim_end_matches(';')
                    .trim()
                    .replace("0x", "");
                return Some(val);
            }
        }
    }
    None
}

fn find_test_merkle_root(test_dir: &Path) -> Option<String> {
    if let Ok(entries) = std::fs::read_dir(test_dir) {
        for entry in entries.flatten() {
            if let Ok(content) = std::fs::read_to_string(entry.path()) {
                for line in content.lines() {
                    if line.contains("MERKLE_ROOT") && line.contains("0x") {
                        if let Some(start) = line.find("0x") {
                            let hex = &line[start + 2..];
                            let hex_clean: String =
                                hex.chars().take_while(|c| c.is_ascii_hexdigit()).collect();
                            if hex_clean.len() == 64 {
                                return Some(hex_clean);
                            }
                        }
                    }
                }
            }
        }
    }
    None
}

/// Extract the k-value from Halo2VerifyingKey.sol.
/// Looks for the line: `mstore(0x0040, 0x...0015) // k`
fn extract_vk_k(vk_content: &str) -> Option<u32> {
    for line in vk_content.lines() {
        if line.contains("// k") || line.trim().ends_with("// k") {
            // Extract hex value from mstore
            if let Some(start) = line.find("0x") {
                let hex = &line[start + 2..];
                let hex_clean: String = hex.chars().take_while(|c| c.is_ascii_hexdigit()).collect();
                if let Ok(val) = u32::from_str_radix(&hex_clean, 16) {
                    return Some(val);
                }
            }
        }
    }
    None
}

/// Extract CIRCUIT_K from the prover source.
fn extract_prover_k(prover_path: &Path) -> Option<u32> {
    let content = std::fs::read_to_string(prover_path).ok()?;
    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.contains("CIRCUIT_K") && trimmed.contains('=') && !trimmed.starts_with("//") {
            if let Some(idx) = trimmed.find('=') {
                let val = trimmed[idx + 1..].trim().trim_end_matches(';').trim();
                if let Ok(k) = val.parse::<u32>() {
                    return Some(k);
                }
            }
        }
    }
    None
}
