// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {ZKMToken} from "../src/ZKMToken.sol";
import {ZKMAirdrop} from "../src/ZKMAirdrop.sol";
import {Halo2Verifier} from "../src/Halo2Verifier.axiom.sol";
import {MockHalo2Verifier} from "./TestUtils.sol";

/// @title ZKMV2 Integration Test — Full deployment and claim flow
/// @notice Tests the complete integration between all three contracts
///         and validates gas costs, edge cases, and deployment ordering.
///
///         This test uses the actual Halo2Verifier (not a mock) to ensure
///         the structural validation in the current verifier works correctly.
///         For mainnet, the verifier must be regenerated with snark-verifier.
///
///         Run: forge test --match-contract ZKMV2Integration -vvv
contract ZKMV2Integration is Test {
    ZKMToken public token;
    ZKMAirdrop public airdrop;
    Halo2Verifier public verifier;

    bytes32 constant MERKLE_ROOT = 0x00cf0fa589ba3f949eec2774dca17df0c00a99497b31d70b76767d4dba38c0ba;

    address constant DEPLOYER = address(0x1);
    address constant CLAIMANT = address(0x2);
    address constant RELAYER = address(0x3);

    function setUp() public {
        // Simulate the Deploy.s.sol flow
        vm.startPrank(DEPLOYER);

        verifier = new Halo2Verifier();

        // Predict airdrop address (nonce + 1 from token)
        uint256 nonce = vm.getNonce(DEPLOYER);
        address predictedAirdrop = vm.computeCreateAddress(DEPLOYER, nonce + 1);
        token = new ZKMToken(predictedAirdrop);

        // Note: The production verifier from halo2-solidity-verifier always
        // performs real KZG pairing verification.
        vm.stopPrank();
    }

    // ── Deployment integrity ────────────────────────────────────────

    function test_integration_token_deployed_correctly() public view {
        assertEq(token.name(), "ZKMist");
        assertEq(token.symbol(), "ZKM");
        assertEq(token.decimals(), 18);
        assertEq(token.totalSupply(), 0);
        assertEq(token.MAX_SUPPLY(), 10_000_000_000e18);
    }

    function test_integration_verifier_parameters() public view {
        // The production verifier is generated by halo2-solidity-verifier
        // and performs real KZG pairing verification.
        // It doesn't have IS_PRODUCTION_VERIFIER flag — it always does real verification.
        assertTrue(address(verifier).code.length > 0);
    }

    function test_integration_airdrop_rejects_short_proof() public {
        vm.skip(true, "proof-length enforcement removed (axiom verifier handles length)");
        // Short proof is rejected by the airdrop contract's length check.
        MockHalo2Verifier mockV = new MockHalo2Verifier();
        ZKMToken t = new ZKMToken(address(this));
        ZKMAirdrop a = new ZKMAirdrop(address(t), address(mockV), MERKLE_ROOT);
        bytes memory shortProof = new bytes(100);
        vm.expectRevert("Invalid proof length");
        a.claim(shortProof, bytes32(uint256(1)), address(0xB0B));
    }

    function test_integration_airdrop_rejects_long_proof() public {
        vm.skip(true, "proof-length enforcement removed (axiom verifier handles length)");
        // Long proof is rejected by the airdrop contract's length check.
        MockHalo2Verifier mockV = new MockHalo2Verifier();
        ZKMToken t = new ZKMToken(address(this));
        ZKMAirdrop a = new ZKMAirdrop(address(t), address(mockV), MERKLE_ROOT);
        bytes memory longProof = new bytes(10000);
        vm.expectRevert("Invalid proof length");
        a.claim(longProof, bytes32(uint256(1)), address(0xB0B));
    }

    function test_integration_airdrop_rejects_zero_recipient() public {
        // Zero recipient is rejected by the airdrop contract (not verifier)
        bytes memory fakeProof = new bytes(5888);
        MockHalo2Verifier mockV = new MockHalo2Verifier();
        ZKMToken t = new ZKMToken(address(this));
        ZKMAirdrop a = new ZKMAirdrop(address(t), address(mockV), MERKLE_ROOT);
        vm.expectRevert("Recipient cannot be zero");
        a.claim(fakeProof, bytes32(uint256(1)), address(0));
    }

    function test_integration_production_verifier_rejects_invalid_proof() public {
        vm.skip(true, "PSE-specific (verifyProof + VK removed); use RealRoundtrip for axiom verify");
    }

    function test_integration_production_vk_deployed() public {
        vm.skip(true, "Halo2VerifyingKey removed (axiom verifier embeds the VK)");
    }

    // ── Token economics ──────────────────────────────────────────────

    function test_integration_max_supply_math() public pure {
        // Verify: MAX_SUPPLY = MAX_CLAIMS * CLAIM_AMOUNT
        uint256 maxSupply = 10_000_000_000e18;
        uint256 maxClaims = 1_000_000;
        uint256 claimAmount = 10_000e18;
        assertEq(maxClaims * claimAmount, maxSupply, "Supply math must be exact");
    }

    function test_integration_deadline_is_2027() public pure {
        // 2027-01-01 00:00:00 UTC
        uint256 deadline = 1_798_761_600;
        // Verify it's in January 2027 (between 2026-01-01 and 2028-01-01)
        assertGt(deadline, 1_770_988_800); // 2026-01-01
        assertLt(deadline, 1_835_029_200); // 2028-01-01
    }

    // ── Gas benchmarks ──────────────────────────────────────────────

    function testGas_integration_verifier_deploy() public {
        Halo2Verifier v = new Halo2Verifier();
        // Should be relatively cheap since it's just constants + structural checks
        assertGt(address(v).code.length, 0);
    }

    function testGas_integration_token_deploy() public {
        ZKMToken t = new ZKMToken(address(this));
        assertGt(address(t).code.length, 0);
    }

    // ── Deployment safety: real verifier guard ──────────────────────

    function test_integration_airdrop_constructor_accepts_production_verifier() public {
        // The production Halo2Verifier performs real KZG pairing verification.
        // ZKMAirdrop's constructor should store it as the verifier. (This only
        // asserts the constructor wiring — it does NOT verify a real proof; the
        // real-KZG → on-chain round-trip is gated in ZKM.realroundtrip.t.sol.)
        vm.prank(DEPLOYER);
        ZKMToken t = new ZKMToken(address(0x999)); // dummy minter
        ZKMAirdrop a = new ZKMAirdrop(address(t), address(verifier), MERKLE_ROOT);
        assertEq(address(a.verifier()), address(verifier));
    }

    /// @notice Regression guard for the Deploy.s.sol nonce-prediction bug.
    /// @dev The deploy script deploys verifier → vk → token → airdrop (4 CREATEs)
    ///      and must predict the airdrop address to bake it into ZKMToken's
    ///      IMMUTABLE minter. The nonce must be captured BEFORE any deployment
    ///      and the airdrop predicted at `nonce + 3`. An earlier version read
    ///      the nonce AFTER verifier+vk (already advanced by 2) yet still used
    ///      `nonce + 3`, predicting an address nobody controls and reverting
    ///      the post-deploy `token.minter() == address(airdrop)` check — a
    ///      hard deployment blocker. This test locks the corrected pattern.
    function test_integration_deploy_nonce_prediction_matches_script() public {
        vm.startPrank(DEPLOYER);

        // Capture the nonce BEFORE any contract is deployed (Deploy.s.sol fix).
        uint256 deployNonce = vm.getNonce(DEPLOYER);

        // Mirror Deploy.s.sol: verifier, token, airdrop (no VK contract in axiom).
        Halo2Verifier v = new Halo2Verifier();
        address predictedAirdrop = vm.computeCreateAddress(DEPLOYER, deployNonce + 2);
        ZKMToken t = new ZKMToken(predictedAirdrop);
        ZKMAirdrop a = new ZKMAirdrop(address(t), address(v), MERKLE_ROOT);

        vm.stopPrank();

        // The token's immutable minter MUST be the actually-deployed airdrop.
        assertEq(t.minter(), address(a), "Deploy.s.sol nonce prediction broken");
    }

    // ── Token edge cases ────────────────────────────────────────────

    function test_integration_token_rejects_mint_to_zero() public {
        ZKMToken t = new ZKMToken(address(this));
        vm.expectRevert("Mint to zero address");
        t.mint(address(0), 10_000e18);
    }

    function test_integration_token_rejects_zero_amount_mint() public {
        ZKMToken t = new ZKMToken(address(this));
        vm.expectRevert("Amount must be positive");
        t.mint(address(0xB0B), 0);
    }
}
