// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test, console} from "forge-std/Test.sol";
import {ZKMToken} from "../src/ZKMToken.sol";
import {ZKMAirdrop} from "../src/ZKMAirdrop.sol";
import {Halo2Verifier} from "../src/Halo2Verifier.sol";
import {Halo2VerifyingKey} from "../src/Halo2VerifyingKey.sol";

/// @title RealRoundtrip — real Halo2-KZG proof → on-chain verify → mint
/// @notice The single end-to-end integration test that proves the CLI prover's
///         commitment/transcript path matches the production `Halo2Verifier`
///         (real BN254 ecPairing). A proof generated by the CLI prover must be
///         accepted by the deployed verifier and mint 10,000 ZKM.
///
/// ## Gating model (deliberate)
///
/// This test is OFF by default because it requires a real proof fixture that
/// is intentionally NOT committed — it is a build artifact (and under
/// `ZKMIST_DEV_SRS` a *forgeable* dev proof). The fixture is gitignored at
/// `contracts/fixtures/`.
///
///   • Default (`RUN_REAL_ROUNDTRIP` unset): the test SKIPS with a console
///     message. The default `forge test` suite stays green while the fixture
///     is absent — the round-trip is a documented pre-mainnet blocker, not a
///     regression.
///
///   • Opted in (`RUN_REAL_ROUNDTRIP=1`): the test is a HARD GATE. If the
///     fixture is missing, or if the proof fails to verify, the test REVERTS
///     (it does NOT silently skip). This makes the opt-in run a real gate that
///     can never masquerade as `[PASS]` while doing nothing — the failure mode
///     this gate was added to close. Run it immediately before any deployment:
///
///       # 1. Generate the fixture against the PINNED PSE SRS (mainnet-grade):
///       cargo run --release -p zkmist-cli -- gen-roundtrip-fixture
///       #    (NOT ZKMIST_DEV_SRS=1 — that yields a forgeable proof which only
///       #     validates the verifier wiring, not the trust root.)
///       #
///       # 2. Run the gate:
///       RUN_REAL_ROUNDTRIP=1 forge test --match-contract RealRoundtrip -vvv
///       #    Or against a deployed chain:
///       RUN_REAL_ROUNDTRIP=1 forge test --match-contract RealRoundtrip \
///         --fork-url $RPC -vvv
///
/// ## Current status of the on-chain VK
///
/// `contracts/src/Halo2VerifyingKey.sol` is the REAL, regenerated VK at k=23
/// (0x17) with non-zero fixed + permutation commitments (emitted by
/// `gen-production-verifier --emit` against the pinned PSE SRS). The earlier
/// "k=21 placeholder with all-zero fixed commitments" no longer applies. The
/// remaining blocker is therefore generating the fixture + running THIS test
/// green (plus confirming SRS transcript provenance and an external audit —
/// see SECURITY.md).
contract RealRoundtrip is Test {
    ZKMToken internal token;
    ZKMAirdrop internal airdrop;
    Halo2Verifier internal verifier;
    Halo2VerifyingKey internal vk;

    /// `false` ⇒ the test is a no-op (fixture not ready / not opted in). When
    /// `RUN_REAL_ROUNDTRIP=1` is set, `setUp` REVERTS instead of leaving this
    /// false, so an opted-in run can never silently pass — see `setUp`.
    bool internal _enabled;
    string internal _fixtureJson;

    function setUp() public {
        // ── Default path: skip (keep `forge test` green) ───────────────
        if (!vm.envOr("RUN_REAL_ROUNDTRIP", false)) {
            console.log("RealRoundtrip: skipped (set RUN_REAL_ROUNDTRIP=1 to enable).");
            return;
        }

        // ── Opted in: HARD GATE — a missing fixture MUST fail, not skip ─
        // Generating + verifying the fixture is the entire reason to opt in;
        // silently skipping here would let this test report [PASS] while
        // having done nothing — the misleading-green failure mode this gate
        // exists to prevent.
        string memory fixturePath = vm.envOr("ROUNDTRIP_FIXTURE", string("fixtures/real_roundtrip.json"));
        if (!vm.exists(fixturePath)) {
            revert(
                "RealRoundtrip: RUN_REAL_ROUNDTRIP=1 but fixture not found. Generate it with "
                "`cargo run --release -p zkmist-cli -- gen-roundtrip-fixture` (pinned PSE SRS), "
                "then re-run. Hard gate: refusing to skip."
            );
        }
        _fixtureJson = vm.readFile(fixturePath);
        bytes32 merkleRoot = vm.parseJsonBytes32(_fixtureJson, ".merkle_root");

        // ── Deploy the REAL contracts (mirrors script/Deploy.s.sol) ────
        // Token minter is immutable, so predict the airdrop address from the
        // deployer nonce and pass it into the token constructor.
        address deployer = address(this);
        uint256 nonce = vm.getNonce(deployer);
        address predictedAirdrop = vm.computeCreateAddress(deployer, nonce + 3);

        verifier = new Halo2Verifier();
        vk = new Halo2VerifyingKey();
        token = new ZKMToken(predictedAirdrop);
        airdrop = new ZKMAirdrop(address(token), address(verifier), merkleRoot);

        require(token.minter() == address(airdrop), "minter prediction failed");
        require(airdrop.merkleRoot() == merkleRoot, "root mismatch");

        _enabled = true;
        console.log("RealRoundtrip: armed. claim() will run a real KZG verify + mint.");
        console.log("  If it reverts with 'Invalid proof', the prover transcript path and the");
        console.log("  on-chain Halo2Verifier/VK disagree (different SRS, k, or VK).");
    }

    /// @dev The single, real round-trip: proof → verifier → mint → state.
    ///      When opted in and armed there is NO early return — any verifier
    ///      failure surfaces as a test failure here.
    function test_realKzgRoundtrip() public {
        if (!_enabled) {
            console.log("RealRoundtrip: not armed -- nothing to run. See test header.");
            return;
        }

        bytes memory proof = vm.parseJsonBytes(_fixtureJson, ".proof");
        bytes32 nullifier = vm.parseJsonBytes32(_fixtureJson, ".nullifier");
        address recipient = vm.parseJsonAddress(_fixtureJson, ".recipient");

        // Sanity: the proof length must match Halo2Verifier's hardcoded 5888.
        // (The contract re-checks this authoritatively; this gives a clearer
        // failure than the verifier's boolean return.)
        assertEq(proof.length, 5888, "proof length != 5888 (Halo2Verifier expects 0x1700)");
        assertNotEq(recipient, address(0), "fixture recipient is zero");

        // Pre-conditions the contract checks before the expensive pairing.
        assertFalse(airdrop.usedNullifiers(nullifier), "nullifier already used");
        assertLt(airdrop.totalClaims(), airdrop.MAX_CLAIMS(), "claim cap reached");

        // Expect Claimed(nullifier, 10000e18, recipient, 1).
        vm.expectEmit(true, false, true, true);
        emit ZKMAirdrop.Claimed(nullifier, 10_000e18, recipient, 1);

        uint256 balBefore = token.balanceOf(recipient);
        airdrop.claim(proof, nullifier, recipient);
        uint256 balAfter = token.balanceOf(recipient);

        // ── Post-claim invariants ─────────────────────────────────────
        assertEq(balAfter - balBefore, 10_000e18, "recipient did not receive 10,000 ZKM");
        assertEq(token.totalSupply(), 10_000e18, "totalSupply != 10,000 ZKM after first claim");
        assertTrue(airdrop.usedNullifiers(nullifier), "nullifier not marked used");
        assertEq(airdrop.totalClaims(), 1, "totalClaims not incremented");

        console.log("RealRoundtrip: OK -- real KZG proof verified on-chain, 10,000 ZKM minted.");
    }

    /// @dev Double-claim with the SAME nullifier must revert (nullifier guard).
    function test_realKzgDoubleClaimRejected() public {
        if (!_enabled) {
            console.log("RealRoundtrip: not armed -- double-claim test skipped.");
            return;
        }
        bytes memory proof = vm.parseJsonBytes(_fixtureJson, ".proof");
        bytes32 nullifier = vm.parseJsonBytes32(_fixtureJson, ".nullifier");
        address recipient = vm.parseJsonAddress(_fixtureJson, ".recipient");

        airdrop.claim(proof, nullifier, recipient); // first claim succeeds

        vm.expectRevert(bytes("Already claimed"));
        airdrop.claim(proof, nullifier, recipient); // second must revert
    }
}
