// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {ZKMToken} from "../src/ZKMToken.sol";
import {ZKMAirdrop} from "../src/ZKMAirdrop.sol";
import {Halo2Verifier} from "../src/Halo2Verifier.sol";
import {MockHalo2Verifier} from "./TestUtils.sol";

/// @title ZKMV2 Integration Test — Full deployment and claim flow
/// @notice Tests the complete integration between all three contracts
///         and validates gas costs, edge cases, and deployment ordering.
///
///         This test uses the actual Halo2Verifier (not a mock) to ensure
///         the structural validation in the current verifier works correctly.
///         For mainnet, the verifier must be regenerated with snark-verifier.
///
///         Run: forge test --match-contract ZKMV2Integration -vvv
contract ZKMV2Integration is Test {
    ZKMToken public token;
    ZKMAirdrop public airdrop;
    Halo2Verifier public verifier;

    bytes32 constant MERKLE_ROOT = 0x1eafd6f3b8f30af949ff5493e9102853a7c22f8cffdcf018daa31d4245797844;

    address constant DEPLOYER = address(0x1);
    address constant CLAIMANT = address(0x2);
    address constant RELAYER = address(0x3);

    function setUp() public {
        // Simulate the Deploy.s.sol flow
        vm.startPrank(DEPLOYER);

        verifier = new Halo2Verifier();

        // Predict airdrop address (nonce + 1 from token)
        uint256 nonce = vm.getNonce(DEPLOYER);
        address predictedAirdrop = vm.computeCreateAddress(DEPLOYER, nonce + 1);
        token = new ZKMToken(predictedAirdrop);

        // Note: The production verifier from halo2-solidity-verifier always
        // performs real KZG pairing verification.
        vm.stopPrank();
    }

    // ── Deployment integrity ────────────────────────────────────────

    function test_integration_token_deployed_correctly() public view {
        assertEq(token.name(), "ZKMist");
        assertEq(token.symbol(), "ZKM");
        assertEq(token.decimals(), 18);
        assertEq(token.totalSupply(), 0);
        assertEq(token.MAX_SUPPLY(), 10_000_000_000e18);
    }

    function test_integration_verifier_parameters() public view {
        // The production verifier is generated by halo2-solidity-verifier
        // and performs real KZG pairing verification.
        // It doesn't have IS_PRODUCTION_VERIFIER flag — it always does real verification.
        assertTrue(address(verifier).code.length > 0);
    }

    function test_integration_verifier_rejects_short_proof() public {
        // Short proof is rejected by the airdrop contract's length check.
        MockHalo2Verifier mockV = new MockHalo2Verifier();
        ZKMToken t = new ZKMToken(address(this));
        ZKMAirdrop a = new ZKMAirdrop(address(t), address(mockV), address(0), MERKLE_ROOT);
        bytes memory shortProof = new bytes(100);
        vm.expectRevert("Invalid proof length");
        a.claim(shortProof, bytes32(uint256(1)), address(0xB0B));
    }

    function test_integration_verifier_rejects_long_proof() public {
        // Long proof is rejected by the airdrop contract's length check.
        MockHalo2Verifier mockV = new MockHalo2Verifier();
        ZKMToken t = new ZKMToken(address(this));
        ZKMAirdrop a = new ZKMAirdrop(address(t), address(mockV), address(0), MERKLE_ROOT);
        bytes memory longProof = new bytes(2000);
        vm.expectRevert("Invalid proof length");
        a.claim(longProof, bytes32(uint256(1)), address(0xB0B));
    }

    function test_integration_verifier_rejects_zero_recipient() public {
        // Zero recipient is rejected by the airdrop contract (not verifier)
        bytes memory fakeProof = new bytes(500);
        MockHalo2Verifier mockV = new MockHalo2Verifier();
        ZKMToken t = new ZKMToken(address(this));
        ZKMAirdrop a = new ZKMAirdrop(address(t), address(mockV), address(0), MERKLE_ROOT);
        vm.expectRevert("Recipient cannot be zero");
        a.claim(fakeProof, bytes32(uint256(1)), address(0));
    }

    function test_integration_verifier_proof_validation() public {
        // The production verifier performs real KZG pairing verification.
        // It requires a deployed VK contract. Without a valid VK + valid proof,
        // verification fails. This is tested at the airdrop level.
        // Here we just verify the verifier contract deployed correctly.
        assertTrue(address(verifier).code.length > 0);
    }

    // ── Token economics ──────────────────────────────────────────────

    function test_integration_max_supply_math() public pure {
        // Verify: MAX_SUPPLY = MAX_CLAIMS * CLAIM_AMOUNT
        uint256 maxSupply = 10_000_000_000e18;
        uint256 maxClaims = 1_000_000;
        uint256 claimAmount = 10_000e18;
        assertEq(maxClaims * claimAmount, maxSupply, "Supply math must be exact");
    }

    function test_integration_deadline_is_2027() public pure {
        // 2027-01-01 00:00:00 UTC
        uint256 deadline = 1_798_761_600;
        // Verify it's in January 2027 (between 2026-01-01 and 2028-01-01)
        assertGt(deadline, 1_770_988_800); // 2026-01-01
        assertLt(deadline, 1_835_029_200); // 2028-01-01
    }

    // ── Gas benchmarks ──────────────────────────────────────────────

    function testGas_integration_verifier_deploy() public {
        Halo2Verifier v = new Halo2Verifier();
        // Should be relatively cheap since it's just constants + structural checks
        assertGt(address(v).code.length, 0);
    }

    function testGas_integration_token_deploy() public {
        ZKMToken t = new ZKMToken(address(this));
        assertGt(address(t).code.length, 0);
    }

    // ── Deployment safety: real verifier guard ──────────────────────

    function test_integration_production_verifier_accepted() public {
        // The production Halo2Verifier performs real KZG pairing verification.
        // ZKMAirdrop should accept it.
        vm.prank(DEPLOYER);
        ZKMToken t = new ZKMToken(address(0x999)); // dummy minter
        ZKMAirdrop a = new ZKMAirdrop(address(t), address(verifier), address(0), MERKLE_ROOT);
        assertEq(address(a.verifier()), address(verifier));
    }

    // ── Token edge cases ────────────────────────────────────────────

    function test_integration_token_rejects_mint_to_zero() public {
        ZKMToken t = new ZKMToken(address(this));
        vm.expectRevert("Mint to zero address");
        t.mint(address(0), 10_000e18);
    }

    function test_integration_token_rejects_zero_amount_mint() public {
        ZKMToken t = new ZKMToken(address(this));
        vm.expectRevert("Amount must be positive");
        t.mint(address(0xB0B), 0);
    }
}
