// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test, console} from "forge-std/Test.sol";
import {ZKMToken} from "../src/ZKMToken.sol";
import {ZKMAirdrop} from "../src/ZKMAirdrop.sol";
import {Halo2Verifier} from "../src/Halo2Verifier.sol";
import {Halo2VerifyingKey} from "../src/Halo2VerifyingKey.sol";

/// @title RealRoundtrip — real Halo2-KZG proof → on-chain verify → mint
/// @notice Scaffold for the documented deployment blocker "the real-KZG →
///         on-chain verifier loop has never been exercised" (see SECURITY.md).
///         Once it passes, it is the first ever honest on-chain verification:
///         a proof generated by the CLI prover is accepted by the production
///         `Halo2Verifier` (real BN254 ecPairing) and mints 10,000 ZKM.
///
/// This test is OFF by default because it needs two deployment artifacts that
/// are intentionally NOT in the repo:
///
///   1. A real `Halo2VerifyingKey.sol` regenerated at k=23 with non-zero
///      fixed commitments. The committed VK is still the placeholder (k=21,
///      all-zero fixed comms) — every proof reverts with "Invalid proof"
///      until it is regenerated:
///        cargo run --release -p gen-production-verifier -- --k 23 \
///          --params-file <pinned PSE SRS> --emit
///
///   2. A real proof fixture produced by the CLI prover:
///        # pinned SRS (mainnet-grade):
///        cargo run --release -p zkmist-cli -- gen-roundtrip-fixture
///        # OR a local forgeable SRS (validates the verifier, NOT soundness):
///        ZKMIST_DEV_SRS=1 cargo run --release -p zkmist-cli -- gen-roundtrip-fixture
///
/// Run:
///   RUN_REAL_ROUNDTRIP=1 forge test --match-contract RealRoundtrip -vvv
///
/// Fork against a deployed chain instead of the in-process EVM:
///   RUN_REAL_ROUNDTRIP=1 forge test --match-contract RealRoundtrip \
///     --fork-url $RPC -vvv
contract RealRoundtrip is Test {
    ZKMToken internal token;
    ZKMAirdrop internal airdrop;
    Halo2Verifier internal verifier;
    Halo2VerifyingKey internal vk;

    /// `false` ⇒ the test is a no-op (fixture/VK not ready). We avoid a hard
    /// `revert` so the default `forge test` suite stays green while the
    /// deployment blockers are pending; opting in flips it to a real gate.
    bool internal _enabled;
    string internal _fixtureJson;

    function setUp() public {
        // ── Opt-in gate ───────────────────────────────────────────────
        if (!vm.envOr("RUN_REAL_ROUNDTRIP", false)) {
            console.log("RealRoundtrip: skipped (set RUN_REAL_ROUNDTRIP=1 to enable).");
            return;
        }

        // ── Fixture gate ──────────────────────────────────────────────
        // Path is relative to the foundry root (contracts/). The CLI writes
        // `zkmist gen-roundtrip-fixture` (default `contracts/fixtures/...` from
        // the repo root) to this same file.
        string memory fixturePath = vm.envOr("ROUNDTRIP_FIXTURE", string("fixtures/real_roundtrip.json"));
        if (!vm.exists(fixturePath)) {
            console.log("RealRoundtrip: fixture not found at", fixturePath);
            console.log("  Generate it with: zkmist gen-roundtrip-fixture");
            return;
        }
        _fixtureJson = vm.readFile(fixturePath);
        bytes32 merkleRoot = vm.parseJsonBytes32(_fixtureJson, ".merkle_root");

        // ── Deploy the REAL contracts (mirrors script/Deploy.s.sol) ────
        // Token minter is immutable, so predict the airdrop address from the
        // deployer nonce and pass it into the token constructor.
        address deployer = address(this);
        uint256 nonce = vm.getNonce(deployer);
        address predictedAirdrop = vm.computeCreateAddress(deployer, nonce + 3);

        verifier = new Halo2Verifier();
        vk = new Halo2VerifyingKey();
        token = new ZKMToken(predictedAirdrop);
        airdrop = new ZKMAirdrop(address(token), address(verifier), address(vk), merkleRoot);

        require(token.minter() == address(airdrop), "minter prediction failed");
        require(airdrop.merkleRoot() == merkleRoot, "root mismatch");

        _enabled = true;
        console.log("RealRoundtrip: armed. If claim() reverts with 'Invalid proof',");
        console.log("  the on-chain Halo2VerifyingKey.sol is still the placeholder --");
        console.log("  regenerate it with gen-production-verifier (see test header).");
    }

    /// @dev The single, real round-trip: proof → verifier → mint → state.
    function test_realKzgRoundtrip() public {
        if (!_enabled) {
            // Soft skip: fixture and/or opt-in missing. Not a failure.
            console.log("RealRoundtrip: not armed -- nothing to run. See test header.");
            return;
        }

        bytes memory proof = vm.parseJsonBytes(_fixtureJson, ".proof");
        bytes32 nullifier = vm.parseJsonBytes32(_fixtureJson, ".nullifier");
        address recipient = vm.parseJsonAddress(_fixtureJson, ".recipient");

        // Sanity: the proof length must match Halo2Verifier's hardcoded 5632.
        // (The contract re-checks this authoritatively; this gives a clearer
        // failure than the verifier's boolean return.)
        assertEq(proof.length, 5632, "proof length != 5632 (Halo2Verifier expects 0x1600)");
        assertNotEq(recipient, address(0), "fixture recipient is zero");

        // Pre-conditions the contract checks before the expensive pairing.
        assertFalse(airdrop.usedNullifiers(nullifier), "nullifier already used");
        assertLt(airdrop.totalClaims(), airdrop.MAX_CLAIMS(), "claim cap reached");

        // Expect Claimed(nullifier, 10000e18, recipient, 1).
        vm.expectEmit(true, false, true, true);
        emit ZKMAirdrop.Claimed(nullifier, 10_000e18, recipient, 1);

        uint256 balBefore = token.balanceOf(recipient);
        airdrop.claim(proof, nullifier, recipient);
        uint256 balAfter = token.balanceOf(recipient);

        // ── Post-claim invariants ─────────────────────────────────────
        assertEq(balAfter - balBefore, 10_000e18, "recipient did not receive 10,000 ZKM");
        assertEq(token.totalSupply(), 10_000e18, "totalSupply != 10,000 ZKM after first claim");
        assertTrue(airdrop.usedNullifiers(nullifier), "nullifier not marked used");
        assertEq(airdrop.totalClaims(), 1, "totalClaims not incremented");

        console.log("RealRoundtrip: OK -- real KZG proof verified on-chain, 10,000 ZKM minted.");
    }

    /// @dev Double-claim with the SAME nullifier must revert (nullifier guard).
    function test_realKzgDoubleClaimRejected() public {
        if (!_enabled) {
            console.log("RealRoundtrip: not armed -- double-claim test skipped.");
            return;
        }
        bytes memory proof = vm.parseJsonBytes(_fixtureJson, ".proof");
        bytes32 nullifier = vm.parseJsonBytes32(_fixtureJson, ".nullifier");
        address recipient = vm.parseJsonAddress(_fixtureJson, ".recipient");

        airdrop.claim(proof, nullifier, recipient); // first claim succeeds

        vm.expectRevert(bytes("Already claimed"));
        airdrop.claim(proof, nullifier, recipient); // second must revert
    }
}
