// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Script, console} from "forge-std/Script.sol";
import {ZKMToken} from "../src/ZKMToken.sol";
import {ZKMAirdrop} from "../src/ZKMAirdrop.sol";
import {Halo2Verifier} from "../src/Halo2Verifier.sol";
import {Halo2VerifyingKey} from "../src/Halo2VerifyingKey.sol";

/// @title Deploy — Deploy ZKMist contracts (Halo2-KZG)
/// @notice Deploys Halo2Verifier, Halo2VerifyingKey, ZKMToken, and ZKMAirdrop to Base.
///
/// Usage:
///   # Testnet (Base Sepolia):
///   forge script script/Deploy.s.sol --rpc-url $BASE_SEPOLIA_RPC --broadcast
///
///   # Mainnet (Base):
///   forge script script/Deploy.s.sol --rpc-url $BASE_RPC --broadcast
///
/// Prerequisites:
///   1. Halo2Verifier.sol generated by halo2-solidity-verifier
///   2. Halo2VerifyingKey.sol generated by halo2-solidity-verifier
///   3. Deployer must have ETH on Base for gas (~$0.50 for all 4 contracts)

contract Deploy is Script {
    // ── Configuration ────────────────────────────────────────────────────

    /// Merkle root of the eligibility tree.
    /// 64,116,228 qualified addresses, 26-level Poseidon, BN254.
    bytes32 constant MERKLE_ROOT = 0x1eafd6f3b8f30af949ff5493e9102853a7c22f8cffdcf018daa31d4245797844;

    /// Expected claim deadline: 2027-01-01 00:00:00 UTC
    uint256 constant EXPECTED_CLAIM_DEADLINE = 1_798_761_600;

    /// Expected claim amount: 10,000 ZKM
    uint256 constant EXPECTED_CLAIM_AMOUNT = 10_000e18;

    /// Expected max claims: 1,000,000
    uint256 constant EXPECTED_MAX_CLAIMS = 1_000_000;

    /// Minimum ETH balance for deployer (gas for 4 contract deploys)
    uint256 constant MIN_DEPLOYER_BALANCE = 0.01 ether;

    // ── Deployment ───────────────────────────────────────────────────────

    function run() external {
        uint256 deployerKey = vm.envUint("PRIVATE_KEY");
        address deployer = vm.addr(deployerKey);

        vm.startBroadcast(deployerKey);

        // ── Pre-deployment validation ─────────────────────────────────
        console.log("=== ZKMist Deployment ===");
        console.log("Deployer:", deployer);
        console.log("Chain ID:", block.chainid);
        console.log("Deployer balance:", deployer.balance);
        console.log("");

        // Validate chain
        require(block.chainid == 8453 || block.chainid == 84532, "Must deploy on Base (8453) or Base Sepolia (84532)");

        // Validate deadline is in the future
        require(block.timestamp < EXPECTED_CLAIM_DEADLINE, "Claim deadline has already passed");

        // Validate deployer has enough ETH for gas
        require(deployer.balance >= MIN_DEPLOYER_BALANCE, "Insufficient ETH for deployment");

        // ── Step 1: Deploy Halo2Verifier ──────────────────────────────
        console.log("Step 1: Deploying Halo2Verifier...");
        Halo2Verifier verifier = new Halo2Verifier();
        console.log("  Halo2Verifier:", address(verifier));

        // ── Step 2: Deploy Halo2VerifyingKey ──────────────────────────
        console.log("");
        console.log("Step 2: Deploying Halo2VerifyingKey...");
        Halo2VerifyingKey vk = new Halo2VerifyingKey();
        console.log("  Halo2VerifyingKey:", address(vk));

        // ── Step 3: Predict airdrop address ───────────────────────────
        uint256 nonce = vm.getNonce(deployer);
        // verifier at nonce, vk at nonce+1, token at nonce+2, airdrop at nonce+3
        address predictedAirdrop = vm.computeCreateAddress(deployer, nonce + 3);
        console.log("");
        console.log("Step 3: Predicting addresses...");
        console.log("  Current nonce:", nonce);
        console.log("  Predicted airdrop:", predictedAirdrop);

        // ── Step 4: Deploy ZKMToken ──────────────────────────────────
        console.log("");
        console.log("Step 4: Deploying ZKMToken...");
        ZKMToken token = new ZKMToken(predictedAirdrop);
        console.log("  ZKMToken:", address(token));
        console.log("  Minter (predicted airdrop):", predictedAirdrop);
        console.log("  Max supply:", token.MAX_SUPPLY());
        require(token.minter() == predictedAirdrop, "Minter prediction failed");

        // ── Step 5: Deploy ZKMAirdrop ─────────────────────────────────
        console.log("");
        console.log("Step 5: Deploying ZKMAirdrop...");
        ZKMAirdrop airdrop = new ZKMAirdrop(address(token), address(verifier), address(vk), MERKLE_ROOT);
        console.log("  ZKMAirdrop:", address(airdrop));

        // ── Post-deployment validation ────────────────────────────────
        console.log("");
        console.log("=== Post-deployment validation ===");

        // Verify minter matches actual airdrop address
        require(token.minter() == address(airdrop), "Minter mismatch");
        console.log("  [OK] Minter matches airdrop address");

        // Verify airdrop parameters
        require(airdrop.merkleRoot() == MERKLE_ROOT, "Root mismatch");
        console.log("  [OK] Merkle root matches");

        require(airdrop.CLAIM_AMOUNT() == EXPECTED_CLAIM_AMOUNT, "Claim amount mismatch");
        console.log("  [OK] Claim amount: 10,000 ZKM");

        require(airdrop.MAX_CLAIMS() == EXPECTED_MAX_CLAIMS, "Max claims mismatch");
        console.log("  [OK] Max claims: 1,000,000");

        require(airdrop.CLAIM_DEADLINE() == EXPECTED_CLAIM_DEADLINE, "Deadline mismatch");
        console.log("  [OK] Claim deadline: 2027-01-01 00:00:00 UTC");

        require(address(airdrop.token()) == address(token), "Token mismatch");
        console.log("  [OK] Token reference correct");

        require(address(airdrop.verifier()) == address(verifier), "Verifier mismatch");
        console.log("  [OK] Verifier reference correct");

        require(address(airdrop.verifyingKey()) == address(vk), "VK mismatch");
        console.log("  [OK] VerifyingKey reference correct");

        vm.stopBroadcast();

        // ── Summary ───────────────────────────────────────────────────
        console.log("");
        console.log("=== Deployment Summary ===");
        console.log("Halo2Verifier:     ", address(verifier));
        console.log("Halo2VerifyingKey: ", address(vk));
        console.log("ZKMToken:          ", address(token));
        console.log("ZKMAirdrop:        ", address(airdrop));
        console.log("Chain:             %s", block.chainid == 8453 ? "Base (mainnet)" : "Base Sepolia (testnet)");
        console.log("");
        console.log("Next steps:");
        console.log("  1. Verify contracts on BaseScan:");
        console.log("     forge verify-contract <address> Halo2Verifier --chain base");
        console.log("     forge verify-contract <address> Halo2VerifyingKey --chain base");
        console.log("     forge verify-contract <address> ZKMToken --chain base");
        console.log("     forge verify-contract <address> ZKMAirdrop --chain base");
        console.log("  2. Update cli/src/constants.rs:");
        console.log("     AIRDROP_CONTRACT = \"%s\"", address(airdrop));
        console.log("  3. Test claim on testnet first (if testnet)");
        console.log("  4. Generate a proof and submit to validate E2E");
    }
}
