// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Script, console} from "forge-std/Script.sol";
import {ZKMToken} from "../src/ZKMToken.sol";
import {ZKMAirdrop} from "../src/ZKMAirdrop.sol";
import {Halo2Verifier} from "../src/Halo2Verifier.axiom.sol";

/// @title Deploy — Deploy ZKMist contracts (axiom Halo2-KZG)
/// @notice Deploys Halo2Verifier (snark-verifier-generated, embeds the VK),
///         ZKMToken, and ZKMAirdrop to Base.
///
/// Usage:
///   # Testnet (Base Sepolia):
///   forge script script/Deploy.s.sol --rpc-url $BASE_SEPOLIA_RPC --broadcast
///
///   # Mainnet (Base):
///   forge script script/Deploy.s.sol --rpc-url $BASE_RPC --broadcast
///
/// Prerequisites:
///   1. contracts/src/Halo2Verifier.axiom.sol generated by snark-verifier-sdk
///      (depth-26, k=21). No separate verifying-key contract (the VK is embedded).

contract Deploy is Script {
    // ── Configuration ────────────────────────────────────────────────────

    /// Merkle root of the eligibility tree (halo2-base Poseidon convention,
    /// 26-level, BN254) — the SAME convention the axiom claim circuit verifies.
    /// Re-derived from the 64,116,228-address list via a parallel halo2-base
    /// build (validated against the serial production builder). Single source
    /// of truth on-chain: MUST equal `KNOWN_MERKLE_ROOT` in `cli/src/constants.rs`
    /// (the CLI's compile-time pin and out-of-band integrity check for the same
    /// eligibility build). Keep the two in lockstep — they are the same
    /// committed root. NOTE: the prior value `0x1eafd6f3…` was a legacy
    /// light-poseidon (Circom) root that the axiom circuit cannot verify.
    bytes32 constant MERKLE_ROOT = 0x00cf0fa589ba3f949eec2774dca17df0c00a99497b31d70b76767d4dba38c0ba;

    uint256 constant EXPECTED_CLAIM_DEADLINE = 1_798_761_600; // 2027-01-01 UTC
    uint256 constant EXPECTED_CLAIM_AMOUNT = 10_000e18;
    uint256 constant EXPECTED_MAX_CLAIMS = 1_000_000;
    uint256 constant MIN_DEPLOYER_BALANCE = 0.01 ether;

    function run() external {
        uint256 deployerKey = vm.envUint("PRIVATE_KEY");
        address deployer = vm.addr(deployerKey);

        vm.startBroadcast(deployerKey);

        console.log("=== ZKMist Deployment ===");
        console.log("Deployer:", deployer);
        console.log("Chain ID:", block.chainid);
        console.log("Deployer balance:", deployer.balance);
        console.log("");

        require(block.chainid == 8453 || block.chainid == 84532, "Must deploy on Base (8453) or Base Sepolia (84532)");
        require(block.timestamp < EXPECTED_CLAIM_DEADLINE, "Claim deadline has already passed");
        require(deployer.balance >= MIN_DEPLOYER_BALANCE, "Insufficient ETH for deployment");

        // Capture the deployer nonce BEFORE any contract is deployed so the
        // airdrop address is predictable (token's immutable minter must point
        // at it). Without a verifying-key contract, the order is:
        // verifier(deployNonce), token(+1), airdrop(+2).
        uint256 deployNonce = vm.getNonce(deployer);

        // ── Step 1: Deploy Halo2Verifier (axiom, embeds VK) ───────────
        console.log("Step 1: Deploying Halo2Verifier...");
        Halo2Verifier verifier = new Halo2Verifier();
        console.log("  Halo2Verifier:", address(verifier));

        // ── Step 2: Predict airdrop address ───────────────────────────
        address predictedAirdrop = vm.computeCreateAddress(deployer, deployNonce + 2);
        console.log("");
        console.log("Step 2: Predicting airdrop address...");
        console.log("  Predicted airdrop:", predictedAirdrop);

        // ── Step 3: Deploy ZKMToken ──────────────────────────────────
        console.log("");
        console.log("Step 3: Deploying ZKMToken...");
        ZKMToken token = new ZKMToken(predictedAirdrop);
        console.log("  ZKMToken:", address(token));
        require(token.minter() == predictedAirdrop, "Minter prediction failed");

        // ── Step 4: Deploy ZKMAirdrop ─────────────────────────────────
        console.log("");
        console.log("Step 4: Deploying ZKMAirdrop...");
        ZKMAirdrop airdrop = new ZKMAirdrop(address(token), address(verifier), MERKLE_ROOT);
        console.log("  ZKMAirdrop:", address(airdrop));

        // ── Post-deployment validation ────────────────────────────────
        console.log("");
        console.log("=== Post-deployment validation ===");
        require(token.minter() == address(airdrop), "Minter mismatch");
        console.log("  [OK] Minter matches airdrop address");
        require(airdrop.merkleRoot() == MERKLE_ROOT, "Root mismatch");
        console.log("  [OK] Merkle root matches");
        require(airdrop.CLAIM_AMOUNT() == EXPECTED_CLAIM_AMOUNT, "Claim amount mismatch");
        console.log("  [OK] Claim amount: 10,000 ZKM");
        require(airdrop.MAX_CLAIMS() == EXPECTED_MAX_CLAIMS, "Max claims mismatch");
        console.log("  [OK] Max claims: 1,000,000");
        require(airdrop.CLAIM_DEADLINE() == EXPECTED_CLAIM_DEADLINE, "Deadline mismatch");
        console.log("  [OK] Claim deadline: 2027-01-01 00:00:00 UTC");
        require(address(airdrop.token()) == address(token), "Token mismatch");
        console.log("  [OK] Token reference correct");
        require(address(airdrop.verifier()) == address(verifier), "Verifier mismatch");
        console.log("  [OK] Verifier reference correct");

        vm.stopBroadcast();

        console.log("");
        console.log("=== Deployment Summary ===");
        console.log("Halo2Verifier: ", address(verifier));
        console.log("ZKMToken:      ", address(token));
        console.log("ZKMAirdrop:    ", address(airdrop));
        console.log("Chain:         %s", block.chainid == 8453 ? "Base (mainnet)" : "Base Sepolia (testnet)");
        console.log("");
        console.log("Next steps:");
        console.log("  1. Verify contracts on BaseScan.");
        console.log("  2. Update cli/src/constants.rs AIRDROP_CONTRACT = \"%s\"", address(airdrop));
        console.log("  3. Generate a proof and submit to validate E2E.");
    }
}
