//! Axiom-stack Poseidon hash gadget (`halo2-base`) — Phase 1 of the axiom
//! backend migration (see `docs/axiom-backend-migration.md`).
//!
//! This is the audited-library replacement for the hand-rolled PSE
//! `poseidon.rs`, intended for the future axiom-backend circuit (Phase 3). It
//! coexists with `poseidon.rs` until the whole circuit is rewritten onto the
//! axiom `Context` eDSL — the two stacks use *different* `Fr` types
//! (`halo2curves-axiom` vs PSE `halo2curves`) and cannot be mixed within one
//! circuit.
//!
//! # Permutation parameters — Circom / light-poseidon compatible
//!
//! The permutation (MDS matrix + round constants, generated by the standard
//! Grain-LFSR algorithm via `OptimizedPoseidonSpec`) is identical to
//! `light-poseidon` v0.4's `new_circom(...)` on BN254:
//!
//! | Variant   | t  | RATE | R_F | R_P | Inputs | Usage                          |
//! |-----------|----|------|-----|-----|--------|--------------------------------|
//! | Leaf      | 2  | 1    | 8   | 56  | 1      | `poseidon(address)`            |
//! | Interior  | 3  | 2    | 8   | 57  | 2      | `poseidon(left, right)` / null |
//!
//! Parameter equivalence is proven in `tests/poseidon_axiom.rs` (the spec's raw
//! permutation reproduces `light-poseidon::Poseidon::hash` byte-for-byte).
//!
//! # Sponge convention — Phase 3 reconciliation required
//!
//! The PERMUTATIONS match, but the HASH functions differ by construction:
//!
//! | Aspect            | halo2-base (this gadget) | light-poseidon / Circom (`zkmist-merkle-tree`) |
//! |-------------------|--------------------------|------------------------------------------------|
//! | Capacity element  | `2^64`                   | `0`                                            |
//! | Input padding     | `1` then `0`s            | none for a full RATE block                     |
//! | Squeeze           | extra empty permutation when absorbed length ≡ 0 (mod RATE) | single permutation |
//! | Digest output     | `state[1]`               | `state[0]`                                     |
//!
//! The off-chain Merkle tree (`zkmist-merkle-tree`) and the existing PSE
//! circuit commit to the light-poseidon convention. Phase 3 must reconcile
//! this so the circuit verifies the *same* tree that is committed on-chain:
//! either (a) rebuild the off-chain tree / nullifier under halo2-base's
//! convention (audited, standard), or (b) wrap this chip to replicate the
//! Circom convention. This decision does not affect Phase 1 — the chip and its
//! parameters are correct either way (verified below).

use halo2_base::{
    gates::RangeInstructions,
    halo2_proofs::halo2curves::bn256::Fr,
    poseidon::hasher::{spec::OptimizedPoseidonSpec, PoseidonHasher},
    AssignedValue, Context,
};

/// Build the leaf-hash spec: t=2, RATE=1, R_F=8, R_P=56 (`light-poseidon`
/// `new_circom(1)` equivalent). One permutation input.
pub fn leaf_spec() -> OptimizedPoseidonSpec<Fr, 2, 1> {
    OptimizedPoseidonSpec::<Fr, 2, 1>::new::<8, 56, 0>()
}

/// Build the interior-hash spec: t=3, RATE=2, R_F=8, R_P=57 (`light-poseidon`
/// `new_circom(2)` equivalent). Two permutation inputs (Merkle interior nodes
/// and the nullifier).
pub fn interior_spec() -> OptimizedPoseidonSpec<Fr, 3, 2> {
    OptimizedPoseidonSpec::<Fr, 3, 2>::new::<8, 57, 0>()
}

/// Hash a single field element with the leaf hasher: `poseidon(x)` (t=2).
///
/// Uses halo2-base's sponge convention (see the module docs). Returns the
/// assigned digest.
pub fn hash_leaf(
    ctx: &mut Context<Fr>,
    range: &impl RangeInstructions<Fr>,
    x: AssignedValue<Fr>,
) -> AssignedValue<Fr> {
    let mut hasher = PoseidonHasher::new(leaf_spec());
    hasher.initialize_consts(ctx, range.gate());
    hasher.hash_fix_len_array(ctx, range.gate(), &[x])
}

/// Hash two field elements with the interior hasher: `poseidon(a, b)` (t=3).
///
/// Used for Merkle interior nodes (`poseidon(left, right)`) and the nullifier
/// (`poseidon(key, domain)`). Uses halo2-base's sponge convention.
pub fn hash_interior(
    ctx: &mut Context<Fr>,
    range: &impl RangeInstructions<Fr>,
    a: AssignedValue<Fr>,
    b: AssignedValue<Fr>,
) -> AssignedValue<Fr> {
    let mut hasher = PoseidonHasher::new(interior_spec());
    hasher.initialize_consts(ctx, range.gate());
    hasher.hash_fix_len_array(ctx, range.gate(), &[a, b])
}
