//! Axiom-stack Poseidon hash gadget (`halo2-base`) — Phase 1 of the axiom
//! backend migration (see `docs/axiom-backend-migration.md`).
//!
//! This is the audited-library replacement for the hand-rolled PSE
//! `poseidon.rs`, intended for the future axiom-backend circuit (Phase 3). It
//! coexists with `poseidon.rs` until the whole circuit is rewritten onto the
//! axiom `Context` eDSL — the two stacks use *different* `Fr` types
//! (`halo2curves-axiom` vs PSE `halo2curves`) and cannot be mixed within one
//! circuit.
//!
//! # Permutation parameters — Circom / light-poseidon compatible
//!
//! The permutation (MDS matrix + round constants, generated by the standard
//! Grain-LFSR algorithm via `OptimizedPoseidonSpec`) is identical to
//! `light-poseidon` v0.4's `new_circom(...)` on BN254:
//!
//! | Variant   | t  | RATE | R_F | R_P | Inputs | Usage                          |
//! |-----------|----|------|-----|-----|--------|--------------------------------|
//! | Leaf      | 2  | 1    | 8   | 56  | 1      | `poseidon(address)`            |
//! | Interior  | 3  | 2    | 8   | 57  | 2      | `poseidon(left, right)` / null |
//!
//! Parameter equivalence is proven in `tests/poseidon_axiom.rs` (the spec's raw
//! permutation reproduces `light-poseidon::Poseidon::hash` byte-for-byte).
//!
//! # Sponge convention — Phase 3 reconciliation required
//!
//! The PERMUTATIONS match, but the HASH functions differ by construction:
//!
//! | Aspect            | halo2-base (this gadget) | light-poseidon / Circom (`zkmist-merkle-tree`) |
//! |-------------------|--------------------------|------------------------------------------------|
//! | Capacity element  | `2^64`                   | `0`                                            |
//! | Input padding     | `1` then `0`s            | none for a full RATE block                     |
//! | Squeeze           | extra empty permutation when absorbed length ≡ 0 (mod RATE) | single permutation |
//! | Digest output     | `state[1]`               | `state[0]`                                     |
//!
//! The off-chain Merkle tree (`zkmist-merkle-tree`) and the existing PSE
//! circuit commit to the light-poseidon convention. Phase 3 must reconcile
//! this so the circuit verifies the *same* tree that is committed on-chain:
//! either (a) rebuild the off-chain tree / nullifier under halo2-base's
//! convention (audited, standard), or (b) wrap this chip to replicate the
//! Circom convention. This decision does not affect Phase 1 — the chip and its
//! parameters are correct either way (verified below).

use halo2_base::{
    gates::RangeInstructions,
    halo2_proofs::halo2curves::bn256::Fr,
    poseidon::hasher::{spec::OptimizedPoseidonSpec, PoseidonHasher},
    AssignedValue, Context,
};
use ff::{Field, PrimeField};
use poseidon_primitives::poseidon::primitives::Spec;
use std::marker::PhantomData;

// ── Native reference (halo2-base sponge convention) ──────────────────────
//
// A native (non-circuit) Poseidon under halo2-base's sponge convention
// (capacity 2^64, squeeze permutation, output state[1]), using the same raw
// Grain-LFSR permutation as the in-circuit chip. Used to generate expected
// digests for the Merkle / nullifier gadgets and their tests. See
// `tests/poseidon_axiom.rs` for the proof that this permutation matches
// light-poseidon byte-for-byte.

#[derive(Debug)]
struct Pow5Gen<
    const T: usize,
    const RATE: usize,
    const R_F: usize,
    const R_P: usize,
    const SECURE_MDS: usize,
>(PhantomData<Fr>);

impl<const T: usize, const RATE: usize, const R_F: usize, const R_P: usize, const SECURE_MDS: usize>
    Spec<Fr, T, RATE> for Pow5Gen<T, RATE, R_F, R_P, SECURE_MDS>
{
    fn full_rounds() -> usize {
        R_F
    }
    fn partial_rounds() -> usize {
        R_P
    }
    fn sbox(val: Fr) -> Fr {
        val.pow([5u64])
    }
    fn secure_mds() -> usize {
        SECURE_MDS
    }
}

/// Standard (non-optimized) Poseidon permutation on `T`-element state, using
/// raw Grain-LFSR round constants + dense MDS. Mirrors the reference in
/// `poseidon-primitives`.
fn native_permute(state: &mut [Fr], mds: &[Vec<Fr>], rc: &[Vec<Fr>], r_f: usize, r_p: usize) {
    let t = state.len();
    let half = r_f / 2;
    let apply_mds = |state: &mut [Fr]| {
        let mut ns = vec![Fr::zero(); t];
        for i in 0..t {
            for j in 0..t {
                ns[i] += mds[i][j] * state[j];
            }
        }
        state.copy_from_slice(&ns);
    };
    let mut round = 0usize;
    for _ in 0..half {
        for i in 0..t {
            state[i] = (state[i] + rc[round][i]).pow([5u64]);
        }
        apply_mds(state);
        round += 1;
    }
    for _ in 0..r_p {
        for i in 0..t {
            state[i] += rc[round][i];
        }
        state[0] = state[0].pow([5u64]);
        apply_mds(state);
        round += 1;
    }
    for _ in 0..half {
        for i in 0..t {
            state[i] = (state[i] + rc[round][i]).pow([5u64]);
        }
        apply_mds(state);
        round += 1;
    }
}

/// Native Poseidon hash under halo2-base's sponge convention, matching the
/// in-circuit [`hash_leaf`] / [`hash_interior`]. `inputs.len()` must equal
/// `RATE` (the only arity ZKMist uses: 1 for leaf, 2 for interior/nullifier).
pub fn native_poseidon<
    const T: usize,
    const RATE: usize,
    const R_F: usize,
    const R_P: usize,
>(
    inputs: &[Fr],
) -> Fr {
    assert_eq!(inputs.len(), RATE);
    let (rc_arr, mds_arr, _mds_inv) =
        <Pow5Gen<T, RATE, R_F, R_P, 0> as Spec<Fr, T, RATE>>::constants();
    let rc: Vec<Vec<Fr>> = rc_arr.iter().map(|r| r.to_vec()).collect();
    let mds: Vec<Vec<Fr>> = mds_arr.iter().map(|r| r.to_vec()).collect();
    let mut state = vec![Fr::zero(); T];
    state[0] = Fr::from_u128(1u128 << 64); // halo2-base capacity
    for (j, inp) in inputs.iter().enumerate() {
        state[1 + j] += inp;
    }
    native_permute(&mut state, &mds, &rc, R_F, R_P);
    // halo2-base squeezes an extra empty permutation when len % RATE == 0.
    state[1] += Fr::one();
    native_permute(&mut state, &mds, &rc, R_F, R_P);
    state[1]
}

/// Native leaf hash `poseidon(x)` (halo2-base convention): t=2.
pub fn native_hash_leaf(x: Fr) -> Fr {
    native_poseidon::<2, 1, 8, 56>(&[x])
}

/// Native interior hash `poseidon(a, b)` (halo2-base convention): t=3.
pub fn native_hash_interior(a: Fr, b: Fr) -> Fr {
    native_poseidon::<3, 2, 8, 57>(&[a, b])
}

/// Build the leaf-hash spec: t=2, RATE=1, R_F=8, R_P=56 (`light-poseidon`
/// `new_circom(1)` equivalent). One permutation input.
pub fn leaf_spec() -> OptimizedPoseidonSpec<Fr, 2, 1> {
    OptimizedPoseidonSpec::<Fr, 2, 1>::new::<8, 56, 0>()
}

/// Build the interior-hash spec: t=3, RATE=2, R_F=8, R_P=57 (`light-poseidon`
/// `new_circom(2)` equivalent). Two permutation inputs (Merkle interior nodes
/// and the nullifier).
pub fn interior_spec() -> OptimizedPoseidonSpec<Fr, 3, 2> {
    OptimizedPoseidonSpec::<Fr, 3, 2>::new::<8, 57, 0>()
}

/// Hash a single field element with the leaf hasher: `poseidon(x)` (t=2).
///
/// Uses halo2-base's sponge convention (see the module docs). Returns the
/// assigned digest.
pub fn hash_leaf(
    ctx: &mut Context<Fr>,
    range: &impl RangeInstructions<Fr>,
    x: AssignedValue<Fr>,
) -> AssignedValue<Fr> {
    let mut hasher = PoseidonHasher::new(leaf_spec());
    hasher.initialize_consts(ctx, range.gate());
    hasher.hash_fix_len_array(ctx, range.gate(), &[x])
}

/// Hash two field elements with the interior hasher: `poseidon(a, b)` (t=3).
///
/// Used for Merkle interior nodes (`poseidon(left, right)`) and the nullifier
/// (`poseidon(key, domain)`). Uses halo2-base's sponge convention.
pub fn hash_interior(
    ctx: &mut Context<Fr>,
    range: &impl RangeInstructions<Fr>,
    a: AssignedValue<Fr>,
    b: AssignedValue<Fr>,
) -> AssignedValue<Fr> {
    let mut hasher = PoseidonHasher::new(interior_spec());
    hasher.initialize_consts(ctx, range.gate());
    hasher.hash_fix_len_array(ctx, range.gate(), &[a, b])
}
