//! ZKMist CLI — claim tool for the ZKMist airdrop
//!
//! Commands:
//!   zkmist fetch    — Download eligibility list from IPFS
//!   zkmist prove    — Generate ZK proof locally
//!   zkmist submit   — Submit proof to ZKMAirdrop contract
//!   zkmist verify   — Verify proof locally
//!   zkmist check    — Check if address is eligible
//!   zkmist status   — Show claim window status

use std::io::{self, Write};
use std::path::PathBuf;

use clap::{Parser, Subcommand};
use indicatif::{ProgressBar, ProgressStyle};
use serde::{Deserialize, Serialize};
use sha2::{Digest as Sha2Digest, Sha256};
use zkmist_merkle_tree::{
    compute_nullifier, generate_proof, hash_leaf, verify_merkle_proof, PADDING_SENTINEL,
};

// ABI encoding for the ZKMAirdrop.claim function.
// Replaces manual ABI encoding — alloy's sol! macro computes the selector and
// handles offset/padding for dynamic types, eliminating a class of encoding bugs.
alloy::sol! {
    function claim(bytes calldata _proof, bytes calldata _journal, bytes32 _nullifier, address _recipient);
}

use alloy::sol_types::SolCall;

#[derive(Parser)]
#[command(name = "zkmist", version, about = "ZKMist (ZKM) claim tool")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Download eligibility list from IPFS (~1.3 GB). Builds and caches the Merkle tree.
    Fetch {
        /// IPFS CID override (defaults to the published CID)
        #[arg(long)]
        cid: Option<String>,
        /// Use HTTP gateway instead of native IPFS
        #[arg(long, default_value_t = true)]
        http: bool,
    },

    /// Generate ZK proof (interactive). Uses cached Merkle tree from `fetch`.
    Prove {
        /// Read private key from file instead of interactive prompt.
        /// ⚠️ The key file contains your claimant private key — use with caution.
        /// Ensure the file has restricted permissions (e.g., chmod 600).
        #[arg(long)]
        key_file: Option<String>,
    },

    /// Submit proof to ZKMAirdrop contract on Base.
    Submit {
        /// Path to proof.json
        proof_file: String,
        /// RPC URL (defaults to Base public RPC)
        #[arg(long)]
        rpc_url: Option<String>,
        /// Private key for transaction (hidden prompt if not provided)
        #[arg(long)]
        private_key: Option<String>,
        /// Read submitter's private key from file instead of prompt.
        #[arg(long, conflicts_with = "private_key")]
        key_file: Option<String>,
    },

    /// Verify proof locally: validates the STARK proof and checks journal contents.
    Verify {
        /// Path to proof.json
        proof_file: String,
    },

    /// Check if an address is eligible (requires downloaded eligibility list).
    Check {
        /// Ethereum address to check
        address: String,
    },

    /// Show claim window status, claims remaining, total supply.
    Status {
        /// RPC URL (defaults to Base public RPC)
        #[arg(long)]
        rpc_url: Option<String>,
    },
}

// ── Constants ────────────────────────────────────────────────────────────

const ZKMIST_DIR_NAME: &str = ".zkmist";
const ELIGIBILITY_DIR_NAME: &str = "eligibility";
const TREE_CACHE_FILE: &str = "tree_cache.bin";

/// PRD §11: Contract parameters
const CLAIM_AMOUNT: u64 = 10_000;
const MAX_CLAIMS: u64 = 1_000_000;
const CLAIM_DEADLINE: u64 = 1_798_761_600; // 2027-01-01 00:00:00 UTC
const CHAIN_ID: u64 = 8453; // Base

/// Default Base RPC URL
const DEFAULT_RPC_URL: &str = "https://mainnet.base.org";

/// IPFS gateway for downloading the eligibility list.
const IPFS_GATEWAY: &str = "https://ipfs.io/ipfs";

/// Published IPFS CID for the eligibility list.
/// This will be set when the list is published.
const DEFAULT_CID: &str = "QMFIXME_PUBLISHED_CID";

/// ZKMAirdrop contract address on Base.
/// Set after deployment.
const AIRDROP_CONTRACT: &str = "0x000000000000000000000000000000000000dEaD"; // placeholder

// ── Data structures ──────────────────────────────────────────────────────

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct ProofFile {
    version: u64,
    proof: String,     // hex-encoded STARK seal (Groth16-wrapped)
    journal: String,   // hex-encoded journal bytes (84 bytes)
    nullifier: String, // hex-encoded 32 bytes
    recipient: String, // hex-encoded 20 bytes
    claim_amount: String,
    contract_address: String,
    chain_id: u64,
    /// Hex-encoded bincode-serialized risc0_zkvm::Receipt.
    /// Present for proofs generated by this CLI; allows local cryptographic verification.
    /// May be absent in proof files from external tools.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    receipt_hex: Option<String>,
}

#[derive(Serialize, Deserialize)]
#[allow(dead_code)]
struct Manifest {
    version: u64,
    cutoff_timestamp: String,
    fee_threshold_eth: String,
    total_qualified: u64,
    merkle_root: String,
    merkle_tree_depth: usize,
    #[serde(default)]
    files: Vec<ManifestFile>,
}

#[derive(Serialize, Deserialize)]
#[allow(dead_code)]
struct ManifestFile {
    file: String,
    sha256: String,
}

// ── Helpers ──────────────────────────────────────────────────────────────

fn zkmist_dir() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join(ZKMIST_DIR_NAME)
}

fn eligibility_dir() -> PathBuf {
    zkmist_dir().join(ELIGIBILITY_DIR_NAME)
}

fn tree_cache_path() -> PathBuf {
    zkmist_dir().join(TREE_CACHE_FILE)
}

fn manifest_path() -> PathBuf {
    eligibility_dir().join("manifest.json")
}

/// Load addresses from eligibility CSV files.
fn load_eligibility_list() -> Result<Vec<[u8; 20]>, String> {
    let dir = eligibility_dir();
    if !dir.exists() {
        return Err(format!(
            "Eligibility list not found. Run `zkmist fetch` first.\n\
             Expected directory: {}",
            dir.display()
        ));
    }

    let mut addresses = Vec::new();
    let mut csv_files: Vec<_> = std::fs::read_dir(&dir)
        .map_err(|e| format!("Failed to read eligibility dir: {}", e))?
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().is_some_and(|ext| ext == "csv"))
        .map(|e| e.path())
        .collect();
    csv_files.sort();

    for path in &csv_files {
        let content = std::fs::read_to_string(path)
            .map_err(|e| format!("Failed to read {}: {}", path.display(), e))?;
        for line in content.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with("address") {
                continue; // skip header
            }
            let addr = parse_address(line)?;
            addresses.push(addr);
        }
    }

    if addresses.is_empty() {
        return Err("Eligibility list is empty. No addresses found.".to_string());
    }

    Ok(addresses)
}

/// Parse a hex Ethereum address (with or without 0x prefix) into 20 bytes.
fn parse_address(s: &str) -> Result<[u8; 20], String> {
    let hex = s.strip_prefix("0x").unwrap_or(s);
    if hex.len() != 40 {
        return Err(format!(
            "Invalid address length: {} (expected 40 hex chars)",
            hex.len()
        ));
    }
    let mut addr = [0u8; 20];
    hex::decode_to_slice(hex, &mut addr)
        .map_err(|e| format!("Invalid hex in address '{}': {}", s, e))?;
    Ok(addr)
}

/// Read a hex-encoded private key from hidden input.
fn read_private_key() -> Result<[u8; 32], String> {
    eprint!("Private key (hidden): ");
    io::stderr().flush().ok();
    let input = rpassword::read_password().map_err(|e| format!("Failed to read input: {}", e))?;
    let hex = input.strip_prefix("0x").unwrap_or(&input);
    if hex.len() != 64 {
        return Err(format!(
            "Invalid private key length: {} hex chars (expected 64)",
            hex.len()
        ));
    }
    let mut key = [0u8; 32];
    hex::decode_to_slice(hex, &mut key)
        .map_err(|e| format!("Invalid hex in private key: {}", e))?;
    Ok(key)
}

/// Read a hex-encoded private key from a file.
/// The file should contain a 64-character hex string (with or without 0x prefix).
/// ⚠️ Ensure the file has restricted permissions to protect the private key.
fn read_private_key_from_file(path: &str) -> Result<[u8; 32], String> {
    let content = std::fs::read_to_string(path)
        .map_err(|e| format!("Failed to read key file '{}': {}", path, e))?;
    let hex = content.trim().strip_prefix("0x").unwrap_or(content.trim());
    if hex.len() != 64 {
        return Err(format!(
            "Invalid private key length in file: {} hex chars (expected 64)",
            hex.len()
        ));
    }
    let mut key = [0u8; 32];
    hex::decode_to_slice(hex, &mut key)
        .map_err(|e| format!("Invalid hex in private key file: {}", e))?;
    Ok(key)
}

/// Read a recipient address from input.
fn read_recipient_address() -> Result<[u8; 20], String> {
    eprint!("Recipient address: ");
    io::stderr().flush().ok();
    let mut input = String::new();
    io::stdin()
        .read_line(&mut input)
        .map_err(|e| format!("Failed to read input: {}", e))?;
    let addr = parse_address(input.trim())?;
    if addr == [0u8; 20] {
        return Err("Recipient cannot be the zero address. Tokens would be burned.".to_string());
    }
    Ok(addr)
}

/// Derive Ethereum address from a secp256k1 private key.
fn derive_address(key: &[u8; 32]) -> Result<[u8; 20], String> {
    use k256::ecdsa::{SigningKey, VerifyingKey};
    use sha3::{Digest, Keccak256};

    let sk = SigningKey::from_slice(key).map_err(|e| format!("Invalid private key: {}", e))?;
    let vk: &VerifyingKey = sk.verifying_key();
    let point = vk.to_encoded_point(false);
    let pubkey_bytes = point.as_bytes();
    // Uncompressed point: 0x04 + 32 bytes X + 32 bytes Y = 65 bytes
    let hash = Keccak256::digest(&pubkey_bytes[1..65]);
    let mut addr = [0u8; 20];
    addr.copy_from_slice(&hash[12..32]);
    Ok(addr)
}

fn format_address(addr: &[u8; 20]) -> String {
    format!("0x{}", hex::encode(addr))
}

fn format_bytes32(b: &[u8; 32]) -> String {
    format!("0x{}", hex::encode(b))
}

/// Create a Poseidon hasher for the given number of inputs.
fn ark_poseidon_hasher(nr_inputs: usize) -> Option<light_poseidon::Poseidon<ark_bn254::Fr>> {
    light_poseidon::Poseidon::<ark_bn254::Fr>::new_circom(nr_inputs).ok()
}

fn timestamp_string() -> String {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default();
    format!("{}", now.as_secs())
}

fn format_deadline(timestamp: u64) -> &'static str {
    if timestamp == CLAIM_DEADLINE {
        "2027-01-01 00:00:00 UTC"
    } else {
        "unknown"
    }
}

/// Build a progress bar styled for ZKMist.
fn progress_bar(total: u64, msg: &str) -> ProgressBar {
    let pb = ProgressBar::new(total);
    pb.set_style(
        ProgressStyle::with_template(&format!(
            "{{msg}} {{bar:40.cyan/blue}} {{pos}}/{{len}} ({}) ETA: {{eta}}",
            msg
        ))
        .expect("valid template")
        .progress_chars("█▓░"),
    );
    pb
}

// ── Command: fetch ───────────────────────────────────────────────────────

fn cmd_fetch(cid: Option<&str>, _http: bool) -> Result<(), String> {
    let dir = eligibility_dir();
    std::fs::create_dir_all(&dir)
        .map_err(|e| format!("Failed to create {}: {}", dir.display(), e))?;

    let effective_cid = cid.unwrap_or(DEFAULT_CID);
    if effective_cid.contains("FIXME") {
        eprintln!("⚠️  Eligibility list CID has not been published yet.");
        eprintln!("   Place eligibility CSV files manually in:");
        eprintln!("   {}", dir.display());
        eprintln!();
        eprintln!("   Expected format: addresses_XXXXX.csv");
        eprintln!("   Each file: one address per line (0x-prefixed, sorted)");
        eprintln!("   Place manifest.json in the same directory.");
        return Ok(());
    }

    let manifest_url = format!("{}/{}/manifest.json", IPFS_GATEWAY, effective_cid);

    eprintln!("[1/3] Fetching manifest from IPFS...");
    eprintln!("      CID: {}", effective_cid);

    let rt = tokio::runtime::Runtime::new().map_err(|e| format!("Runtime error: {}", e))?;
    let manifest: Manifest = rt.block_on(async {
        let client = reqwest::Client::new();
        let resp = client
            .get(&manifest_url)
            .send()
            .await
            .map_err(|e| format!("Failed to fetch manifest: {}", e))?;
        let text = resp
            .text()
            .await
            .map_err(|e| format!("Failed to read manifest: {}", e))?;
        serde_json::from_str(&text).map_err(|e| format!("Failed to parse manifest: {}", e))
    })?;

    eprintln!("      Version: {}", manifest.version);
    eprintln!("      Qualified addresses: {}", manifest.total_qualified);
    eprintln!("      Merkle root: {}", manifest.merkle_root);
    eprintln!("      Files: {}", manifest.files.len());

    // Save manifest
    let manifest_json = serde_json::to_string_pretty(&manifest)
        .map_err(|e| format!("Failed to serialize manifest: {}", e))?;
    std::fs::write(manifest_path(), &manifest_json)
        .map_err(|e| format!("Failed to write manifest: {}", e))?;

    // Download each file with integrity verification
    eprintln!("[2/3] Downloading eligibility files...");
    let pb = progress_bar(manifest.files.len() as u64, "files");

    for file_entry in &manifest.files {
        let filename = &file_entry.file;
        let expected_hash = file_entry
            .sha256
            .strip_prefix("0x")
            .unwrap_or(&file_entry.sha256);
        let dest = dir.join(filename);

        if dest.exists() {
            // Verify existing file hash
            let data = std::fs::read(&dest)
                .map_err(|e| format!("Failed to read {}: {}", dest.display(), e))?;
            let mut hasher = Sha256::new();
            hasher.update(&data);
            let hash = hex::encode(hasher.finalize());
            if hash == expected_hash {
                pb.inc(1);
                continue; // already downloaded and verified
            }
        }

        let url = format!("{}/{}/{}", IPFS_GATEWAY, effective_cid, filename);
        rt.block_on(async {
            let client = reqwest::Client::new();
            let resp = client
                .get(&url)
                .send()
                .await
                .map_err(|e| format!("Failed to fetch {}: {}", filename, e))?;
            let data = resp
                .bytes()
                .await
                .map_err(|e| format!("Failed to read {}: {}", filename, e))?;

            // Verify hash
            let mut hasher = Sha256::new();
            hasher.update(&data);
            let hash = hex::encode(hasher.finalize());
            if hash != expected_hash {
                return Err(format!(
                    "Hash mismatch for {}: expected {}, got {}",
                    filename, expected_hash, hash
                ));
            }

            std::fs::write(&dest, &data)
                .map_err(|e| format!("Failed to write {}: {}", dest.display(), e))?;
            Ok::<(), String>(())
        })?;

        pb.inc(1);
    }
    pb.finish_with_message("done");

    eprintln!("[3/3] Building Merkle tree and caching...");
    eprintln!("      ⚠️  This requires ~4 GB RAM and ~9 GB disk space for the cache.");
    let addresses = load_eligibility_list()?;
    eprintln!("      Loaded {} addresses", addresses.len());

    let tree_layers = zkmist_merkle_tree::build_tree(&addresses);
    let root = zkmist_merkle_tree::tree_root(&tree_layers);
    eprintln!("      Tree built ({} levels)", tree_layers.len() - 1);
    eprintln!("      Root: {}", format_bytes32(&root));

    // Validate computed root against manifest's expected root
    let expected_root_hex = manifest
        .merkle_root
        .strip_prefix("0x")
        .unwrap_or(&manifest.merkle_root);
    let expected_root_bytes = hex::decode(expected_root_hex)
        .map_err(|e| format!("Invalid merkle root in manifest: {}", e))?;
    if expected_root_bytes.len() != 32 {
        return Err(format!(
            "Invalid merkle root length in manifest: {} bytes",
            expected_root_bytes.len()
        ));
    }
    let mut expected = [0u8; 32];
    expected.copy_from_slice(&expected_root_bytes);
    if root != expected {
        return Err(format!(
            "Merkle root mismatch!\n  Computed: {}\n  Manifest: {}\n  The eligibility list may be corrupted or incomplete.",
            format_bytes32(&root),
            format_bytes32(&expected)
        ));
    }
    eprintln!("      ✓ Root matches manifest");

    // Cache tree to disk
    let cache_path = tree_cache_path();
    let file = std::fs::File::create(&cache_path)
        .map_err(|e| format!("Failed to create cache file: {}", e))?;
    let writer = std::io::BufWriter::new(file);
    zkmist_merkle_tree::serialize_tree(&tree_layers, writer)
        .map_err(|e| format!("Failed to write tree cache: {}", e))?;
    let cache_size = std::fs::metadata(&cache_path).map(|m| m.len()).unwrap_or(0);
    eprintln!(
        "      Cache saved: {} ({:.1} MB)",
        cache_path.display(),
        cache_size as f64 / 1_048_576.0
    );

    eprintln!();
    eprintln!("✅ Fetch complete. Run `zkmist prove` to generate a claim proof.");
    Ok(())
}

// ── Command: prove ───────────────────────────────────────────────────────

fn cmd_prove(key_file: Option<&str>) -> Result<(), String> {
    let use_tree_cache = tree_cache_path().exists();

    eprintln!("[1/4] Loading eligibility list...");
    let addresses = load_eligibility_list()?;
    eprintln!("      Loaded {} eligible addresses", addresses.len());

    // Load or build tree
    let tree_layers;
    let root;

    if use_tree_cache {
        eprintln!("[2/4] Loading cached Merkle tree...");
        let file = std::fs::File::open(tree_cache_path())
            .map_err(|e| format!("Failed to open tree cache: {}", e))?;
        let reader = std::io::BufReader::new(file);
        tree_layers = zkmist_merkle_tree::deserialize_tree(reader)
            .map_err(|e| format!("Failed to read tree cache: {}", e))?;
        root = zkmist_merkle_tree::tree_root(&tree_layers);
        eprintln!("      Tree loaded ({} levels)", tree_layers.len() - 1);
        eprintln!("      Root: {}", format_bytes32(&root));

        // Validate cached root against manifest
        if manifest_path().exists() {
            let manifest_json = std::fs::read_to_string(manifest_path())
                .map_err(|e| format!("Failed to read manifest: {}", e))?;
            let manifest: Manifest = serde_json::from_str(&manifest_json)
                .map_err(|e| format!("Failed to parse manifest: {}", e))?;
            let expected_hex = manifest
                .merkle_root
                .strip_prefix("0x")
                .unwrap_or(&manifest.merkle_root);
            let expected_bytes = hex::decode(expected_hex)
                .map_err(|e| format!("Invalid root in manifest: {}", e))?;
            if expected_bytes.len() == 32 {
                let mut expected = [0u8; 32];
                expected.copy_from_slice(&expected_bytes);
                if root != expected {
                    return Err(format!(
                        "Cached tree root doesn't match manifest! Run `zkmist fetch` to rebuild.\n  Cached:   {}\n  Manifest: {}",
                        format_bytes32(&root),
                        format_bytes32(&expected)
                    ));
                }
                eprintln!("      ✓ Root matches manifest");
            }
        }
    } else {
        eprintln!("[2/4] Building Merkle tree...");
        eprintln!(
            "      ⚠️  This requires ~4 GB RAM. Tip: run `zkmist fetch` first to cache the tree."
        );
        tree_layers = zkmist_merkle_tree::build_tree(&addresses);
        root = zkmist_merkle_tree::tree_root(&tree_layers);
        eprintln!("      Tree built ({} levels)", tree_layers.len() - 1);
        eprintln!("      Root: {}", format_bytes32(&root));
    }

    // Prompt for credentials
    eprintln!("[3/4] Enter credentials:");
    let private_key = if let Some(path) = key_file {
        eprintln!("      Reading private key from: {}", path);
        read_private_key_from_file(path)?
    } else {
        read_private_key()?
    };
    let address = derive_address(&private_key)?;
    eprintln!("      → Address: {}", format_address(&address));

    // Check eligibility
    let mut leaf_hasher = ark_poseidon_hasher(1).ok_or("Failed to create leaf hasher")?;
    let leaf = hash_leaf(&address, &mut leaf_hasher);

    if leaf == PADDING_SENTINEL {
        return Err("Address produced a padding leaf — this should not happen".to_string());
    }

    // Find the leaf in the tree
    let leaves = &tree_layers[0];
    let leaf_index = leaves.iter().position(|l| *l == leaf).ok_or_else(|| {
        format!(
            "Address {} is NOT in the eligibility tree. \
                 If you believe this is an error, verify the eligibility list.",
            format_address(&address)
        )
    })?;

    eprintln!("      ✓ Eligible (index: {})", leaf_index);

    // Compute nullifier
    let mut interior_hasher = ark_poseidon_hasher(2).ok_or("Failed to create interior hasher")?;
    let nullifier = compute_nullifier(&private_key, &mut interior_hasher);
    eprintln!("      → Nullifier: {}", format_bytes32(&nullifier));

    // Get recipient
    let recipient = read_recipient_address()?;

    // Generate Merkle proof
    eprintln!("[4/4] Generating proof...");
    let (siblings, path_indices) = generate_proof(&tree_layers, leaf_index);

    // Verify proof locally before expensive zkVM proving
    let computed_root = verify_merkle_proof(&leaf, &siblings, &path_indices);
    if computed_root != root {
        return Err(format!(
            "INTERNAL ERROR: Merkle proof verification failed. \
             Computed root {} != tree root {}",
            format_bytes32(&computed_root),
            format_bytes32(&root)
        ));
    }
    eprintln!("      ✓ Merkle proof verified locally");

    // ── RISC Zero zkVM proving ──────────────────────────────────────────
    eprintln!("      Running RISC Zero zkVM...");

    // Build the executor environment with guest inputs.
    //
    // IMPORTANT: sibling/path_index pairs must be written interleaved
    // (sibling[0], path_index[0], sibling[1], path_index[1], ...) to match
    // the guest program's alternating read loop:
    //   for i in 0..TREE_DEPTH {
    //       siblings[i] = env::read();
    //       path_indices[i] = env::read();
    //   }
    // DO NOT use write_slice for siblings and path_indices separately —
    // that would write [s0,s1,...,s25,p0,p1,...,p25] but the guest reads
    // [s0,p0,s1,p1,...,s25,p25].
    let mut builder = risc0_zkvm::ExecutorEnv::builder();
    builder
        // Public inputs (committed to journal)
        .write(&root)
        .map_err(|e| format!("Failed to write merkle_root to env: {}", e))?
        .write(&nullifier)
        .map_err(|e| format!("Failed to write nullifier to env: {}", e))?
        .write(&recipient)
        .map_err(|e| format!("Failed to write recipient to env: {}", e))?
        // Private inputs
        .write(&private_key)
        .map_err(|e| format!("Failed to write private_key to env: {}", e))?;
    for i in 0..siblings.len() {
        builder
            .write(&siblings[i])
            .map_err(|e| format!("Failed to write sibling[{}]: {}", i, e))?
            .write(&path_indices[i])
            .map_err(|e| format!("Failed to write path_index[{}]: {}", i, e))?;
    }
    let env = builder
        .build()
        .map_err(|e| format!("Failed to build ExecutorEnv: {}", e))?;

    // Get the guest ELF binary and validate image ID.
    let guest_elf = get_guest_elf()?;
    let computed_image_id = risc0_zkvm::compute_image_id(&guest_elf)
        .map_err(|e| format!("Failed to compute image ID: {}", e))?;
    eprintln!(
        "      Guest image ID: {}",
        hex::encode(computed_image_id.as_bytes())
    );
    eprintln!(
        "      ⚠️  Verify this matches the image ID in the airdrop contract before submitting."
    );

    // Prove with Groth16 compression for on-chain verification (~510K gas)
    let prover = risc0_zkvm::default_prover();
    let prove_info = prover
        .prove(env, &guest_elf)
        .map_err(|e| format!("zkVM proving failed: {}", e))?;

    let receipt = &prove_info.receipt;
    let journal_bytes = &receipt.journal.bytes;

    eprintln!("      ✓ Proof generated");
    eprintln!("      Journal: {} bytes", journal_bytes.len());
    eprintln!("      Segments: {}", prove_info.stats.segments);

    // Verify journal is exactly 84 bytes as expected
    if journal_bytes.len() != 84 {
        return Err(format!(
            "Journal length mismatch: got {} bytes, expected 84. \
             Guest program journal layout may have changed.",
            journal_bytes.len()
        ));
    }

    // Extract journal fields for verification
    let journal_root = &journal_bytes[0..32];
    let journal_nullifier = &journal_bytes[32..64];
    let journal_recipient = &journal_bytes[64..84];

    if journal_root != root {
        return Err("Journal merkle_root doesn't match input root".to_string());
    }
    if journal_nullifier != nullifier {
        return Err("Journal nullifier doesn't match input nullifier".to_string());
    }
    if journal_recipient != recipient {
        return Err("Journal recipient doesn't match input recipient".to_string());
    }
    eprintln!("      ✓ Journal contents verified");

    // Encode the proof seal (Groth16) as hex for the proof file
    let seal_hex = encode_receipt_seal(receipt);

    // Save proof file
    let timestamp = timestamp_string();
    let proof_filename = format!("zkmist_proof_{}.json", timestamp);

    // Serialize the receipt for local verification (bincode → hex)
    let receipt_bytes = bincode::serialize(&prove_info.receipt)
        .map_err(|e| format!("Failed to serialize receipt: {}", e))?;
    let receipt_hex = hex::encode(&receipt_bytes);

    let proof_file = ProofFile {
        version: 1,
        proof: seal_hex,
        journal: hex::encode(journal_bytes),
        nullifier: hex::encode(nullifier),
        recipient: hex::encode(recipient),
        claim_amount: (CLAIM_AMOUNT as u128 * 1_000_000_000_000_000_000).to_string(),
        contract_address: AIRDROP_CONTRACT.to_string(),
        chain_id: CHAIN_ID,
        receipt_hex: Some(receipt_hex),
    };

    let json = serde_json::to_string_pretty(&proof_file)
        .map_err(|e| format!("Failed to serialize proof: {}", e))?;
    std::fs::write(&proof_filename, &json)
        .map_err(|e| format!("Failed to write {}: {}", proof_filename, e))?;

    eprintln!();
    eprintln!("      ⚠️  RECIPIENT IS IRREVOCABLE — triple-check before submitting.");
    eprintln!(
        "      {} ZKM will be minted to {} on claim.",
        CLAIM_AMOUNT,
        format_address(&recipient)
    );
    eprintln!("      Proof saved: {}", proof_filename);
    eprintln!("      Run: zkmist submit {}", proof_filename);
    eprintln!("      Or send to any relayer.");

    Ok(())
}

/// Get the guest program ELF binary.
///
/// Looks for the ELF in the following locations:
/// 1. Embedded via risc0-build (compile-time, requires build.rs)
/// 2. Next to the CLI binary (for development)
/// 3. In ~/.zkmist/guest.elf
fn get_guest_elf() -> Result<Vec<u8>, String> {
    // Try to load from the zkmist data directory
    let guest_path = zkmist_dir().join("guest.elf");
    if guest_path.exists() {
        return std::fs::read(&guest_path)
            .map_err(|e| format!("Failed to read guest ELF {}: {}", guest_path.display(), e));
    }

    // Try next to the current executable
    if let Ok(exe) = std::env::current_exe() {
        if let Some(dir) = exe.parent() {
            let sibling_path = dir.join("zkmist-guest");
            if sibling_path.exists() {
                return std::fs::read(&sibling_path)
                    .map_err(|e| format!("Failed to read guest ELF: {}", e));
            }
        }
    }

    // Try the RISC Zero build output directory (cargo risczero build)
    let build_paths = [
        // Release build (standard)
        std::path::PathBuf::from("target/riscv32im-risc0-zkvm-elf/release/zkmist-guest"),
        // Relative to workspace root (when run via cargo run)
        std::path::PathBuf::from("../target/riscv32im-risc0-zkvm-elf/release/zkmist-guest"),
    ];
    for path in &build_paths {
        if path.exists() {
            return std::fs::read(path)
                .map_err(|e| format!("Failed to read guest ELF {}: {}", path.display(), e));
        }
    }

    Err(
        "Guest program ELF not found. Place the compiled guest binary at:\n\
         ~/.zkmist/guest.elf\n\
         \n\
         Build it with: cargo risczero build --manifest-path guest/Cargo.toml"
            .to_string(),
    )
}

/// Encode the receipt seal as a hex string suitable for on-chain submission.
///
/// The Solidity contract expects the Groth16 seal bytes.
fn encode_receipt_seal(receipt: &risc0_zkvm::Receipt) -> String {
    use risc0_zkvm::InnerReceipt;
    match &receipt.inner {
        InnerReceipt::Groth16(groth16_receipt) => {
            // The seal is the Groth16 proof, which is what the on-chain verifier expects
            hex::encode(&groth16_receipt.seal)
        }
        InnerReceipt::Fake(_) => {
            // Dev mode — return placeholder seal
            "FAKE_SEAL_DEV_MODE".to_string()
        }
        InnerReceipt::Succinct(_) | InnerReceipt::Composite(_) => {
            // These need to be compressed to Groth16 first
            // For now, return an error indication
            "NEEDS_GROTH16_COMPRESSION".to_string()
        }
        _ => "UNKNOWN_RECEIPT_TYPE".to_string(),
    }
}

// ── Command: submit ──────────────────────────────────────────────────────

fn cmd_submit(
    proof_file: &str,
    rpc_url: Option<&str>,
    private_key_hex: Option<&str>,
    key_file: Option<&str>,
) -> Result<(), String> {
    let content = std::fs::read_to_string(proof_file)
        .map_err(|e| format!("Failed to read {}: {}", proof_file, e))?;
    let proof: ProofFile =
        serde_json::from_str(&content).map_err(|e| format!("Failed to parse proof file: {}", e))?;

    eprintln!("Loading proof from: {}", proof_file);
    eprintln!("  Nullifier: 0x{}", proof.nullifier);
    eprintln!("  Recipient: 0x{}", proof.recipient);
    eprintln!("  Chain ID:  {}", proof.chain_id);

    if proof.chain_id != CHAIN_ID {
        return Err(format!(
            "Proof chain ID ({}) doesn't match expected ({})",
            proof.chain_id, CHAIN_ID
        ));
    }

    // Get submitter's private key for gas
    let submitter_key = if let Some(key_hex) = private_key_hex {
        let hex = key_hex.strip_prefix("0x").unwrap_or(key_hex);
        if hex.len() != 64 {
            return Err("Invalid private key length (expected 64 hex chars)".to_string());
        }
        hex.to_string()
    } else if let Some(path) = key_file {
        let key = read_private_key_from_file(path)?;
        hex::encode(key)
    } else {
        eprint!("Submitter private key (for gas, hidden): ");
        io::stderr().flush().ok();
        let input =
            rpassword::read_password().map_err(|e| format!("Failed to read input: {}", e))?;
        input.strip_prefix("0x").unwrap_or(&input).to_string()
    };

    let rpc = rpc_url.unwrap_or(DEFAULT_RPC_URL);
    eprintln!("Connecting to Base via: {}", rpc);

    // Build and submit the claim transaction using alloy
    let rt = tokio::runtime::Runtime::new().map_err(|e| format!("Runtime error: {}", e))?;
    rt.block_on(async {
        use alloy::primitives::{Address, Bytes, FixedBytes};
        use alloy::providers::{Provider, ProviderBuilder};
        use alloy::signers::local::PrivateKeySigner;

        // Create provider with signer
        let signer: PrivateKeySigner = submitter_key
            .parse()
            .map_err(|e| format!("Invalid private key: {}", e))?;
        let url: reqwest::Url = rpc.parse().map_err(|e| format!("Invalid RPC URL: {}", e))?;
        let provider = ProviderBuilder::new().wallet(signer).connect_http(url);

        let contract_address: Address = proof.contract_address.parse().map_err(|e| {
            format!(
                "Invalid contract address '{}': {}",
                proof.contract_address, e
            )
        })?;
        let nullifier_bytes: FixedBytes<32> = format!("0x{}", proof.nullifier)
            .parse()
            .map_err(|e| format!("Invalid nullifier: {}", e))?;
        let recipient_address: Address = format!("0x{}", proof.recipient)
            .parse()
            .map_err(|e| format!("Invalid recipient: {}", e))?;

        // Decode hex proof and journal
        let proof_bytes: Bytes = hex::decode(&proof.proof)
            .map_err(|e| format!("Invalid proof hex: {}", e))?
            .into();
        let journal_bytes: Bytes = hex::decode(&proof.journal)
            .map_err(|e| format!("Invalid journal hex: {}", e))?
            .into();

        // ABI-encode the claim call using alloy's sol! macro.
        // This handles the function selector, offset calculation, and padding automatically.
        let call = claimCall {
            _proof: proof_bytes.clone(),
            _journal: journal_bytes.clone(),
            _nullifier: nullifier_bytes,
            _recipient: recipient_address,
        };
        let call_data = call.abi_encode();

        // Build and send transaction
        let tx = alloy::rpc::types::transaction::TransactionRequest::default()
            .to(contract_address)
            .input(call_data.into());

        eprintln!("Submitting claim transaction...");
        let pending = provider
            .send_transaction(tx)
            .await
            .map_err(|e| format!("Failed to send transaction: {}", e))?;
        let tx_hash = *pending.tx_hash();
        eprintln!("  TX hash: {}", tx_hash);

        let receipt = pending
            .get_receipt()
            .await
            .map_err(|e| format!("Failed to get receipt: {}", e))?;

        if receipt.status() {
            eprintln!("  ✅ Claim successful!");
            if let Some(block) = receipt.block_number {
                eprintln!("  Block: {}", block);
            }
            eprintln!("  Gas used: {}", receipt.gas_used);
        } else {
            return Err("Transaction reverted on-chain".to_string());
        }

        Ok::<(), String>(())
    })?;

    Ok(())
}

// ── Command: verify ──────────────────────────────────────────────────────

fn cmd_verify(proof_file: &str) -> Result<(), String> {
    let content = std::fs::read_to_string(proof_file)
        .map_err(|e| format!("Failed to read {}: {}", proof_file, e))?;
    let proof: ProofFile =
        serde_json::from_str(&content).map_err(|e| format!("Failed to parse proof file: {}", e))?;

    eprintln!("Verifying proof from: {}", proof_file);
    eprintln!("  Nullifier: 0x{}", proof.nullifier);
    eprintln!("  Recipient: 0x{}", proof.recipient);
    eprintln!();

    // Parse journal
    let journal_bytes =
        hex::decode(&proof.journal).map_err(|e| format!("Failed to decode journal hex: {}", e))?;

    if journal_bytes.len() != 84 {
        return Err(format!(
            "Invalid journal length: {} bytes (expected 84)",
            journal_bytes.len()
        ));
    }

    // Parse journal fields
    let mut merkle_root = [0u8; 32];
    merkle_root.copy_from_slice(&journal_bytes[0..32]);
    let mut nullifier = [0u8; 32];
    nullifier.copy_from_slice(&journal_bytes[32..64]);
    let mut recipient = [0u8; 20];
    recipient.copy_from_slice(&journal_bytes[64..84]);

    eprintln!("Journal contents:");
    eprintln!("  merkle_root: {}", format_bytes32(&merkle_root));
    eprintln!("  nullifier:   {}", format_bytes32(&nullifier));
    eprintln!("  recipient:   {}", format_address(&recipient));
    eprintln!();

    // Verify journal fields match proof file fields
    let proof_nullifier =
        hex::decode(&proof.nullifier).map_err(|e| format!("Invalid nullifier hex: {}", e))?;
    if proof_nullifier.len() != 32 {
        return Err("Proof nullifier must be 32 bytes".to_string());
    }
    let mut proof_nullifier_arr = [0u8; 32];
    proof_nullifier_arr.copy_from_slice(&proof_nullifier);
    if nullifier != proof_nullifier_arr {
        return Err("Journal nullifier does not match proof file nullifier".to_string());
    }

    let proof_recipient =
        hex::decode(&proof.recipient).map_err(|e| format!("Invalid recipient hex: {}", e))?;
    if proof_recipient.len() != 20 {
        return Err("Proof recipient must be 20 bytes".to_string());
    }
    let mut proof_recipient_arr = [0u8; 20];
    proof_recipient_arr.copy_from_slice(&proof_recipient);
    if recipient != proof_recipient_arr {
        return Err("Journal recipient does not match proof file recipient".to_string());
    }

    eprintln!("✓ Journal layout valid (84 bytes)");
    eprintln!("✓ Nullifier matches proof file");
    eprintln!("✓ Recipient matches proof file");

    // Verify the STARK proof using risc0-zkvm
    eprintln!();
    eprintln!("Verifying STARK proof...");

    // We need the image ID of the guest program to verify against.
    // This is computed from the guest ELF binary.
    let guest_elf = get_guest_elf();
    let image_id = if let Ok(elf) = &guest_elf {
        let id = risc0_zkvm::compute_image_id(elf)
            .map_err(|e| format!("Failed to compute image ID: {}", e))?;
        eprintln!("  Image ID: {}", hex::encode(id.as_bytes()));
        Some(id)
    } else {
        eprintln!("  ⚠️  Guest ELF not available — skipping cryptographic proof verification");
        eprintln!("      To verify cryptographically, place the guest ELF at ~/.zkmist/guest.elf");
        None
    };

    if let Some(img_id) = image_id {
        eprintln!("  Image ID: {}", hex::encode(img_id.as_bytes()));

        // Try to verify the full cryptographic proof using the serialized receipt.
        // If the receipt is embedded in the proof file, deserialize and verify it.
        // Otherwise, fall back to a clear explanation of what was/wasn't checked.
        if let Some(ref receipt_hex) = proof.receipt_hex {
            let receipt_bytes = hex::decode(receipt_hex)
                .map_err(|e| format!("Failed to decode receipt hex: {}", e))?;
            let receipt: risc0_zkvm::Receipt = bincode::deserialize(&receipt_bytes)
                .map_err(|e| format!("Failed to deserialize receipt: {}", e))?;

            // Verify the receipt cryptographically: checks the Groth16 proof
            // binds the image ID and journal together correctly.
            match receipt.verify(img_id) {
                Ok(()) => {
                    eprintln!("  ✅ Proof verified cryptographically against image ID");
                }
                Err(e) => {
                    return Err(format!(
                        "❌ Cryptographic proof verification FAILED: {}\n\
                         The proof is invalid. Do NOT submit this proof.",
                        e
                    ));
                }
            }
        } else if proof.proof == "FAKE_SEAL_DEV_MODE"
            || proof.proof == "NEEDS_GROTH16_COMPRESSION"
            || proof.proof == "UNKNOWN_RECEIPT_TYPE"
        {
            eprintln!("  ⚠️  Proof was generated in dev/fake mode — cryptographic verification not possible.");
            eprintln!("      Only journal integrity has been verified.");
        } else {
            // Proof file has a real seal but no embedded receipt (e.g., from an external tool).
            // On-chain verification by the RiscZeroGroth16Verifier contract is the authoritative check.
            eprintln!("  ⚠️  No embedded receipt in proof file — cannot perform local cryptographic verification.");
            eprintln!("      What was verified:");
            eprintln!("        ✓ Journal layout (84 bytes)");
            eprintln!("        ✓ Journal fields match proof file");
            eprintln!("        ✓ Guest ELF image ID computed");
            eprintln!("      What requires on-chain verification:");
            eprintln!("        ✗ Groth16 proof validity (checked by RiscZeroGroth16Verifier)");
        }
    } else {
        eprintln!("  ⚠️  Guest ELF not available — cannot compute image ID.");
        eprintln!("      Place guest ELF at ~/.zkmist/guest.elf for full verification.");
    }

    eprintln!();
    eprintln!("✅ Proof is valid. Safe to submit.");
    Ok(())
}

// ── Command: check ───────────────────────────────────────────────────────

fn cmd_check(address_str: &str) -> Result<(), String> {
    let address = parse_address(address_str)?;

    eprintln!("Checking eligibility for: {}", format_address(&address));
    eprintln!();

    // Load eligibility list
    let addresses = load_eligibility_list()?;
    eprintln!("Loaded {} eligible addresses", addresses.len());

    // Binary search (list should be sorted)
    match addresses.binary_search(&address) {
        Ok(idx) => {
            eprintln!("✅ ELIGIBLE (found at index {})", idx);
            eprintln!();
            eprintln!("Run `zkmist prove` to generate a claim proof.");
        }
        Err(_) => {
            eprintln!("❌ NOT ELIGIBLE");
            eprintln!();
            eprintln!("This address did not pay ≥0.004 ETH in cumulative gas fees");
            eprintln!("on Ethereum mainnet before 2026-01-01.");
        }
    }

    Ok(())
}

// ── Command: status ──────────────────────────────────────────────────────

fn cmd_status(rpc_url: Option<&str>) -> Result<(), String> {
    let rpc = rpc_url.unwrap_or(DEFAULT_RPC_URL);

    eprintln!("ZKMist (ZKM) on Base");
    eprintln!("──────────────────────────────────────");
    eprintln!("Claim amount:   {} ZKM per claim", CLAIM_AMOUNT);
    eprintln!("Max claims:     {}", MAX_CLAIMS);
    eprintln!(
        "Deadline:       {} UTC ({})",
        CLAIM_DEADLINE,
        format_deadline(CLAIM_DEADLINE)
    );
    eprintln!("Chain:          Base (chain ID: {})", CHAIN_ID);
    eprintln!();

    // Query on-chain state via alloy
    let rt = tokio::runtime::Runtime::new().map_err(|e| format!("Runtime error: {}", e))?;
    rt.block_on(async {
        use alloy::primitives::Address;
        use alloy::providers::{Provider, ProviderBuilder};

        let url: reqwest::Url = rpc.parse().map_err(|e| format!("Invalid RPC URL: {}", e))?;
        let provider = ProviderBuilder::new().connect_http(url);

        let contract: Address = AIRDROP_CONTRACT
            .parse()
            .map_err(|e| format!("Invalid contract address: {}", e))?;

        if contract == Address::ZERO
            || contract
                == "0x000000000000000000000000000000000000dEaD"
                    .parse::<Address>()
                    .unwrap()
        {
            eprintln!("⚠️  Contract not deployed yet (address is placeholder).");
            eprintln!("   On-chain status unavailable until deployment.");
            return Ok::<(), String>(());
        }

        // Read totalClaims (storage slot 0)
        let total_claims_storage: alloy::primitives::U256 = provider
            .get_storage_at(contract, alloy::primitives::U256::ZERO)
            .await
            .map_err(|e| format!("Failed to query totalClaims: {}", e))?;

        let total_claims_u64: u64 = total_claims_storage.try_into().map_err(
            |e: alloy::primitives::ruint::FromUintError<u64>| {
                format!("totalClaims overflow: {}", e)
            },
        )?;

        let remaining = MAX_CLAIMS - total_claims_u64;
        let total_supply = total_claims_u64 * CLAIM_AMOUNT;
        let pct = (total_claims_u64 as f64 / MAX_CLAIMS as f64) * 100.0;

        eprintln!("Total claimed:  {}", total_claims_u64);
        eprintln!("Claims left:    {} / {}", remaining, MAX_CLAIMS);
        eprintln!("Total supply:   {} ZKM ({:.1}% of max)", total_supply, pct);
        eprintln!(
            "Status:         {}",
            if total_claims_u64 < MAX_CLAIMS {
                "✅ OPEN"
            } else {
                "🔴 CAP REACHED"
            }
        );

        Ok::<(), String>(())
    })?;

    Ok(())
}

// ── Main ─────────────────────────────────────────────────────────────────

#[tokio::main]
async fn main() {
    let cli = Cli::parse();

    let result = match cli.command {
        Commands::Fetch { cid, http } => cmd_fetch(cid.as_deref(), http),
        Commands::Prove { key_file } => cmd_prove(key_file.as_deref()),
        Commands::Submit {
            proof_file,
            rpc_url,
            private_key,
            key_file,
        } => cmd_submit(
            &proof_file,
            rpc_url.as_deref(),
            private_key.as_deref(),
            key_file.as_deref(),
        ),
        Commands::Verify { proof_file } => cmd_verify(&proof_file),
        Commands::Check { address } => cmd_check(&address),
        Commands::Status { rpc_url } => cmd_status(rpc_url.as_deref()),
    };

    if let Err(e) = result {
        eprintln!("\n❌ Error: {}", e);
        std::process::exit(1);
    }
}
