//! ZKMist CLI data types and download source parsing.

use serde::{Deserialize, Serialize};

/// Download source for the eligibility list.
#[derive(Clone, Copy, PartialEq, Debug)]
pub enum DownloadSource {
    /// Try GitHub Releases first, fall back to IPFS on failure.
    Auto,
    /// GitHub Releases only.
    Github,
    /// IPFS only.
    Ipfs,
}

pub fn parse_source(s: &str) -> Result<DownloadSource, String> {
    match s.to_lowercase().as_str() {
        "auto" => Ok(DownloadSource::Auto),
        "github" | "gh" => Ok(DownloadSource::Github),
        "ipfs" => Ok(DownloadSource::Ipfs),
        other => Err(format!(
            "Unknown source '{}'. Use: github, ipfs, or auto",
            other
        )),
    }
}

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProofFile {
    pub version: u64,
    pub proof: String,     // hex-encoded STARK seal (Groth16-wrapped)
    pub journal: String,   // hex-encoded journal bytes (84 bytes)
    pub nullifier: String, // hex-encoded 32 bytes
    pub recipient: String, // hex-encoded 20 bytes
    pub claim_amount: String,
    pub contract_address: String,
    pub chain_id: u64,
    /// Hex-encoded bincode-serialized risc0_zkvm::Receipt.
    /// Present for proofs generated by this CLI; allows local cryptographic verification.
    /// May be absent in proof files from external tools.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub receipt_hex: Option<String>,
}

#[derive(Serialize, Deserialize)]
pub struct Manifest {
    pub version: u64,
    pub cutoff_timestamp: String,
    pub fee_threshold_eth: String,
    pub total_qualified: u64,
    pub merkle_root: String,
    pub merkle_tree_depth: usize,
    #[serde(default)]
    pub files: Vec<ManifestFile>,
}

#[derive(Serialize, Deserialize)]
pub struct ManifestFile {
    pub file: String,
    pub sha256: String,
}
