//! ZKMist CLI data types and download source parsing.

use serde::{Deserialize, Serialize};

/// Download source for the eligibility list.
#[derive(Clone, Copy, PartialEq, Debug)]
pub enum DownloadSource {
    /// Try GitHub Releases first, fall back to IPFS on failure.
    Auto,
    /// GitHub Releases only.
    Github,
    /// IPFS only.
    Ipfs,
}

pub fn parse_source(s: &str) -> Result<DownloadSource, String> {
    match s.to_lowercase().as_str() {
        "auto" => Ok(DownloadSource::Auto),
        "github" | "gh" => Ok(DownloadSource::Github),
        "ipfs" => Ok(DownloadSource::Ipfs),
        other => Err(format!(
            "Unknown source '{}'. Use: github, ipfs, or auto",
            other
        )),
    }
}

/// Proof file format version.
///
/// v1: bincode v1 serialized receipt (risc0-zkvm v3.x).
/// v2+: reserved for future serialization formats.
///
/// The `proof_format_version` field allows future CLI versions to
/// handle proof files from older versions gracefully (e.g., skip
/// local verification if the receipt format is unrecognized).
pub const PROOF_FORMAT_VERSION_V1: u64 = 1;

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProofFile {
    pub version: u64,
    /// Proof file format version (independent of `version` which is the
    /// overall schema version). Allows receipt deserialization to fail
    /// gracefully when the proof was generated by a different CLI version.
    #[serde(default = "default_proof_format_version")]
    pub proof_format_version: u64,
    pub proof: String,     // hex-encoded STARK seal (Groth16-wrapped)
    pub journal: String,   // hex-encoded journal bytes (84 bytes)
    pub nullifier: String, // hex-encoded 32 bytes
    pub recipient: String, // hex-encoded 20 bytes
    pub claim_amount: String,
    pub contract_address: String,
    pub chain_id: u64,
    /// Hex-encoded bincode-serialized risc0_zkvm::Receipt.
    /// Present for proofs generated by this CLI; allows local cryptographic verification.
    /// May be absent in proof files from external tools or future versions.
    ///
    /// ⚠️ Format depends on `proof_format_version`:
    ///   - v1: bincode v1 (risc0-zkvm v3.x)
    ///   - Future versions may use different serialization.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub receipt_hex: Option<String>,
}

fn default_proof_format_version() -> u64 {
    PROOF_FORMAT_VERSION_V1
}

#[derive(Serialize, Deserialize)]
pub struct Manifest {
    pub version: u64,
    pub cutoff_timestamp: String,
    pub fee_threshold_eth: String,
    pub total_qualified: u64,
    pub merkle_root: String,
    pub merkle_tree_depth: usize,
    #[serde(default)]
    pub files: Vec<ManifestFile>,
}

#[derive(Serialize, Deserialize)]
pub struct ManifestFile {
    pub file: String,
    pub sha256: String,
}
