
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.19;

/// @dev PINNED-SRS VERIFIER — generated against the file pinned by
///      `KZG_SRS_SHA256` (~/.zkmist/cache/v2_params_k23.bin, derived from
///      ppot_0080_23.ptau). PROVENANCE CONFIRMED: `tools/verify_srs_from_ptau.rs`
///      verifies every τ-power and G2 point is byte-identical to the public
///      beaconed PSE ceremony transcript (round 0080, randao beacon from
///      Ethereum slot 7,325,000). The deployer did NOT substitute a toxic-waste
///      file; soundness rests on the ceremony (1-of-87 participants OR the
///      beacon honest). Generated by circuits/tests/claim_evm_roundtrip.rs
///      (ZKMIST_EMIT_VERIFIER + ZKMIST_USE_PINNED_SRS).
contract Halo2Verifier {
    fallback(bytes calldata) external returns (bytes memory) {
        assembly ("memory-safe") {
            // Enforce that Solidity memory layout is respected
            let data := mload(0x40)
            if iszero(eq(data, 0x80)) {
                revert(0, 0)
            }

            let success := true
            let f_p := 0x30644e72e131a029b85045b68181585d97816a916871ca8d3c208c16d87cfd47
            let f_q := 0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000001
            function validate_ec_point(x, y) -> valid {
                {
                    let x_lt_p := lt(x, 0x30644e72e131a029b85045b68181585d97816a916871ca8d3c208c16d87cfd47)
                    let y_lt_p := lt(y, 0x30644e72e131a029b85045b68181585d97816a916871ca8d3c208c16d87cfd47)
                    valid := and(x_lt_p, y_lt_p)
                }
                {
                    let y_square := mulmod(y, y, 0x30644e72e131a029b85045b68181585d97816a916871ca8d3c208c16d87cfd47)
                    let x_square := mulmod(x, x, 0x30644e72e131a029b85045b68181585d97816a916871ca8d3c208c16d87cfd47)
                    let x_cube := mulmod(x_square, x, 0x30644e72e131a029b85045b68181585d97816a916871ca8d3c208c16d87cfd47)
                    let x_cube_plus_3 := addmod(x_cube, 3, 0x30644e72e131a029b85045b68181585d97816a916871ca8d3c208c16d87cfd47)
                    let is_affine := eq(x_cube_plus_3, y_square)
                    valid := and(valid, is_affine)
                }
            }
            mstore(0xa0, mod(calldataload(0x0), f_q))
mstore(0xc0, mod(calldataload(0x20), f_q))
mstore(0xe0, mod(calldataload(0x40), f_q))
mstore(0x100, mod(calldataload(0x60), f_q))
mstore(0x80, 6760514555507996243350237062847408310009674054655535363410272918669425862572)

        {
            let x := calldataload(0x80)
            mstore(0x120, x)
            let y := calldataload(0xa0)
            mstore(0x140, y)
            success := and(validate_ec_point(x, y), success)
        }
mstore(0x160, keccak256(0x80, 224))
{
            let hash := mload(0x160)
            mstore(0x180, mod(hash, f_q))
            mstore(0x1a0, hash)
        }

        {
            let x := calldataload(0xc0)
            mstore(0x1c0, x)
            let y := calldataload(0xe0)
            mstore(0x1e0, y)
            success := and(validate_ec_point(x, y), success)
        }

        {
            let x := calldataload(0x100)
            mstore(0x200, x)
            let y := calldataload(0x120)
            mstore(0x220, y)
            success := and(validate_ec_point(x, y), success)
        }
mstore(0x240, keccak256(0x1a0, 160))
{
            let hash := mload(0x240)
            mstore(0x260, mod(hash, f_q))
            mstore(0x280, hash)
        }
mstore8(672, 1)
mstore(0x2a0, keccak256(0x280, 33))
{
            let hash := mload(0x2a0)
            mstore(0x2c0, mod(hash, f_q))
            mstore(0x2e0, hash)
        }

        {
            let x := calldataload(0x140)
            mstore(0x300, x)
            let y := calldataload(0x160)
            mstore(0x320, y)
            success := and(validate_ec_point(x, y), success)
        }

        {
            let x := calldataload(0x180)
            mstore(0x340, x)
            let y := calldataload(0x1a0)
            mstore(0x360, y)
            success := and(validate_ec_point(x, y), success)
        }

        {
            let x := calldataload(0x1c0)
            mstore(0x380, x)
            let y := calldataload(0x1e0)
            mstore(0x3a0, y)
            success := and(validate_ec_point(x, y), success)
        }
mstore(0x3c0, keccak256(0x2e0, 224))
{
            let hash := mload(0x3c0)
            mstore(0x3e0, mod(hash, f_q))
            mstore(0x400, hash)
        }

        {
            let x := calldataload(0x200)
            mstore(0x420, x)
            let y := calldataload(0x220)
            mstore(0x440, y)
            success := and(validate_ec_point(x, y), success)
        }

        {
            let x := calldataload(0x240)
            mstore(0x460, x)
            let y := calldataload(0x260)
            mstore(0x480, y)
            success := and(validate_ec_point(x, y), success)
        }

        {
            let x := calldataload(0x280)
            mstore(0x4a0, x)
            let y := calldataload(0x2a0)
            mstore(0x4c0, y)
            success := and(validate_ec_point(x, y), success)
        }

        {
            let x := calldataload(0x2c0)
            mstore(0x4e0, x)
            let y := calldataload(0x2e0)
            mstore(0x500, y)
            success := and(validate_ec_point(x, y), success)
        }
mstore(0x520, keccak256(0x400, 288))
{
            let hash := mload(0x520)
            mstore(0x540, mod(hash, f_q))
            mstore(0x560, hash)
        }
mstore(0x580, mod(calldataload(0x300), f_q))
mstore(0x5a0, mod(calldataload(0x320), f_q))
mstore(0x5c0, mod(calldataload(0x340), f_q))
mstore(0x5e0, mod(calldataload(0x360), f_q))
mstore(0x600, mod(calldataload(0x380), f_q))
mstore(0x620, mod(calldataload(0x3a0), f_q))
mstore(0x640, mod(calldataload(0x3c0), f_q))
mstore(0x660, mod(calldataload(0x3e0), f_q))
mstore(0x680, mod(calldataload(0x400), f_q))
mstore(0x6a0, mod(calldataload(0x420), f_q))
mstore(0x6c0, mod(calldataload(0x440), f_q))
mstore(0x6e0, mod(calldataload(0x460), f_q))
mstore(0x700, mod(calldataload(0x480), f_q))
mstore(0x720, mod(calldataload(0x4a0), f_q))
mstore(0x740, mod(calldataload(0x4c0), f_q))
mstore(0x760, mod(calldataload(0x4e0), f_q))
mstore(0x780, mod(calldataload(0x500), f_q))
mstore(0x7a0, mod(calldataload(0x520), f_q))
mstore(0x7c0, mod(calldataload(0x540), f_q))
mstore(0x7e0, keccak256(0x560, 640))
{
            let hash := mload(0x7e0)
            mstore(0x800, mod(hash, f_q))
            mstore(0x820, hash)
        }
mstore8(2112, 1)
mstore(0x840, keccak256(0x820, 33))
{
            let hash := mload(0x840)
            mstore(0x860, mod(hash, f_q))
            mstore(0x880, hash)
        }

        {
            let x := calldataload(0x560)
            mstore(0x8a0, x)
            let y := calldataload(0x580)
            mstore(0x8c0, y)
            success := and(validate_ec_point(x, y), success)
        }
mstore(0x8e0, keccak256(0x880, 96))
{
            let hash := mload(0x8e0)
            mstore(0x900, mod(hash, f_q))
            mstore(0x920, hash)
        }

        {
            let x := calldataload(0x5a0)
            mstore(0x940, x)
            let y := calldataload(0x5c0)
            mstore(0x960, y)
            success := and(validate_ec_point(x, y), success)
        }
mstore(0x980, mulmod(mload(0x540), mload(0x540), f_q))
mstore(0x9a0, mulmod(mload(0x980), mload(0x980), f_q))
mstore(0x9c0, mulmod(mload(0x9a0), mload(0x9a0), f_q))
mstore(0x9e0, mulmod(mload(0x9c0), mload(0x9c0), f_q))
mstore(0xa00, mulmod(mload(0x9e0), mload(0x9e0), f_q))
mstore(0xa20, mulmod(mload(0xa00), mload(0xa00), f_q))
mstore(0xa40, mulmod(mload(0xa20), mload(0xa20), f_q))
mstore(0xa60, mulmod(mload(0xa40), mload(0xa40), f_q))
mstore(0xa80, mulmod(mload(0xa60), mload(0xa60), f_q))
mstore(0xaa0, mulmod(mload(0xa80), mload(0xa80), f_q))
mstore(0xac0, mulmod(mload(0xaa0), mload(0xaa0), f_q))
mstore(0xae0, mulmod(mload(0xac0), mload(0xac0), f_q))
mstore(0xb00, mulmod(mload(0xae0), mload(0xae0), f_q))
mstore(0xb20, mulmod(mload(0xb00), mload(0xb00), f_q))
mstore(0xb40, mulmod(mload(0xb20), mload(0xb20), f_q))
mstore(0xb60, mulmod(mload(0xb40), mload(0xb40), f_q))
mstore(0xb80, mulmod(mload(0xb60), mload(0xb60), f_q))
mstore(0xba0, mulmod(mload(0xb80), mload(0xb80), f_q))
mstore(0xbc0, mulmod(mload(0xba0), mload(0xba0), f_q))
mstore(0xbe0, mulmod(mload(0xbc0), mload(0xbc0), f_q))
mstore(0xc00, mulmod(mload(0xbe0), mload(0xbe0), f_q))
mstore(0xc20, mulmod(mload(0xc00), mload(0xc00), f_q))
mstore(0xc40, mulmod(mload(0xc20), mload(0xc20), f_q))
mstore(0xc60, addmod(mload(0xc40), 21888242871839275222246405745257275088548364400416034343698204186575808495616, f_q))
mstore(0xc80, mulmod(mload(0xc60), 21888240262557392955334514970720457388010314637169927192662615958087340972065, f_q))
mstore(0xca0, mulmod(mload(0xc80), 4506835738822104338668100540817374747935106310012997856968187171738630203507, f_q))
mstore(0xcc0, addmod(mload(0x540), 17381407133017170883578305204439900340613258090403036486730017014837178292110, f_q))
mstore(0xce0, mulmod(mload(0xc80), 21710372849001950800533397158415938114909991150039389063546734567764856596059, f_q))
mstore(0xd00, addmod(mload(0x540), 177870022837324421713008586841336973638373250376645280151469618810951899558, f_q))
mstore(0xd20, mulmod(mload(0xc80), 1887003188133998471169152042388914354640772748308168868301418279904560637395, f_q))
mstore(0xd40, addmod(mload(0x540), 20001239683705276751077253702868360733907591652107865475396785906671247858222, f_q))
mstore(0xd60, mulmod(mload(0xc80), 2785514556381676080176937710880804108647911392478702105860685610379369825016, f_q))
mstore(0xd80, addmod(mload(0x540), 19102728315457599142069468034376470979900453007937332237837518576196438670601, f_q))
mstore(0xda0, mulmod(mload(0xc80), 14655294445420895451632927078981340937842238432098198055057679026789553137428, f_q))
mstore(0xdc0, addmod(mload(0x540), 7232948426418379770613478666275934150706125968317836288640525159786255358189, f_q))
mstore(0xde0, mulmod(mload(0xc80), 8734126352828345679573237859165904705806588461301144420590422589042130041188, f_q))
mstore(0xe00, addmod(mload(0x540), 13154116519010929542673167886091370382741775939114889923107781597533678454429, f_q))
mstore(0xe20, mulmod(mload(0xc80), 9741553891420464328295280489650144566903017206473301385034033384879943874347, f_q))
mstore(0xe40, addmod(mload(0x540), 12146688980418810893951125255607130521645347193942732958664170801695864621270, f_q))
mstore(0xe60, mulmod(mload(0xc80), 1, f_q))
mstore(0xe80, addmod(mload(0x540), 21888242871839275222246405745257275088548364400416034343698204186575808495616, f_q))
mstore(0xea0, mulmod(mload(0xc80), 8374374965308410102411073611984011876711565317741801500439755773472076597347, f_q))
mstore(0xec0, addmod(mload(0x540), 13513867906530865119835332133273263211836799082674232843258448413103731898270, f_q))
mstore(0xee0, mulmod(mload(0xc80), 11211301017135681023579411905410872569206244553457844956874280139879520583390, f_q))
mstore(0xf00, addmod(mload(0x540), 10676941854703594198666993839846402519342119846958189386823924046696287912227, f_q))
mstore(0xf20, mulmod(mload(0xc80), 3615478808282855240548287271348143516886772452944084747768312988864436725401, f_q))
mstore(0xf40, addmod(mload(0x540), 18272764063556419981698118473909131571661591947471949595929891197711371770216, f_q))
{
            let prod := mload(0xcc0)

                prod := mulmod(mload(0xd00), prod, f_q)
                mstore(0xf60, prod)
            
                prod := mulmod(mload(0xd40), prod, f_q)
                mstore(0xf80, prod)
            
                prod := mulmod(mload(0xd80), prod, f_q)
                mstore(0xfa0, prod)
            
                prod := mulmod(mload(0xdc0), prod, f_q)
                mstore(0xfc0, prod)
            
                prod := mulmod(mload(0xe00), prod, f_q)
                mstore(0xfe0, prod)
            
                prod := mulmod(mload(0xe40), prod, f_q)
                mstore(0x1000, prod)
            
                prod := mulmod(mload(0xe80), prod, f_q)
                mstore(0x1020, prod)
            
                prod := mulmod(mload(0xec0), prod, f_q)
                mstore(0x1040, prod)
            
                prod := mulmod(mload(0xf00), prod, f_q)
                mstore(0x1060, prod)
            
                prod := mulmod(mload(0xf40), prod, f_q)
                mstore(0x1080, prod)
            
                prod := mulmod(mload(0xc60), prod, f_q)
                mstore(0x10a0, prod)
            
        }
mstore(0x10e0, 32)
mstore(0x1100, 32)
mstore(0x1120, 32)
mstore(0x1140, mload(0x10a0))
mstore(0x1160, 21888242871839275222246405745257275088548364400416034343698204186575808495615)
mstore(0x1180, 21888242871839275222246405745257275088548364400416034343698204186575808495617)
success := and(eq(staticcall(gas(), 0x5, 0x10e0, 0xc0, 0x10c0, 0x20), 1), success)
{
            
            let inv := mload(0x10c0)
            let v
        
                    v := mload(0xc60)
                    mstore(3168, mulmod(mload(0x1080), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0xf40)
                    mstore(3904, mulmod(mload(0x1060), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0xf00)
                    mstore(3840, mulmod(mload(0x1040), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0xec0)
                    mstore(3776, mulmod(mload(0x1020), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0xe80)
                    mstore(3712, mulmod(mload(0x1000), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0xe40)
                    mstore(3648, mulmod(mload(0xfe0), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0xe00)
                    mstore(3584, mulmod(mload(0xfc0), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0xdc0)
                    mstore(3520, mulmod(mload(0xfa0), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0xd80)
                    mstore(3456, mulmod(mload(0xf80), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0xd40)
                    mstore(3392, mulmod(mload(0xf60), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0xd00)
                    mstore(3328, mulmod(mload(0xcc0), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                mstore(0xcc0, inv)

        }
mstore(0x11a0, mulmod(mload(0xca0), mload(0xcc0), f_q))
mstore(0x11c0, mulmod(mload(0xce0), mload(0xd00), f_q))
mstore(0x11e0, mulmod(mload(0xd20), mload(0xd40), f_q))
mstore(0x1200, mulmod(mload(0xd60), mload(0xd80), f_q))
mstore(0x1220, mulmod(mload(0xda0), mload(0xdc0), f_q))
mstore(0x1240, mulmod(mload(0xde0), mload(0xe00), f_q))
mstore(0x1260, mulmod(mload(0xe20), mload(0xe40), f_q))
mstore(0x1280, mulmod(mload(0xe60), mload(0xe80), f_q))
mstore(0x12a0, mulmod(mload(0xea0), mload(0xec0), f_q))
mstore(0x12c0, mulmod(mload(0xee0), mload(0xf00), f_q))
mstore(0x12e0, mulmod(mload(0xf20), mload(0xf40), f_q))
{
            let result := mulmod(mload(0x1280), mload(0xa0), f_q)
result := addmod(mulmod(mload(0x12a0), mload(0xc0), f_q), result, f_q)
result := addmod(mulmod(mload(0x12c0), mload(0xe0), f_q), result, f_q)
result := addmod(mulmod(mload(0x12e0), mload(0x100), f_q), result, f_q)
mstore(4864, result)
        }
mstore(0x1320, mulmod(mload(0x5c0), mload(0x5a0), f_q))
mstore(0x1340, addmod(mload(0x580), mload(0x1320), f_q))
mstore(0x1360, addmod(mload(0x1340), sub(f_q, mload(0x5e0)), f_q))
mstore(0x1380, mulmod(mload(0x1360), mload(0x640), f_q))
mstore(0x13a0, mulmod(mload(0x3e0), mload(0x1380), f_q))
mstore(0x13c0, addmod(1, sub(f_q, mload(0x700)), f_q))
mstore(0x13e0, mulmod(mload(0x13c0), mload(0x1280), f_q))
mstore(0x1400, addmod(mload(0x13a0), mload(0x13e0), f_q))
mstore(0x1420, mulmod(mload(0x3e0), mload(0x1400), f_q))
mstore(0x1440, mulmod(mload(0x700), mload(0x700), f_q))
mstore(0x1460, addmod(mload(0x1440), sub(f_q, mload(0x700)), f_q))
mstore(0x1480, mulmod(mload(0x1460), mload(0x11a0), f_q))
mstore(0x14a0, addmod(mload(0x1420), mload(0x1480), f_q))
mstore(0x14c0, mulmod(mload(0x3e0), mload(0x14a0), f_q))
mstore(0x14e0, addmod(1, sub(f_q, mload(0x11a0)), f_q))
mstore(0x1500, addmod(mload(0x11c0), mload(0x11e0), f_q))
mstore(0x1520, addmod(mload(0x1500), mload(0x1200), f_q))
mstore(0x1540, addmod(mload(0x1520), mload(0x1220), f_q))
mstore(0x1560, addmod(mload(0x1540), mload(0x1240), f_q))
mstore(0x1580, addmod(mload(0x1560), mload(0x1260), f_q))
mstore(0x15a0, addmod(mload(0x14e0), sub(f_q, mload(0x1580)), f_q))
mstore(0x15c0, mulmod(mload(0x6a0), mload(0x260), f_q))
mstore(0x15e0, addmod(mload(0x600), mload(0x15c0), f_q))
mstore(0x1600, addmod(mload(0x15e0), mload(0x2c0), f_q))
mstore(0x1620, mulmod(mload(0x6c0), mload(0x260), f_q))
mstore(0x1640, addmod(mload(0x580), mload(0x1620), f_q))
mstore(0x1660, addmod(mload(0x1640), mload(0x2c0), f_q))
mstore(0x1680, mulmod(mload(0x1660), mload(0x1600), f_q))
mstore(0x16a0, mulmod(mload(0x6e0), mload(0x260), f_q))
mstore(0x16c0, addmod(mload(0x1300), mload(0x16a0), f_q))
mstore(0x16e0, addmod(mload(0x16c0), mload(0x2c0), f_q))
mstore(0x1700, mulmod(mload(0x16e0), mload(0x1680), f_q))
mstore(0x1720, mulmod(mload(0x1700), mload(0x720), f_q))
mstore(0x1740, mulmod(1, mload(0x260), f_q))
mstore(0x1760, mulmod(mload(0x540), mload(0x1740), f_q))
mstore(0x1780, addmod(mload(0x600), mload(0x1760), f_q))
mstore(0x17a0, addmod(mload(0x1780), mload(0x2c0), f_q))
mstore(0x17c0, mulmod(4131629893567559867359510883348571134090853742863529169391034518566172092834, mload(0x260), f_q))
mstore(0x17e0, mulmod(mload(0x540), mload(0x17c0), f_q))
mstore(0x1800, addmod(mload(0x580), mload(0x17e0), f_q))
mstore(0x1820, addmod(mload(0x1800), mload(0x2c0), f_q))
mstore(0x1840, mulmod(mload(0x1820), mload(0x17a0), f_q))
mstore(0x1860, mulmod(8910878055287538404433155982483128285667088683464058436815641868457422632747, mload(0x260), f_q))
mstore(0x1880, mulmod(mload(0x540), mload(0x1860), f_q))
mstore(0x18a0, addmod(mload(0x1300), mload(0x1880), f_q))
mstore(0x18c0, addmod(mload(0x18a0), mload(0x2c0), f_q))
mstore(0x18e0, mulmod(mload(0x18c0), mload(0x1840), f_q))
mstore(0x1900, mulmod(mload(0x18e0), mload(0x700), f_q))
mstore(0x1920, addmod(mload(0x1720), sub(f_q, mload(0x1900)), f_q))
mstore(0x1940, mulmod(mload(0x1920), mload(0x15a0), f_q))
mstore(0x1960, addmod(mload(0x14c0), mload(0x1940), f_q))
mstore(0x1980, mulmod(mload(0x3e0), mload(0x1960), f_q))
mstore(0x19a0, addmod(1, sub(f_q, mload(0x740)), f_q))
mstore(0x19c0, mulmod(mload(0x19a0), mload(0x1280), f_q))
mstore(0x19e0, addmod(mload(0x1980), mload(0x19c0), f_q))
mstore(0x1a00, mulmod(mload(0x3e0), mload(0x19e0), f_q))
mstore(0x1a20, mulmod(mload(0x740), mload(0x740), f_q))
mstore(0x1a40, addmod(mload(0x1a20), sub(f_q, mload(0x740)), f_q))
mstore(0x1a60, mulmod(mload(0x1a40), mload(0x11a0), f_q))
mstore(0x1a80, addmod(mload(0x1a00), mload(0x1a60), f_q))
mstore(0x1aa0, mulmod(mload(0x3e0), mload(0x1a80), f_q))
mstore(0x1ac0, addmod(mload(0x780), mload(0x260), f_q))
mstore(0x1ae0, mulmod(mload(0x1ac0), mload(0x760), f_q))
mstore(0x1b00, addmod(mload(0x7c0), mload(0x2c0), f_q))
mstore(0x1b20, mulmod(mload(0x1b00), mload(0x1ae0), f_q))
mstore(0x1b40, mulmod(mload(0x580), mload(0x660), f_q))
mstore(0x1b60, addmod(mload(0x1b40), mload(0x260), f_q))
mstore(0x1b80, mulmod(mload(0x1b60), mload(0x740), f_q))
mstore(0x1ba0, addmod(mload(0x620), mload(0x2c0), f_q))
mstore(0x1bc0, mulmod(mload(0x1ba0), mload(0x1b80), f_q))
mstore(0x1be0, addmod(mload(0x1b20), sub(f_q, mload(0x1bc0)), f_q))
mstore(0x1c00, mulmod(mload(0x1be0), mload(0x15a0), f_q))
mstore(0x1c20, addmod(mload(0x1aa0), mload(0x1c00), f_q))
mstore(0x1c40, mulmod(mload(0x3e0), mload(0x1c20), f_q))
mstore(0x1c60, addmod(mload(0x780), sub(f_q, mload(0x7c0)), f_q))
mstore(0x1c80, mulmod(mload(0x1c60), mload(0x1280), f_q))
mstore(0x1ca0, addmod(mload(0x1c40), mload(0x1c80), f_q))
mstore(0x1cc0, mulmod(mload(0x3e0), mload(0x1ca0), f_q))
mstore(0x1ce0, mulmod(mload(0x1c60), mload(0x15a0), f_q))
mstore(0x1d00, addmod(mload(0x780), sub(f_q, mload(0x7a0)), f_q))
mstore(0x1d20, mulmod(mload(0x1d00), mload(0x1ce0), f_q))
mstore(0x1d40, addmod(mload(0x1cc0), mload(0x1d20), f_q))
mstore(0x1d60, mulmod(mload(0xc40), mload(0xc40), f_q))
mstore(0x1d80, mulmod(mload(0x1d60), mload(0xc40), f_q))
mstore(0x1da0, mulmod(mload(0x1d80), mload(0xc40), f_q))
mstore(0x1dc0, mulmod(1, mload(0xc40), f_q))
mstore(0x1de0, mulmod(1, mload(0x1d60), f_q))
mstore(0x1e00, mulmod(1, mload(0x1d80), f_q))
mstore(0x1e20, mulmod(mload(0x1d40), mload(0xc60), f_q))
mstore(0x1e40, mulmod(mload(0x980), mload(0x540), f_q))
mstore(0x1e60, mulmod(mload(0x1e40), mload(0x540), f_q))
mstore(0x1e80, mulmod(mload(0x540), 9741553891420464328295280489650144566903017206473301385034033384879943874347, f_q))
mstore(0x1ea0, addmod(mload(0x900), sub(f_q, mload(0x1e80)), f_q))
mstore(0x1ec0, mulmod(mload(0x540), 1, f_q))
mstore(0x1ee0, addmod(mload(0x900), sub(f_q, mload(0x1ec0)), f_q))
mstore(0x1f00, mulmod(mload(0x540), 8374374965308410102411073611984011876711565317741801500439755773472076597347, f_q))
mstore(0x1f20, addmod(mload(0x900), sub(f_q, mload(0x1f00)), f_q))
mstore(0x1f40, mulmod(mload(0x540), 11211301017135681023579411905410872569206244553457844956874280139879520583390, f_q))
mstore(0x1f60, addmod(mload(0x900), sub(f_q, mload(0x1f40)), f_q))
mstore(0x1f80, mulmod(mload(0x540), 3615478808282855240548287271348143516886772452944084747768312988864436725401, f_q))
mstore(0x1fa0, addmod(mload(0x900), sub(f_q, mload(0x1f80)), f_q))
mstore(0x1fc0, mulmod(13213688729882003894512633350385593288217014177373218494356903340348818451480, mload(0x1e40), f_q))
mstore(0x1fe0, mulmod(mload(0x1fc0), 1, f_q))
{
            let result := mulmod(mload(0x900), mload(0x1fc0), f_q)
result := addmod(mulmod(mload(0x540), sub(f_q, mload(0x1fe0)), f_q), result, f_q)
mstore(8192, result)
        }
mstore(0x2020, mulmod(8207090019724696496350398458716998472718344609680392612601596849934418295470, mload(0x1e40), f_q))
mstore(0x2040, mulmod(mload(0x2020), 8374374965308410102411073611984011876711565317741801500439755773472076597347, f_q))
{
            let result := mulmod(mload(0x900), mload(0x2020), f_q)
result := addmod(mulmod(mload(0x540), sub(f_q, mload(0x2040)), f_q), result, f_q)
mstore(8288, result)
        }
mstore(0x2080, mulmod(7391709068497399131897422873231908718558236401035363928063603272120120747483, mload(0x1e40), f_q))
mstore(0x20a0, mulmod(mload(0x2080), 11211301017135681023579411905410872569206244553457844956874280139879520583390, f_q))
{
            let result := mulmod(mload(0x900), mload(0x2080), f_q)
result := addmod(mulmod(mload(0x540), sub(f_q, mload(0x20a0)), f_q), result, f_q)
mstore(8384, result)
        }
mstore(0x20e0, mulmod(19036273796805830823244991598792794567595348772040298280440552631112242221017, mload(0x1e40), f_q))
mstore(0x2100, mulmod(mload(0x20e0), 3615478808282855240548287271348143516886772452944084747768312988864436725401, f_q))
{
            let result := mulmod(mload(0x900), mload(0x20e0), f_q)
result := addmod(mulmod(mload(0x540), sub(f_q, mload(0x2100)), f_q), result, f_q)
mstore(8480, result)
        }
mstore(0x2140, mulmod(1, mload(0x1ee0), f_q))
mstore(0x2160, mulmod(mload(0x2140), mload(0x1f20), f_q))
mstore(0x2180, mulmod(mload(0x2160), mload(0x1f60), f_q))
mstore(0x21a0, mulmod(mload(0x2180), mload(0x1fa0), f_q))
mstore(0x21c0, mulmod(13513867906530865119835332133273263211836799082674232843258448413103731898271, mload(0x540), f_q))
mstore(0x21e0, mulmod(mload(0x21c0), 1, f_q))
{
            let result := mulmod(mload(0x900), mload(0x21c0), f_q)
result := addmod(mulmod(mload(0x540), sub(f_q, mload(0x21e0)), f_q), result, f_q)
mstore(8704, result)
        }
mstore(0x2220, mulmod(8374374965308410102411073611984011876711565317741801500439755773472076597346, mload(0x540), f_q))
mstore(0x2240, mulmod(mload(0x2220), 8374374965308410102411073611984011876711565317741801500439755773472076597347, f_q))
{
            let result := mulmod(mload(0x900), mload(0x2220), f_q)
result := addmod(mulmod(mload(0x540), sub(f_q, mload(0x2240)), f_q), result, f_q)
mstore(8800, result)
        }
mstore(0x2280, mulmod(12146688980418810893951125255607130521645347193942732958664170801695864621271, mload(0x540), f_q))
mstore(0x22a0, mulmod(mload(0x2280), 1, f_q))
{
            let result := mulmod(mload(0x900), mload(0x2280), f_q)
result := addmod(mulmod(mload(0x540), sub(f_q, mload(0x22a0)), f_q), result, f_q)
mstore(8896, result)
        }
mstore(0x22e0, mulmod(9741553891420464328295280489650144566903017206473301385034033384879943874346, mload(0x540), f_q))
mstore(0x2300, mulmod(mload(0x22e0), 9741553891420464328295280489650144566903017206473301385034033384879943874347, f_q))
{
            let result := mulmod(mload(0x900), mload(0x22e0), f_q)
result := addmod(mulmod(mload(0x540), sub(f_q, mload(0x2300)), f_q), result, f_q)
mstore(8992, result)
        }
mstore(0x2340, mulmod(mload(0x2140), mload(0x1ea0), f_q))
{
            let result := mulmod(mload(0x900), 1, f_q)
result := addmod(mulmod(mload(0x540), 21888242871839275222246405745257275088548364400416034343698204186575808495616, f_q), result, f_q)
mstore(9056, result)
        }
{
            let prod := mload(0x2000)

                prod := mulmod(mload(0x2060), prod, f_q)
                mstore(0x2380, prod)
            
                prod := mulmod(mload(0x20c0), prod, f_q)
                mstore(0x23a0, prod)
            
                prod := mulmod(mload(0x2120), prod, f_q)
                mstore(0x23c0, prod)
            
                prod := mulmod(mload(0x2200), prod, f_q)
                mstore(0x23e0, prod)
            
                prod := mulmod(mload(0x2260), prod, f_q)
                mstore(0x2400, prod)
            
                prod := mulmod(mload(0x2160), prod, f_q)
                mstore(0x2420, prod)
            
                prod := mulmod(mload(0x22c0), prod, f_q)
                mstore(0x2440, prod)
            
                prod := mulmod(mload(0x2320), prod, f_q)
                mstore(0x2460, prod)
            
                prod := mulmod(mload(0x2340), prod, f_q)
                mstore(0x2480, prod)
            
                prod := mulmod(mload(0x2360), prod, f_q)
                mstore(0x24a0, prod)
            
                prod := mulmod(mload(0x2140), prod, f_q)
                mstore(0x24c0, prod)
            
        }
mstore(0x2500, 32)
mstore(0x2520, 32)
mstore(0x2540, 32)
mstore(0x2560, mload(0x24c0))
mstore(0x2580, 21888242871839275222246405745257275088548364400416034343698204186575808495615)
mstore(0x25a0, 21888242871839275222246405745257275088548364400416034343698204186575808495617)
success := and(eq(staticcall(gas(), 0x5, 0x2500, 0xc0, 0x24e0, 0x20), 1), success)
{
            
            let inv := mload(0x24e0)
            let v
        
                    v := mload(0x2140)
                    mstore(8512, mulmod(mload(0x24a0), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0x2360)
                    mstore(9056, mulmod(mload(0x2480), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0x2340)
                    mstore(9024, mulmod(mload(0x2460), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0x2320)
                    mstore(8992, mulmod(mload(0x2440), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0x22c0)
                    mstore(8896, mulmod(mload(0x2420), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0x2160)
                    mstore(8544, mulmod(mload(0x2400), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0x2260)
                    mstore(8800, mulmod(mload(0x23e0), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0x2200)
                    mstore(8704, mulmod(mload(0x23c0), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0x2120)
                    mstore(8480, mulmod(mload(0x23a0), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0x20c0)
                    mstore(8384, mulmod(mload(0x2380), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0x2060)
                    mstore(8288, mulmod(mload(0x2000), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                mstore(0x2000, inv)

        }
{
            let result := mload(0x2000)
result := addmod(mload(0x2060), result, f_q)
result := addmod(mload(0x20c0), result, f_q)
result := addmod(mload(0x2120), result, f_q)
mstore(9664, result)
        }
mstore(0x25e0, mulmod(mload(0x21a0), mload(0x2160), f_q))
{
            let result := mload(0x2200)
result := addmod(mload(0x2260), result, f_q)
mstore(9728, result)
        }
mstore(0x2620, mulmod(mload(0x21a0), mload(0x2340), f_q))
{
            let result := mload(0x22c0)
result := addmod(mload(0x2320), result, f_q)
mstore(9792, result)
        }
mstore(0x2660, mulmod(mload(0x21a0), mload(0x2140), f_q))
{
            let result := mload(0x2360)
mstore(9856, result)
        }
{
            let prod := mload(0x25c0)

                prod := mulmod(mload(0x2600), prod, f_q)
                mstore(0x26a0, prod)
            
                prod := mulmod(mload(0x2640), prod, f_q)
                mstore(0x26c0, prod)
            
                prod := mulmod(mload(0x2680), prod, f_q)
                mstore(0x26e0, prod)
            
        }
mstore(0x2720, 32)
mstore(0x2740, 32)
mstore(0x2760, 32)
mstore(0x2780, mload(0x26e0))
mstore(0x27a0, 21888242871839275222246405745257275088548364400416034343698204186575808495615)
mstore(0x27c0, 21888242871839275222246405745257275088548364400416034343698204186575808495617)
success := and(eq(staticcall(gas(), 0x5, 0x2720, 0xc0, 0x2700, 0x20), 1), success)
{
            
            let inv := mload(0x2700)
            let v
        
                    v := mload(0x2680)
                    mstore(9856, mulmod(mload(0x26c0), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0x2640)
                    mstore(9792, mulmod(mload(0x26a0), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0x2600)
                    mstore(9728, mulmod(mload(0x25c0), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                mstore(0x25c0, inv)

        }
mstore(0x27e0, mulmod(mload(0x25e0), mload(0x2600), f_q))
mstore(0x2800, mulmod(mload(0x2620), mload(0x2640), f_q))
mstore(0x2820, mulmod(mload(0x2660), mload(0x2680), f_q))
mstore(0x2840, mulmod(mload(0x800), mload(0x800), f_q))
mstore(0x2860, mulmod(mload(0x2840), mload(0x800), f_q))
mstore(0x2880, mulmod(mload(0x2860), mload(0x800), f_q))
mstore(0x28a0, mulmod(mload(0x2880), mload(0x800), f_q))
mstore(0x28c0, mulmod(mload(0x28a0), mload(0x800), f_q))
mstore(0x28e0, mulmod(mload(0x28c0), mload(0x800), f_q))
mstore(0x2900, mulmod(mload(0x28e0), mload(0x800), f_q))
mstore(0x2920, mulmod(mload(0x2900), mload(0x800), f_q))
mstore(0x2940, mulmod(mload(0x2920), mload(0x800), f_q))
mstore(0x2960, mulmod(mload(0x860), mload(0x860), f_q))
mstore(0x2980, mulmod(mload(0x2960), mload(0x860), f_q))
mstore(0x29a0, mulmod(mload(0x2980), mload(0x860), f_q))
{
            let result := mulmod(mload(0x580), mload(0x2000), f_q)
result := addmod(mulmod(mload(0x5a0), mload(0x2060), f_q), result, f_q)
result := addmod(mulmod(mload(0x5c0), mload(0x20c0), f_q), result, f_q)
result := addmod(mulmod(mload(0x5e0), mload(0x2120), f_q), result, f_q)
mstore(10688, result)
        }
mstore(0x29e0, mulmod(mload(0x29c0), mload(0x25c0), f_q))
mstore(0x2a00, mulmod(sub(f_q, mload(0x29e0)), 1, f_q))
mstore(0x2a20, mulmod(mload(0x2a00), 1, f_q))
mstore(0x2a40, mulmod(1, mload(0x25e0), f_q))
{
            let result := mulmod(mload(0x700), mload(0x2200), f_q)
result := addmod(mulmod(mload(0x720), mload(0x2260), f_q), result, f_q)
mstore(10848, result)
        }
mstore(0x2a80, mulmod(mload(0x2a60), mload(0x27e0), f_q))
mstore(0x2aa0, mulmod(sub(f_q, mload(0x2a80)), 1, f_q))
mstore(0x2ac0, mulmod(mload(0x2a40), 1, f_q))
{
            let result := mulmod(mload(0x740), mload(0x2200), f_q)
result := addmod(mulmod(mload(0x760), mload(0x2260), f_q), result, f_q)
mstore(10976, result)
        }
mstore(0x2b00, mulmod(mload(0x2ae0), mload(0x27e0), f_q))
mstore(0x2b20, mulmod(sub(f_q, mload(0x2b00)), mload(0x800), f_q))
mstore(0x2b40, mulmod(mload(0x2a40), mload(0x800), f_q))
mstore(0x2b60, addmod(mload(0x2aa0), mload(0x2b20), f_q))
mstore(0x2b80, mulmod(mload(0x2b60), mload(0x860), f_q))
mstore(0x2ba0, mulmod(mload(0x2ac0), mload(0x860), f_q))
mstore(0x2bc0, mulmod(mload(0x2b40), mload(0x860), f_q))
mstore(0x2be0, addmod(mload(0x2a20), mload(0x2b80), f_q))
mstore(0x2c00, mulmod(1, mload(0x2620), f_q))
{
            let result := mulmod(mload(0x780), mload(0x22c0), f_q)
result := addmod(mulmod(mload(0x7a0), mload(0x2320), f_q), result, f_q)
mstore(11296, result)
        }
mstore(0x2c40, mulmod(mload(0x2c20), mload(0x2800), f_q))
mstore(0x2c60, mulmod(sub(f_q, mload(0x2c40)), 1, f_q))
mstore(0x2c80, mulmod(mload(0x2c00), 1, f_q))
mstore(0x2ca0, mulmod(mload(0x2c60), mload(0x2960), f_q))
mstore(0x2cc0, mulmod(mload(0x2c80), mload(0x2960), f_q))
mstore(0x2ce0, addmod(mload(0x2be0), mload(0x2ca0), f_q))
mstore(0x2d00, mulmod(1, mload(0x2660), f_q))
{
            let result := mulmod(mload(0x7c0), mload(0x2360), f_q)
mstore(11552, result)
        }
mstore(0x2d40, mulmod(mload(0x2d20), mload(0x2820), f_q))
mstore(0x2d60, mulmod(sub(f_q, mload(0x2d40)), 1, f_q))
mstore(0x2d80, mulmod(mload(0x2d00), 1, f_q))
{
            let result := mulmod(mload(0x600), mload(0x2360), f_q)
mstore(11680, result)
        }
mstore(0x2dc0, mulmod(mload(0x2da0), mload(0x2820), f_q))
mstore(0x2de0, mulmod(sub(f_q, mload(0x2dc0)), mload(0x800), f_q))
mstore(0x2e00, mulmod(mload(0x2d00), mload(0x800), f_q))
mstore(0x2e20, addmod(mload(0x2d60), mload(0x2de0), f_q))
{
            let result := mulmod(mload(0x620), mload(0x2360), f_q)
mstore(11840, result)
        }
mstore(0x2e60, mulmod(mload(0x2e40), mload(0x2820), f_q))
mstore(0x2e80, mulmod(sub(f_q, mload(0x2e60)), mload(0x2840), f_q))
mstore(0x2ea0, mulmod(mload(0x2d00), mload(0x2840), f_q))
mstore(0x2ec0, addmod(mload(0x2e20), mload(0x2e80), f_q))
{
            let result := mulmod(mload(0x640), mload(0x2360), f_q)
mstore(12000, result)
        }
mstore(0x2f00, mulmod(mload(0x2ee0), mload(0x2820), f_q))
mstore(0x2f20, mulmod(sub(f_q, mload(0x2f00)), mload(0x2860), f_q))
mstore(0x2f40, mulmod(mload(0x2d00), mload(0x2860), f_q))
mstore(0x2f60, addmod(mload(0x2ec0), mload(0x2f20), f_q))
{
            let result := mulmod(mload(0x660), mload(0x2360), f_q)
mstore(12160, result)
        }
mstore(0x2fa0, mulmod(mload(0x2f80), mload(0x2820), f_q))
mstore(0x2fc0, mulmod(sub(f_q, mload(0x2fa0)), mload(0x2880), f_q))
mstore(0x2fe0, mulmod(mload(0x2d00), mload(0x2880), f_q))
mstore(0x3000, addmod(mload(0x2f60), mload(0x2fc0), f_q))
{
            let result := mulmod(mload(0x6a0), mload(0x2360), f_q)
mstore(12320, result)
        }
mstore(0x3040, mulmod(mload(0x3020), mload(0x2820), f_q))
mstore(0x3060, mulmod(sub(f_q, mload(0x3040)), mload(0x28a0), f_q))
mstore(0x3080, mulmod(mload(0x2d00), mload(0x28a0), f_q))
mstore(0x30a0, addmod(mload(0x3000), mload(0x3060), f_q))
{
            let result := mulmod(mload(0x6c0), mload(0x2360), f_q)
mstore(12480, result)
        }
mstore(0x30e0, mulmod(mload(0x30c0), mload(0x2820), f_q))
mstore(0x3100, mulmod(sub(f_q, mload(0x30e0)), mload(0x28c0), f_q))
mstore(0x3120, mulmod(mload(0x2d00), mload(0x28c0), f_q))
mstore(0x3140, addmod(mload(0x30a0), mload(0x3100), f_q))
{
            let result := mulmod(mload(0x6e0), mload(0x2360), f_q)
mstore(12640, result)
        }
mstore(0x3180, mulmod(mload(0x3160), mload(0x2820), f_q))
mstore(0x31a0, mulmod(sub(f_q, mload(0x3180)), mload(0x28e0), f_q))
mstore(0x31c0, mulmod(mload(0x2d00), mload(0x28e0), f_q))
mstore(0x31e0, addmod(mload(0x3140), mload(0x31a0), f_q))
mstore(0x3200, mulmod(mload(0x1dc0), mload(0x2660), f_q))
mstore(0x3220, mulmod(mload(0x1de0), mload(0x2660), f_q))
mstore(0x3240, mulmod(mload(0x1e00), mload(0x2660), f_q))
{
            let result := mulmod(mload(0x1e20), mload(0x2360), f_q)
mstore(12896, result)
        }
mstore(0x3280, mulmod(mload(0x3260), mload(0x2820), f_q))
mstore(0x32a0, mulmod(sub(f_q, mload(0x3280)), mload(0x2900), f_q))
mstore(0x32c0, mulmod(mload(0x2d00), mload(0x2900), f_q))
mstore(0x32e0, mulmod(mload(0x3200), mload(0x2900), f_q))
mstore(0x3300, mulmod(mload(0x3220), mload(0x2900), f_q))
mstore(0x3320, mulmod(mload(0x3240), mload(0x2900), f_q))
mstore(0x3340, addmod(mload(0x31e0), mload(0x32a0), f_q))
{
            let result := mulmod(mload(0x680), mload(0x2360), f_q)
mstore(13152, result)
        }
mstore(0x3380, mulmod(mload(0x3360), mload(0x2820), f_q))
mstore(0x33a0, mulmod(sub(f_q, mload(0x3380)), mload(0x2920), f_q))
mstore(0x33c0, mulmod(mload(0x2d00), mload(0x2920), f_q))
mstore(0x33e0, addmod(mload(0x3340), mload(0x33a0), f_q))
mstore(0x3400, mulmod(mload(0x33e0), mload(0x2980), f_q))
mstore(0x3420, mulmod(mload(0x2d80), mload(0x2980), f_q))
mstore(0x3440, mulmod(mload(0x2e00), mload(0x2980), f_q))
mstore(0x3460, mulmod(mload(0x2ea0), mload(0x2980), f_q))
mstore(0x3480, mulmod(mload(0x2f40), mload(0x2980), f_q))
mstore(0x34a0, mulmod(mload(0x2fe0), mload(0x2980), f_q))
mstore(0x34c0, mulmod(mload(0x3080), mload(0x2980), f_q))
mstore(0x34e0, mulmod(mload(0x3120), mload(0x2980), f_q))
mstore(0x3500, mulmod(mload(0x31c0), mload(0x2980), f_q))
mstore(0x3520, mulmod(mload(0x32c0), mload(0x2980), f_q))
mstore(0x3540, mulmod(mload(0x32e0), mload(0x2980), f_q))
mstore(0x3560, mulmod(mload(0x3300), mload(0x2980), f_q))
mstore(0x3580, mulmod(mload(0x3320), mload(0x2980), f_q))
mstore(0x35a0, mulmod(mload(0x33c0), mload(0x2980), f_q))
mstore(0x35c0, addmod(mload(0x2ce0), mload(0x3400), f_q))
mstore(0x35e0, mulmod(1, mload(0x21a0), f_q))
mstore(0x3600, mulmod(1, mload(0x900), f_q))
mstore(0x3620, 0x0000000000000000000000000000000000000000000000000000000000000001)
                    mstore(0x3640, 0x0000000000000000000000000000000000000000000000000000000000000002)
mstore(0x3660, mload(0x35c0))
success := and(eq(staticcall(gas(), 0x7, 0x3620, 0x60, 0x3620, 0x40), 1), success)
mstore(0x3680, mload(0x3620))
                    mstore(0x36a0, mload(0x3640))
mstore(0x36c0, mload(0x120))
                    mstore(0x36e0, mload(0x140))
success := and(eq(staticcall(gas(), 0x6, 0x3680, 0x80, 0x3680, 0x40), 1), success)
mstore(0x3700, mload(0x300))
                    mstore(0x3720, mload(0x320))
mstore(0x3740, mload(0x2ba0))
success := and(eq(staticcall(gas(), 0x7, 0x3700, 0x60, 0x3700, 0x40), 1), success)
mstore(0x3760, mload(0x3680))
                    mstore(0x3780, mload(0x36a0))
mstore(0x37a0, mload(0x3700))
                    mstore(0x37c0, mload(0x3720))
success := and(eq(staticcall(gas(), 0x6, 0x3760, 0x80, 0x3760, 0x40), 1), success)
mstore(0x37e0, mload(0x340))
                    mstore(0x3800, mload(0x360))
mstore(0x3820, mload(0x2bc0))
success := and(eq(staticcall(gas(), 0x7, 0x37e0, 0x60, 0x37e0, 0x40), 1), success)
mstore(0x3840, mload(0x3760))
                    mstore(0x3860, mload(0x3780))
mstore(0x3880, mload(0x37e0))
                    mstore(0x38a0, mload(0x3800))
success := and(eq(staticcall(gas(), 0x6, 0x3840, 0x80, 0x3840, 0x40), 1), success)
mstore(0x38c0, mload(0x1c0))
                    mstore(0x38e0, mload(0x1e0))
mstore(0x3900, mload(0x2cc0))
success := and(eq(staticcall(gas(), 0x7, 0x38c0, 0x60, 0x38c0, 0x40), 1), success)
mstore(0x3920, mload(0x3840))
                    mstore(0x3940, mload(0x3860))
mstore(0x3960, mload(0x38c0))
                    mstore(0x3980, mload(0x38e0))
success := and(eq(staticcall(gas(), 0x6, 0x3920, 0x80, 0x3920, 0x40), 1), success)
mstore(0x39a0, mload(0x200))
                    mstore(0x39c0, mload(0x220))
mstore(0x39e0, mload(0x3420))
success := and(eq(staticcall(gas(), 0x7, 0x39a0, 0x60, 0x39a0, 0x40), 1), success)
mstore(0x3a00, mload(0x3920))
                    mstore(0x3a20, mload(0x3940))
mstore(0x3a40, mload(0x39a0))
                    mstore(0x3a60, mload(0x39c0))
success := and(eq(staticcall(gas(), 0x6, 0x3a00, 0x80, 0x3a00, 0x40), 1), success)
mstore(0x3a80, 0x220bd1ac082a64b02cc0523d637f22ca3704c7ec1d776d9e0118dbd7555c435f)
                    mstore(0x3aa0, 0x0536208018b5b32f9c59e902f70d452ea1844c9d556bcc471689c72c0283b04a)
mstore(0x3ac0, mload(0x3440))
success := and(eq(staticcall(gas(), 0x7, 0x3a80, 0x60, 0x3a80, 0x40), 1), success)
mstore(0x3ae0, mload(0x3a00))
                    mstore(0x3b00, mload(0x3a20))
mstore(0x3b20, mload(0x3a80))
                    mstore(0x3b40, mload(0x3aa0))
success := and(eq(staticcall(gas(), 0x6, 0x3ae0, 0x80, 0x3ae0, 0x40), 1), success)
mstore(0x3b60, 0x0c8564ccdedaa665e2a6d7a62df66d301f768431696539a7a83c8b0945597d51)
                    mstore(0x3b80, 0x0967706cd514e5b24c84c61b14bf7cdec62bd7439e2082bfcd7da8ce699892d0)
mstore(0x3ba0, mload(0x3460))
success := and(eq(staticcall(gas(), 0x7, 0x3b60, 0x60, 0x3b60, 0x40), 1), success)
mstore(0x3bc0, mload(0x3ae0))
                    mstore(0x3be0, mload(0x3b00))
mstore(0x3c00, mload(0x3b60))
                    mstore(0x3c20, mload(0x3b80))
success := and(eq(staticcall(gas(), 0x6, 0x3bc0, 0x80, 0x3bc0, 0x40), 1), success)
mstore(0x3c40, 0x05026454e438efd95332b6aef358af9d0a2512c3fec031fb32ed4c0733c7a159)
                    mstore(0x3c60, 0x0295f18fe667aa5d0ac71264fa000fbd269f141b06bbdb90f451e771558ebf54)
mstore(0x3c80, mload(0x3480))
success := and(eq(staticcall(gas(), 0x7, 0x3c40, 0x60, 0x3c40, 0x40), 1), success)
mstore(0x3ca0, mload(0x3bc0))
                    mstore(0x3cc0, mload(0x3be0))
mstore(0x3ce0, mload(0x3c40))
                    mstore(0x3d00, mload(0x3c60))
success := and(eq(staticcall(gas(), 0x6, 0x3ca0, 0x80, 0x3ca0, 0x40), 1), success)
mstore(0x3d20, 0x16e35b1e6e9aadac7a76e772e9f6e26e19a9bf3e15132e40562daf40e738ffe8)
                    mstore(0x3d40, 0x10573160e2cd71549a935ca7a69e5bbe279fd2030becc3cd147bd6b70198b842)
mstore(0x3d60, mload(0x34a0))
success := and(eq(staticcall(gas(), 0x7, 0x3d20, 0x60, 0x3d20, 0x40), 1), success)
mstore(0x3d80, mload(0x3ca0))
                    mstore(0x3da0, mload(0x3cc0))
mstore(0x3dc0, mload(0x3d20))
                    mstore(0x3de0, mload(0x3d40))
success := and(eq(staticcall(gas(), 0x6, 0x3d80, 0x80, 0x3d80, 0x40), 1), success)
mstore(0x3e00, 0x16ba3ced29683ba28d0c1540e084f74e2bcc3a72d9ee4e38c46889faab004f3c)
                    mstore(0x3e20, 0x27637a019d9541e1cc506963bd77a5bcbced4a919ebfd930d0daee79c6312cab)
mstore(0x3e40, mload(0x34c0))
success := and(eq(staticcall(gas(), 0x7, 0x3e00, 0x60, 0x3e00, 0x40), 1), success)
mstore(0x3e60, mload(0x3d80))
                    mstore(0x3e80, mload(0x3da0))
mstore(0x3ea0, mload(0x3e00))
                    mstore(0x3ec0, mload(0x3e20))
success := and(eq(staticcall(gas(), 0x6, 0x3e60, 0x80, 0x3e60, 0x40), 1), success)
mstore(0x3ee0, 0x147f1b4b59b6c09a666e916f2826e753c8d8f736b7dc56638cbd9fff86f64142)
                    mstore(0x3f00, 0x1595343d09f76ea74c7041df68208597c2251ceff020bccd8feb141fb798d41f)
mstore(0x3f20, mload(0x34e0))
success := and(eq(staticcall(gas(), 0x7, 0x3ee0, 0x60, 0x3ee0, 0x40), 1), success)
mstore(0x3f40, mload(0x3e60))
                    mstore(0x3f60, mload(0x3e80))
mstore(0x3f80, mload(0x3ee0))
                    mstore(0x3fa0, mload(0x3f00))
success := and(eq(staticcall(gas(), 0x6, 0x3f40, 0x80, 0x3f40, 0x40), 1), success)
mstore(0x3fc0, 0x21197f4ba3fc1d3ef544574f87341d2f3f9ac3e3384127eb77a10264a123823f)
                    mstore(0x3fe0, 0x12d388d95e12bad0e26ff920aac33f19165eb375c17ca5dfa0a4921212173656)
mstore(0x4000, mload(0x3500))
success := and(eq(staticcall(gas(), 0x7, 0x3fc0, 0x60, 0x3fc0, 0x40), 1), success)
mstore(0x4020, mload(0x3f40))
                    mstore(0x4040, mload(0x3f60))
mstore(0x4060, mload(0x3fc0))
                    mstore(0x4080, mload(0x3fe0))
success := and(eq(staticcall(gas(), 0x6, 0x4020, 0x80, 0x4020, 0x40), 1), success)
mstore(0x40a0, mload(0x420))
                    mstore(0x40c0, mload(0x440))
mstore(0x40e0, mload(0x3520))
success := and(eq(staticcall(gas(), 0x7, 0x40a0, 0x60, 0x40a0, 0x40), 1), success)
mstore(0x4100, mload(0x4020))
                    mstore(0x4120, mload(0x4040))
mstore(0x4140, mload(0x40a0))
                    mstore(0x4160, mload(0x40c0))
success := and(eq(staticcall(gas(), 0x6, 0x4100, 0x80, 0x4100, 0x40), 1), success)
mstore(0x4180, mload(0x460))
                    mstore(0x41a0, mload(0x480))
mstore(0x41c0, mload(0x3540))
success := and(eq(staticcall(gas(), 0x7, 0x4180, 0x60, 0x4180, 0x40), 1), success)
mstore(0x41e0, mload(0x4100))
                    mstore(0x4200, mload(0x4120))
mstore(0x4220, mload(0x4180))
                    mstore(0x4240, mload(0x41a0))
success := and(eq(staticcall(gas(), 0x6, 0x41e0, 0x80, 0x41e0, 0x40), 1), success)
mstore(0x4260, mload(0x4a0))
                    mstore(0x4280, mload(0x4c0))
mstore(0x42a0, mload(0x3560))
success := and(eq(staticcall(gas(), 0x7, 0x4260, 0x60, 0x4260, 0x40), 1), success)
mstore(0x42c0, mload(0x41e0))
                    mstore(0x42e0, mload(0x4200))
mstore(0x4300, mload(0x4260))
                    mstore(0x4320, mload(0x4280))
success := and(eq(staticcall(gas(), 0x6, 0x42c0, 0x80, 0x42c0, 0x40), 1), success)
mstore(0x4340, mload(0x4e0))
                    mstore(0x4360, mload(0x500))
mstore(0x4380, mload(0x3580))
success := and(eq(staticcall(gas(), 0x7, 0x4340, 0x60, 0x4340, 0x40), 1), success)
mstore(0x43a0, mload(0x42c0))
                    mstore(0x43c0, mload(0x42e0))
mstore(0x43e0, mload(0x4340))
                    mstore(0x4400, mload(0x4360))
success := and(eq(staticcall(gas(), 0x6, 0x43a0, 0x80, 0x43a0, 0x40), 1), success)
mstore(0x4420, mload(0x380))
                    mstore(0x4440, mload(0x3a0))
mstore(0x4460, mload(0x35a0))
success := and(eq(staticcall(gas(), 0x7, 0x4420, 0x60, 0x4420, 0x40), 1), success)
mstore(0x4480, mload(0x43a0))
                    mstore(0x44a0, mload(0x43c0))
mstore(0x44c0, mload(0x4420))
                    mstore(0x44e0, mload(0x4440))
success := and(eq(staticcall(gas(), 0x6, 0x4480, 0x80, 0x4480, 0x40), 1), success)
mstore(0x4500, mload(0x8a0))
                    mstore(0x4520, mload(0x8c0))
mstore(0x4540, sub(f_q, mload(0x35e0)))
success := and(eq(staticcall(gas(), 0x7, 0x4500, 0x60, 0x4500, 0x40), 1), success)
mstore(0x4560, mload(0x4480))
                    mstore(0x4580, mload(0x44a0))
mstore(0x45a0, mload(0x4500))
                    mstore(0x45c0, mload(0x4520))
success := and(eq(staticcall(gas(), 0x6, 0x4560, 0x80, 0x4560, 0x40), 1), success)
mstore(0x45e0, mload(0x940))
                    mstore(0x4600, mload(0x960))
mstore(0x4620, mload(0x3600))
success := and(eq(staticcall(gas(), 0x7, 0x45e0, 0x60, 0x45e0, 0x40), 1), success)
mstore(0x4640, mload(0x4560))
                    mstore(0x4660, mload(0x4580))
mstore(0x4680, mload(0x45e0))
                    mstore(0x46a0, mload(0x4600))
success := and(eq(staticcall(gas(), 0x6, 0x4640, 0x80, 0x4640, 0x40), 1), success)
mstore(0x46c0, mload(0x4640))
                    mstore(0x46e0, mload(0x4660))
mstore(0x4700, 0x198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c2)
            mstore(0x4720, 0x1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed)
            mstore(0x4740, 0x090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b)
            mstore(0x4760, 0x12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa)
mstore(0x4780, mload(0x940))
                    mstore(0x47a0, mload(0x960))
mstore(0x47c0, 0x17cc93077f56f654da727c1def86010339c2b4131094547285adb083e48c197b)
            mstore(0x47e0, 0x285b1f14edd7e6632340a37dfae9005ff762edcfecfe1c732a7474c0708bef80)
            mstore(0x4800, 0x0ec56ea3f31a7c4b5100ea8711a5ee83b453955652ed813695efb84f0ad28e6e)
            mstore(0x4820, 0x04b6b43b964556568e63decd8c5061d88e50364110657e7575452e3b3c9e7d77)
success := and(eq(staticcall(gas(), 0x8, 0x46c0, 0x180, 0x46c0, 0x20), 1), success)
success := and(eq(mload(0x46c0), 1), success)

            // Revert if anything fails
            if iszero(success) { revert(0, 0) }

            // Return empty bytes on success
            return(0, 0)

        }
    }
}
        