// ⚠️ AUTO-GENERATED by `gen-production-verifier --emit` from the REAL
// zkmist_circuits::ZKMistV2Claim circuit. Do not edit by hand.
// VK validity is gated on the pinned PSE KZG SRS (KZG_SRS_SHA256 in
// cli/src/constants.rs); confirm via DEPLOYMENT.md Phase 3-4 before
// deploying.

// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

contract Halo2VerifyingKey {
    constructor() {
        assembly {
            mstore(0x0000, 0x133adf5289091bd5b7a39300e21115f0336d7d098332fadbb9685f8bb6ecd045) // vk_digest
            mstore(0x0020, 0x0000000000000000000000000000000000000000000000000000000000000003) // num_instances
            mstore(0x0040, 0x0000000000000000000000000000000000000000000000000000000000000017) // k
            mstore(0x0060, 0x30644e121894ba67550ff245e0f5eb5a25832df811e8df9dd100d30c2c14d821) // n_inv
            mstore(0x0080, 0x1283ba6f4b7b1a76ba2008fe823128bea4adb9269cbfd7c41c223be65bc60863) // omega
            mstore(0x00a0, 0x1589862c1cf3f8b59954774980cc9361c568bcabd9cb7d0858de685794d4772b) // omega_inv
            mstore(0x00c0, 0x2fffa2b50d66f628412d9782f09d3386d766a1168304babe2165fe7ec962e65b) // omega_inv_to_l
            mstore(0x00e0, 0x0000000000000000000000000000000000000000000000000000000000000000) // has_accumulator
            mstore(0x0100, 0x0000000000000000000000000000000000000000000000000000000000000000) // acc_offset
            mstore(0x0120, 0x0000000000000000000000000000000000000000000000000000000000000000) // num_acc_limbs
            mstore(0x0140, 0x0000000000000000000000000000000000000000000000000000000000000000) // num_acc_limb_bits
            mstore(0x0160, 0x0000000000000000000000000000000000000000000000000000000000000001) // g1_x
            mstore(0x0180, 0x0000000000000000000000000000000000000000000000000000000000000002) // g1_y
            mstore(0x01a0, 0x198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c2) // g2_x_1
            mstore(0x01c0, 0x1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed) // g2_x_2
            mstore(0x01e0, 0x090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b) // g2_y_1
            mstore(0x0200, 0x12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa) // g2_y_2
            mstore(0x0220, 0x17cc93077f56f654da727c1def86010339c2b4131094547285adb083e48c197b) // neg_s_g2_x_1
            mstore(0x0240, 0x285b1f14edd7e6632340a37dfae9005ff762edcfecfe1c732a7474c0708bef80) // neg_s_g2_x_2
            mstore(0x0260, 0x0ec56ea3f31a7c4b5100ea8711a5ee83b453955652ed813695efb84f0ad28e6e) // neg_s_g2_y_1
            mstore(0x0280, 0x04b6b43b964556568e63decd8c5061d88e50364110657e7575452e3b3c9e7d77) // neg_s_g2_y_2
            mstore(0x02a0, 0x14e7640e3860e7d72701e5d45eb9148328dadb218e5593ef3da7ecb030cb3afc) // fixed_comms[0].x
            mstore(0x02c0, 0x29285f0882ca8b9da45b43dc2a44dd90e9b400d4653b45aec8edbb65c3c42144) // fixed_comms[0].y
            mstore(0x02e0, 0x12980e38f639b3fd64881c7096dc7d5c51dd597fabd072f7d400409cf8404f53) // fixed_comms[1].x
            mstore(0x0300, 0x25aa54b3b9eebb84dde32bde8255168e85757385608502e32bc0d33c9a43d721) // fixed_comms[1].y
            mstore(0x0320, 0x0c8564ccdedaa665e2a6d7a62df66d301f768431696539a7a83c8b0945597d51) // fixed_comms[2].x
            mstore(0x0340, 0x0967706cd514e5b24c84c61b14bf7cdec62bd7439e2082bfcd7da8ce699892d0) // fixed_comms[2].y
            mstore(0x0360, 0x1459315a280ea0b2311551ab2150cac20fcb10224a7c3950717d5dc0596c2af4) // fixed_comms[3].x
            mstore(0x0380, 0x19635f4d68fa1589027ac288c90abe004fbe2a91b5919adf7d960b4a8d5bc764) // fixed_comms[3].y
            mstore(0x03a0, 0x0c8564ccdedaa665e2a6d7a62df66d301f768431696539a7a83c8b0945597d51) // fixed_comms[4].x
            mstore(0x03c0, 0x0967706cd514e5b24c84c61b14bf7cdec62bd7439e2082bfcd7da8ce699892d0) // fixed_comms[4].y
            mstore(0x03e0, 0x03c502461a4599ba66816d67b02eff687d6d35553a1e8d075d92c8aa3de938ee) // fixed_comms[5].x
            mstore(0x0400, 0x2d388e0c57849a53c5441b828383ff52d4013428fe65e9748ec1268882c02608) // fixed_comms[5].y
            mstore(0x0420, 0x0000000000000000000000000000000000000000000000000000000000000000) // fixed_comms[6].x
            mstore(0x0440, 0x0000000000000000000000000000000000000000000000000000000000000000) // fixed_comms[6].y
            mstore(0x0460, 0x0000000000000000000000000000000000000000000000000000000000000000) // fixed_comms[7].x
            mstore(0x0480, 0x0000000000000000000000000000000000000000000000000000000000000000) // fixed_comms[7].y
            mstore(0x04a0, 0x25a060c3f68546a206d9509d7c20935c73af700006872ea1902dffb1d9eb7713) // fixed_comms[8].x
            mstore(0x04c0, 0x12614935b6d67420f7e99a8b3a570c95520ae24e7e3c09cde7e32d9a62290582) // fixed_comms[8].y
            mstore(0x04e0, 0x030dde74b0f382668c3c08adb5080f1062daf1b90889693900ed3a033124dcbc) // fixed_comms[9].x
            mstore(0x0500, 0x07d1fde019d78df1506c9336d8e5cda2aceb10b527dedc41f7c4ea4eee37a07f) // fixed_comms[9].y
            mstore(0x0520, 0x1b17ae224077d95d425a420626b9564d13a97ed339600ed18451139d8159525f) // fixed_comms[10].x
            mstore(0x0540, 0x139c565b05075c69d701c435e0e633748ecd38bba955845347df5443315b61dc) // fixed_comms[10].y
            mstore(0x0560, 0x2079bdfb58cd922ff665efd430ba3560a5d92615164684e4879cacd7e1394c3d) // fixed_comms[11].x
            mstore(0x0580, 0x11f9f30397dfb0ab70e9ab51dc9f08326ad9dfdc5236bacf639acfdf29015dbf) // fixed_comms[11].y
            mstore(0x05a0, 0x0726a5e8b1c9809776af327e595e084fd37ddb916d20638a81da120ba9c1e887) // fixed_comms[12].x
            mstore(0x05c0, 0x1170763465691a824c7d9c216c20484f485c81cf0d6a357df579e8c2716348ff) // fixed_comms[12].y
            mstore(0x05e0, 0x1b7a815612b8393a2247e95a9d693a86e99fa98109f2193f911e3c322955d74b) // fixed_comms[13].x
            mstore(0x0600, 0x19b4285d7a9c7f763c8ea2ef520cd847ad959f520230e576a8ab032ee19e1ce1) // fixed_comms[13].y
            mstore(0x0620, 0x10c1d641f156270ef400ae4f8ced76bb426db86dee1ebc69c0a4cb30c1528af4) // fixed_comms[14].x
            mstore(0x0640, 0x02006a2c078df14596b1492f7aaf5c87e8deb615b23c256fa0aeca56806dda7c) // fixed_comms[14].y
            mstore(0x0660, 0x00839980757f588635804265913a85b5b0793fc6b477a6041760bf545d28e1b0) // fixed_comms[15].x
            mstore(0x0680, 0x247f2670836e23cf114808aa85530579d853901310d3b2b7b6e40731485936cf) // fixed_comms[15].y
            mstore(0x06a0, 0x0b31f79a249c0a7e52a40edf8c5fc03644377d910fdd3522b92f2627be996d37) // fixed_comms[16].x
            mstore(0x06c0, 0x0da86c7a5e58c6128dc4452512071e10339963979d901fdebd82c6077bbfccd8) // fixed_comms[16].y
            mstore(0x06e0, 0x10d96548388ce62956b387889b38a66878e8716ea17f6ba8e3b3de8fc7ad0de9) // permutation_comms[0].x
            mstore(0x0700, 0x1f333886d1dce84b04e3c38fc7ca4a4f5b1659212091f6910145b1534feae77a) // permutation_comms[0].y
            mstore(0x0720, 0x2a3e63109eb2c9362ff7b48201848e864844df5af6a5c5d69c219b492faef155) // permutation_comms[1].x
            mstore(0x0740, 0x2eeaa32131743eae850644d96bf2dd2e476054def62197e879cab4c0111e2803) // permutation_comms[1].y
            mstore(0x0760, 0x05dfb8883a751fba48a506b2463773f6b83ab2f21b3b2abe3632da72b7d6339c) // permutation_comms[2].x
            mstore(0x0780, 0x2be3176c20e2d58561196d3946f00e02fffb5a9531cdf36edb1efbc5f9732f5e) // permutation_comms[2].y
            mstore(0x07a0, 0x06e6592d27c18e4e9a56e03fab4e6d9bd04579b9803ad31bed2187c4583ee79f) // permutation_comms[3].x
            mstore(0x07c0, 0x1afc444f6736f8cd613957885276a2a337064e3315f19e3585dac2b346977af6) // permutation_comms[3].y
            mstore(0x07e0, 0x06811fa76ab509211cf7f5ff10ea606d1a92e0f7c5b7fcd0f22978a6ab5cc817) // permutation_comms[4].x
            mstore(0x0800, 0x1ed990cdb150ada0dfff649c261925969bdc03b451104fb6d25771e306f579e2) // permutation_comms[4].y
            mstore(0x0820, 0x2862ba5b4db9b690f0ce8087fc2a18b85066b723bf1a7a0f48be9352aba9ff97) // permutation_comms[5].x
            mstore(0x0840, 0x2480f0b71fa80b328f17ba29dccb867a1a47c9db029cf1468858002f458256a5) // permutation_comms[5].y
            mstore(0x0860, 0x246356c96a6949ec85cfccb848129fa6624b607a193880a84a595ea37109bcd4) // permutation_comms[6].x
            mstore(0x0880, 0x20b8df2017ca5187b56b1cf56fac2f4db4cb34ac95dd903fe09861f255b606a5) // permutation_comms[6].y
            mstore(0x08a0, 0x1e8b8ffc07a8a61bf2aa9bc0e9bb795c8faa315a4d7d4d2ef6f6f0148715523f) // permutation_comms[7].x
            mstore(0x08c0, 0x028357d4c1832cc35ef73f0179218a63a3b52641390c40bd710c7ee83ec192a2) // permutation_comms[7].y
            mstore(0x08e0, 0x0a6c300f2dad94da8651d5bcd3d34fc7a841551c3cfc587143059a02399d44b0) // permutation_comms[8].x
            mstore(0x0900, 0x2c9050825c5845b7478c64dd8c02d05cfb3c89523ca701c98e88ee92c435a186) // permutation_comms[8].y
            mstore(0x0920, 0x1b015f0cc126b1768e242d97ffb8acd335602ca95904448d8ef5599ef06eaa8a) // permutation_comms[9].x
            mstore(0x0940, 0x3044b55cb8fac905b025ba0f5c79d2121f0561b5d6464e59ecd8d1870ba5f80d) // permutation_comms[9].y
            mstore(0x0960, 0x294c7219491f0b38f942f647e6e683e12eceecc861bb574fa9c442c73d3997d1) // permutation_comms[10].x
            mstore(0x0980, 0x2a032342198785b695df755c95e8186a2eb61e56882422785bc0657587d5b718) // permutation_comms[10].y
            mstore(0x09a0, 0x067a2c5107554bf07b9775ec05cb6d2a2d19933d26804a068f3bdd3ec5a9af87) // permutation_comms[11].x
            mstore(0x09c0, 0x1787eaff270d298c09f8d182acfc44654832187652d8df1bcd8574ab9b1245c0) // permutation_comms[11].y
            mstore(0x09e0, 0x2f0f7f8bafc1f288c97d53c44425d5e51ba2226fc43090abd3eac658d6fec5d0) // permutation_comms[12].x
            mstore(0x0a00, 0x30335685a8ec8433d6e0570bec31a2a4a440e2f924bc639719a22a1cf0500d9b) // permutation_comms[12].y
            mstore(0x0a20, 0x226bdcebca545f95038095a66f6aa7ef90fd8c353b7284290249db63a7d5649e) // permutation_comms[13].x
            mstore(0x0a40, 0x08222767081cf27e7c1da43648103d664124c0c68e3f74c40ff73347db037aa2) // permutation_comms[13].y
            mstore(0x0a60, 0x1928e155723ba3ca74dcfc0a70aab295382ce8791ce303b915c88522fc945f7c) // permutation_comms[14].x
            mstore(0x0a80, 0x1bc736b20ccd92b10dd7aaabd1fadb81929bf5ac0ba178c5fc4956202491bb5e) // permutation_comms[14].y
            mstore(0x0aa0, 0x1eb8bb5cbf8e6f2e30037f7188e7d0fb05cf9570407beac696ad093d460d2088) // permutation_comms[15].x
            mstore(0x0ac0, 0x1c0daed9a733bdb720f44b8af26b83fd6883f00656da720820821815cd6b1521) // permutation_comms[15].y
            mstore(0x0ae0, 0x0e4a394c8035cf8bc20d4f1d963fa90cdb11a3a117091387589bb3d917bbeda0) // permutation_comms[16].x
            mstore(0x0b00, 0x17b356c895ec4862e4c4d23099c3706c37458884570c71275eee4c01d353b076) // permutation_comms[16].y
            mstore(0x0b20, 0x1bbf0a46644fea1c2e3f58825b286ebadd030a1ebc2d9f18d21c695fc5dfa5b5) // permutation_comms[17].x
            mstore(0x0b40, 0x1d0bce84d94afe177bd36c45a936614e271fdd0aaf831cf7bea790e4334dc3cd) // permutation_comms[17].y
            mstore(0x0b60, 0x1c31d472e84c937ffa9d4ddd1ede91ed1f210d84e15b29640db0c897ff1a9d41) // permutation_comms[18].x
            mstore(0x0b80, 0x08c3d67a2c21e0ac0464ec7d9ea2322bd860f9f25a3d51358bc307fb95a2fad6) // permutation_comms[18].y
            mstore(0x0ba0, 0x1eac1491087efdbe3b5ffa533e176d0656d4d9104d66c33e5e2d2b7f234e318b) // permutation_comms[19].x
            mstore(0x0bc0, 0x116dcae4a76fbb01df0e7a74765562ac1d5489c11755f3e99b37c5eadd6609d9) // permutation_comms[19].y
            mstore(0x0be0, 0x2f1bf5c8cfda7394b58d1b3f869e65bf5a4996cf04a6a3bf746cef1699b2941b) // permutation_comms[20].x
            mstore(0x0c00, 0x113734b209683677d362a76ca9723b444288a652facbf3d27f58930dbd965035) // permutation_comms[20].y

            return(0, 0x0c20)
        }
    }
}
