
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.19;

/// @dev ⚠️ PINNED-SRS VERIFIER — generated against the file pinned by
///      `KZG_SRS_SHA256` (currently ~/.zkmist/cache/v2_params_k23.bin, derived
///      from ppot_0080_23.ptau). A proof verifies here iff the prover
///      transcript/instances/VK are wired correctly. Soundness (non-forgeability)
///      additionally requires that the pinned file's digest be cross-referenced
///      against the PSE ceremony's published records (docs/kzg-srs.md §2.2) —
///      that EXTERNAL provenance step is NOT yet done; do not deploy to mainnet
///      until it is. Generated by circuits/tests/claim_evm_roundtrip.rs
///      (ZKMIST_EMIT_VERIFIER + ZKMIST_USE_PINNED_SRS).
contract Halo2Verifier {
    fallback(bytes calldata) external returns (bytes memory) {
        assembly ("memory-safe") {
            // Enforce that Solidity memory layout is respected
            let data := mload(0x40)
            if iszero(eq(data, 0x80)) {
                revert(0, 0)
            }

            let success := true
            let f_p := 0x30644e72e131a029b85045b68181585d97816a916871ca8d3c208c16d87cfd47
            let f_q := 0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000001
            function validate_ec_point(x, y) -> valid {
                {
                    let x_lt_p := lt(x, 0x30644e72e131a029b85045b68181585d97816a916871ca8d3c208c16d87cfd47)
                    let y_lt_p := lt(y, 0x30644e72e131a029b85045b68181585d97816a916871ca8d3c208c16d87cfd47)
                    valid := and(x_lt_p, y_lt_p)
                }
                {
                    let y_square := mulmod(y, y, 0x30644e72e131a029b85045b68181585d97816a916871ca8d3c208c16d87cfd47)
                    let x_square := mulmod(x, x, 0x30644e72e131a029b85045b68181585d97816a916871ca8d3c208c16d87cfd47)
                    let x_cube := mulmod(x_square, x, 0x30644e72e131a029b85045b68181585d97816a916871ca8d3c208c16d87cfd47)
                    let x_cube_plus_3 := addmod(x_cube, 3, 0x30644e72e131a029b85045b68181585d97816a916871ca8d3c208c16d87cfd47)
                    let is_affine := eq(x_cube_plus_3, y_square)
                    valid := and(valid, is_affine)
                }
            }
            mstore(0xa0, mod(calldataload(0x0), f_q))
mstore(0xc0, mod(calldataload(0x20), f_q))
mstore(0xe0, mod(calldataload(0x40), f_q))
mstore(0x80, 7946391449778485752496101695552140919620727635781241947992880356117364063854)

        {
            let x := calldataload(0x60)
            mstore(0x100, x)
            let y := calldataload(0x80)
            mstore(0x120, y)
            success := and(validate_ec_point(x, y), success)
        }
mstore(0x140, keccak256(0x80, 192))
{
            let hash := mload(0x140)
            mstore(0x160, mod(hash, f_q))
            mstore(0x180, hash)
        }

        {
            let x := calldataload(0xa0)
            mstore(0x1a0, x)
            let y := calldataload(0xc0)
            mstore(0x1c0, y)
            success := and(validate_ec_point(x, y), success)
        }

        {
            let x := calldataload(0xe0)
            mstore(0x1e0, x)
            let y := calldataload(0x100)
            mstore(0x200, y)
            success := and(validate_ec_point(x, y), success)
        }
mstore(0x220, keccak256(0x180, 160))
{
            let hash := mload(0x220)
            mstore(0x240, mod(hash, f_q))
            mstore(0x260, hash)
        }
mstore8(640, 1)
mstore(0x280, keccak256(0x260, 33))
{
            let hash := mload(0x280)
            mstore(0x2a0, mod(hash, f_q))
            mstore(0x2c0, hash)
        }

        {
            let x := calldataload(0x120)
            mstore(0x2e0, x)
            let y := calldataload(0x140)
            mstore(0x300, y)
            success := and(validate_ec_point(x, y), success)
        }

        {
            let x := calldataload(0x160)
            mstore(0x320, x)
            let y := calldataload(0x180)
            mstore(0x340, y)
            success := and(validate_ec_point(x, y), success)
        }

        {
            let x := calldataload(0x1a0)
            mstore(0x360, x)
            let y := calldataload(0x1c0)
            mstore(0x380, y)
            success := and(validate_ec_point(x, y), success)
        }
mstore(0x3a0, keccak256(0x2c0, 224))
{
            let hash := mload(0x3a0)
            mstore(0x3c0, mod(hash, f_q))
            mstore(0x3e0, hash)
        }

        {
            let x := calldataload(0x1e0)
            mstore(0x400, x)
            let y := calldataload(0x200)
            mstore(0x420, y)
            success := and(validate_ec_point(x, y), success)
        }

        {
            let x := calldataload(0x220)
            mstore(0x440, x)
            let y := calldataload(0x240)
            mstore(0x460, y)
            success := and(validate_ec_point(x, y), success)
        }

        {
            let x := calldataload(0x260)
            mstore(0x480, x)
            let y := calldataload(0x280)
            mstore(0x4a0, y)
            success := and(validate_ec_point(x, y), success)
        }

        {
            let x := calldataload(0x2a0)
            mstore(0x4c0, x)
            let y := calldataload(0x2c0)
            mstore(0x4e0, y)
            success := and(validate_ec_point(x, y), success)
        }
mstore(0x500, keccak256(0x3e0, 288))
{
            let hash := mload(0x500)
            mstore(0x520, mod(hash, f_q))
            mstore(0x540, hash)
        }
mstore(0x560, mod(calldataload(0x2e0), f_q))
mstore(0x580, mod(calldataload(0x300), f_q))
mstore(0x5a0, mod(calldataload(0x320), f_q))
mstore(0x5c0, mod(calldataload(0x340), f_q))
mstore(0x5e0, mod(calldataload(0x360), f_q))
mstore(0x600, mod(calldataload(0x380), f_q))
mstore(0x620, mod(calldataload(0x3a0), f_q))
mstore(0x640, mod(calldataload(0x3c0), f_q))
mstore(0x660, mod(calldataload(0x3e0), f_q))
mstore(0x680, mod(calldataload(0x400), f_q))
mstore(0x6a0, mod(calldataload(0x420), f_q))
mstore(0x6c0, mod(calldataload(0x440), f_q))
mstore(0x6e0, mod(calldataload(0x460), f_q))
mstore(0x700, mod(calldataload(0x480), f_q))
mstore(0x720, mod(calldataload(0x4a0), f_q))
mstore(0x740, mod(calldataload(0x4c0), f_q))
mstore(0x760, mod(calldataload(0x4e0), f_q))
mstore(0x780, mod(calldataload(0x500), f_q))
mstore(0x7a0, mod(calldataload(0x520), f_q))
mstore(0x7c0, keccak256(0x540, 640))
{
            let hash := mload(0x7c0)
            mstore(0x7e0, mod(hash, f_q))
            mstore(0x800, hash)
        }
mstore8(2080, 1)
mstore(0x820, keccak256(0x800, 33))
{
            let hash := mload(0x820)
            mstore(0x840, mod(hash, f_q))
            mstore(0x860, hash)
        }

        {
            let x := calldataload(0x540)
            mstore(0x880, x)
            let y := calldataload(0x560)
            mstore(0x8a0, y)
            success := and(validate_ec_point(x, y), success)
        }
mstore(0x8c0, keccak256(0x860, 96))
{
            let hash := mload(0x8c0)
            mstore(0x8e0, mod(hash, f_q))
            mstore(0x900, hash)
        }

        {
            let x := calldataload(0x580)
            mstore(0x920, x)
            let y := calldataload(0x5a0)
            mstore(0x940, y)
            success := and(validate_ec_point(x, y), success)
        }
mstore(0x960, mulmod(mload(0x520), mload(0x520), f_q))
mstore(0x980, mulmod(mload(0x960), mload(0x960), f_q))
mstore(0x9a0, mulmod(mload(0x980), mload(0x980), f_q))
mstore(0x9c0, mulmod(mload(0x9a0), mload(0x9a0), f_q))
mstore(0x9e0, mulmod(mload(0x9c0), mload(0x9c0), f_q))
mstore(0xa00, mulmod(mload(0x9e0), mload(0x9e0), f_q))
mstore(0xa20, mulmod(mload(0xa00), mload(0xa00), f_q))
mstore(0xa40, mulmod(mload(0xa20), mload(0xa20), f_q))
mstore(0xa60, mulmod(mload(0xa40), mload(0xa40), f_q))
mstore(0xa80, mulmod(mload(0xa60), mload(0xa60), f_q))
mstore(0xaa0, mulmod(mload(0xa80), mload(0xa80), f_q))
mstore(0xac0, mulmod(mload(0xaa0), mload(0xaa0), f_q))
mstore(0xae0, mulmod(mload(0xac0), mload(0xac0), f_q))
mstore(0xb00, mulmod(mload(0xae0), mload(0xae0), f_q))
mstore(0xb20, mulmod(mload(0xb00), mload(0xb00), f_q))
mstore(0xb40, mulmod(mload(0xb20), mload(0xb20), f_q))
mstore(0xb60, mulmod(mload(0xb40), mload(0xb40), f_q))
mstore(0xb80, mulmod(mload(0xb60), mload(0xb60), f_q))
mstore(0xba0, mulmod(mload(0xb80), mload(0xb80), f_q))
mstore(0xbc0, mulmod(mload(0xba0), mload(0xba0), f_q))
mstore(0xbe0, mulmod(mload(0xbc0), mload(0xbc0), f_q))
mstore(0xc00, mulmod(mload(0xbe0), mload(0xbe0), f_q))
mstore(0xc20, mulmod(mload(0xc00), mload(0xc00), f_q))
mstore(0xc40, addmod(mload(0xc20), 21888242871839275222246405745257275088548364400416034343698204186575808495616, f_q))
mstore(0xc60, mulmod(mload(0xc40), 21888240262557392955334514970720457388010314637169927192662615958087340972065, f_q))
mstore(0xc80, mulmod(mload(0xc60), 4506835738822104338668100540817374747935106310012997856968187171738630203507, f_q))
mstore(0xca0, addmod(mload(0x520), 17381407133017170883578305204439900340613258090403036486730017014837178292110, f_q))
mstore(0xcc0, mulmod(mload(0xc60), 21710372849001950800533397158415938114909991150039389063546734567764856596059, f_q))
mstore(0xce0, addmod(mload(0x520), 177870022837324421713008586841336973638373250376645280151469618810951899558, f_q))
mstore(0xd00, mulmod(mload(0xc60), 1887003188133998471169152042388914354640772748308168868301418279904560637395, f_q))
mstore(0xd20, addmod(mload(0x520), 20001239683705276751077253702868360733907591652107865475396785906671247858222, f_q))
mstore(0xd40, mulmod(mload(0xc60), 2785514556381676080176937710880804108647911392478702105860685610379369825016, f_q))
mstore(0xd60, addmod(mload(0x520), 19102728315457599142069468034376470979900453007937332237837518576196438670601, f_q))
mstore(0xd80, mulmod(mload(0xc60), 14655294445420895451632927078981340937842238432098198055057679026789553137428, f_q))
mstore(0xda0, addmod(mload(0x520), 7232948426418379770613478666275934150706125968317836288640525159786255358189, f_q))
mstore(0xdc0, mulmod(mload(0xc60), 8734126352828345679573237859165904705806588461301144420590422589042130041188, f_q))
mstore(0xde0, addmod(mload(0x520), 13154116519010929542673167886091370382741775939114889923107781597533678454429, f_q))
mstore(0xe00, mulmod(mload(0xc60), 9741553891420464328295280489650144566903017206473301385034033384879943874347, f_q))
mstore(0xe20, addmod(mload(0x520), 12146688980418810893951125255607130521645347193942732958664170801695864621270, f_q))
mstore(0xe40, mulmod(mload(0xc60), 1, f_q))
mstore(0xe60, addmod(mload(0x520), 21888242871839275222246405745257275088548364400416034343698204186575808495616, f_q))
mstore(0xe80, mulmod(mload(0xc60), 8374374965308410102411073611984011876711565317741801500439755773472076597347, f_q))
mstore(0xea0, addmod(mload(0x520), 13513867906530865119835332133273263211836799082674232843258448413103731898270, f_q))
mstore(0xec0, mulmod(mload(0xc60), 11211301017135681023579411905410872569206244553457844956874280139879520583390, f_q))
mstore(0xee0, addmod(mload(0x520), 10676941854703594198666993839846402519342119846958189386823924046696287912227, f_q))
{
            let prod := mload(0xca0)

                prod := mulmod(mload(0xce0), prod, f_q)
                mstore(0xf00, prod)
            
                prod := mulmod(mload(0xd20), prod, f_q)
                mstore(0xf20, prod)
            
                prod := mulmod(mload(0xd60), prod, f_q)
                mstore(0xf40, prod)
            
                prod := mulmod(mload(0xda0), prod, f_q)
                mstore(0xf60, prod)
            
                prod := mulmod(mload(0xde0), prod, f_q)
                mstore(0xf80, prod)
            
                prod := mulmod(mload(0xe20), prod, f_q)
                mstore(0xfa0, prod)
            
                prod := mulmod(mload(0xe60), prod, f_q)
                mstore(0xfc0, prod)
            
                prod := mulmod(mload(0xea0), prod, f_q)
                mstore(0xfe0, prod)
            
                prod := mulmod(mload(0xee0), prod, f_q)
                mstore(0x1000, prod)
            
                prod := mulmod(mload(0xc40), prod, f_q)
                mstore(0x1020, prod)
            
        }
mstore(0x1060, 32)
mstore(0x1080, 32)
mstore(0x10a0, 32)
mstore(0x10c0, mload(0x1020))
mstore(0x10e0, 21888242871839275222246405745257275088548364400416034343698204186575808495615)
mstore(0x1100, 21888242871839275222246405745257275088548364400416034343698204186575808495617)
success := and(eq(staticcall(gas(), 0x5, 0x1060, 0xc0, 0x1040, 0x20), 1), success)
{
            
            let inv := mload(0x1040)
            let v
        
                    v := mload(0xc40)
                    mstore(3136, mulmod(mload(0x1000), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0xee0)
                    mstore(3808, mulmod(mload(0xfe0), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0xea0)
                    mstore(3744, mulmod(mload(0xfc0), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0xe60)
                    mstore(3680, mulmod(mload(0xfa0), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0xe20)
                    mstore(3616, mulmod(mload(0xf80), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0xde0)
                    mstore(3552, mulmod(mload(0xf60), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0xda0)
                    mstore(3488, mulmod(mload(0xf40), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0xd60)
                    mstore(3424, mulmod(mload(0xf20), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0xd20)
                    mstore(3360, mulmod(mload(0xf00), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0xce0)
                    mstore(3296, mulmod(mload(0xca0), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                mstore(0xca0, inv)

        }
mstore(0x1120, mulmod(mload(0xc80), mload(0xca0), f_q))
mstore(0x1140, mulmod(mload(0xcc0), mload(0xce0), f_q))
mstore(0x1160, mulmod(mload(0xd00), mload(0xd20), f_q))
mstore(0x1180, mulmod(mload(0xd40), mload(0xd60), f_q))
mstore(0x11a0, mulmod(mload(0xd80), mload(0xda0), f_q))
mstore(0x11c0, mulmod(mload(0xdc0), mload(0xde0), f_q))
mstore(0x11e0, mulmod(mload(0xe00), mload(0xe20), f_q))
mstore(0x1200, mulmod(mload(0xe40), mload(0xe60), f_q))
mstore(0x1220, mulmod(mload(0xe80), mload(0xea0), f_q))
mstore(0x1240, mulmod(mload(0xec0), mload(0xee0), f_q))
{
            let result := mulmod(mload(0x1200), mload(0xa0), f_q)
result := addmod(mulmod(mload(0x1220), mload(0xc0), f_q), result, f_q)
result := addmod(mulmod(mload(0x1240), mload(0xe0), f_q), result, f_q)
mstore(4704, result)
        }
mstore(0x1280, mulmod(mload(0x5a0), mload(0x580), f_q))
mstore(0x12a0, addmod(mload(0x560), mload(0x1280), f_q))
mstore(0x12c0, addmod(mload(0x12a0), sub(f_q, mload(0x5c0)), f_q))
mstore(0x12e0, mulmod(mload(0x12c0), mload(0x620), f_q))
mstore(0x1300, mulmod(mload(0x3c0), mload(0x12e0), f_q))
mstore(0x1320, addmod(1, sub(f_q, mload(0x6e0)), f_q))
mstore(0x1340, mulmod(mload(0x1320), mload(0x1200), f_q))
mstore(0x1360, addmod(mload(0x1300), mload(0x1340), f_q))
mstore(0x1380, mulmod(mload(0x3c0), mload(0x1360), f_q))
mstore(0x13a0, mulmod(mload(0x6e0), mload(0x6e0), f_q))
mstore(0x13c0, addmod(mload(0x13a0), sub(f_q, mload(0x6e0)), f_q))
mstore(0x13e0, mulmod(mload(0x13c0), mload(0x1120), f_q))
mstore(0x1400, addmod(mload(0x1380), mload(0x13e0), f_q))
mstore(0x1420, mulmod(mload(0x3c0), mload(0x1400), f_q))
mstore(0x1440, addmod(1, sub(f_q, mload(0x1120)), f_q))
mstore(0x1460, addmod(mload(0x1140), mload(0x1160), f_q))
mstore(0x1480, addmod(mload(0x1460), mload(0x1180), f_q))
mstore(0x14a0, addmod(mload(0x1480), mload(0x11a0), f_q))
mstore(0x14c0, addmod(mload(0x14a0), mload(0x11c0), f_q))
mstore(0x14e0, addmod(mload(0x14c0), mload(0x11e0), f_q))
mstore(0x1500, addmod(mload(0x1440), sub(f_q, mload(0x14e0)), f_q))
mstore(0x1520, mulmod(mload(0x680), mload(0x240), f_q))
mstore(0x1540, addmod(mload(0x5e0), mload(0x1520), f_q))
mstore(0x1560, addmod(mload(0x1540), mload(0x2a0), f_q))
mstore(0x1580, mulmod(mload(0x6a0), mload(0x240), f_q))
mstore(0x15a0, addmod(mload(0x560), mload(0x1580), f_q))
mstore(0x15c0, addmod(mload(0x15a0), mload(0x2a0), f_q))
mstore(0x15e0, mulmod(mload(0x15c0), mload(0x1560), f_q))
mstore(0x1600, mulmod(mload(0x6c0), mload(0x240), f_q))
mstore(0x1620, addmod(mload(0x1260), mload(0x1600), f_q))
mstore(0x1640, addmod(mload(0x1620), mload(0x2a0), f_q))
mstore(0x1660, mulmod(mload(0x1640), mload(0x15e0), f_q))
mstore(0x1680, mulmod(mload(0x1660), mload(0x700), f_q))
mstore(0x16a0, mulmod(1, mload(0x240), f_q))
mstore(0x16c0, mulmod(mload(0x520), mload(0x16a0), f_q))
mstore(0x16e0, addmod(mload(0x5e0), mload(0x16c0), f_q))
mstore(0x1700, addmod(mload(0x16e0), mload(0x2a0), f_q))
mstore(0x1720, mulmod(4131629893567559867359510883348571134090853742863529169391034518566172092834, mload(0x240), f_q))
mstore(0x1740, mulmod(mload(0x520), mload(0x1720), f_q))
mstore(0x1760, addmod(mload(0x560), mload(0x1740), f_q))
mstore(0x1780, addmod(mload(0x1760), mload(0x2a0), f_q))
mstore(0x17a0, mulmod(mload(0x1780), mload(0x1700), f_q))
mstore(0x17c0, mulmod(8910878055287538404433155982483128285667088683464058436815641868457422632747, mload(0x240), f_q))
mstore(0x17e0, mulmod(mload(0x520), mload(0x17c0), f_q))
mstore(0x1800, addmod(mload(0x1260), mload(0x17e0), f_q))
mstore(0x1820, addmod(mload(0x1800), mload(0x2a0), f_q))
mstore(0x1840, mulmod(mload(0x1820), mload(0x17a0), f_q))
mstore(0x1860, mulmod(mload(0x1840), mload(0x6e0), f_q))
mstore(0x1880, addmod(mload(0x1680), sub(f_q, mload(0x1860)), f_q))
mstore(0x18a0, mulmod(mload(0x1880), mload(0x1500), f_q))
mstore(0x18c0, addmod(mload(0x1420), mload(0x18a0), f_q))
mstore(0x18e0, mulmod(mload(0x3c0), mload(0x18c0), f_q))
mstore(0x1900, addmod(1, sub(f_q, mload(0x720)), f_q))
mstore(0x1920, mulmod(mload(0x1900), mload(0x1200), f_q))
mstore(0x1940, addmod(mload(0x18e0), mload(0x1920), f_q))
mstore(0x1960, mulmod(mload(0x3c0), mload(0x1940), f_q))
mstore(0x1980, mulmod(mload(0x720), mload(0x720), f_q))
mstore(0x19a0, addmod(mload(0x1980), sub(f_q, mload(0x720)), f_q))
mstore(0x19c0, mulmod(mload(0x19a0), mload(0x1120), f_q))
mstore(0x19e0, addmod(mload(0x1960), mload(0x19c0), f_q))
mstore(0x1a00, mulmod(mload(0x3c0), mload(0x19e0), f_q))
mstore(0x1a20, addmod(mload(0x760), mload(0x240), f_q))
mstore(0x1a40, mulmod(mload(0x1a20), mload(0x740), f_q))
mstore(0x1a60, addmod(mload(0x7a0), mload(0x2a0), f_q))
mstore(0x1a80, mulmod(mload(0x1a60), mload(0x1a40), f_q))
mstore(0x1aa0, mulmod(mload(0x560), mload(0x640), f_q))
mstore(0x1ac0, addmod(mload(0x1aa0), mload(0x240), f_q))
mstore(0x1ae0, mulmod(mload(0x1ac0), mload(0x720), f_q))
mstore(0x1b00, addmod(mload(0x600), mload(0x2a0), f_q))
mstore(0x1b20, mulmod(mload(0x1b00), mload(0x1ae0), f_q))
mstore(0x1b40, addmod(mload(0x1a80), sub(f_q, mload(0x1b20)), f_q))
mstore(0x1b60, mulmod(mload(0x1b40), mload(0x1500), f_q))
mstore(0x1b80, addmod(mload(0x1a00), mload(0x1b60), f_q))
mstore(0x1ba0, mulmod(mload(0x3c0), mload(0x1b80), f_q))
mstore(0x1bc0, addmod(mload(0x760), sub(f_q, mload(0x7a0)), f_q))
mstore(0x1be0, mulmod(mload(0x1bc0), mload(0x1200), f_q))
mstore(0x1c00, addmod(mload(0x1ba0), mload(0x1be0), f_q))
mstore(0x1c20, mulmod(mload(0x3c0), mload(0x1c00), f_q))
mstore(0x1c40, mulmod(mload(0x1bc0), mload(0x1500), f_q))
mstore(0x1c60, addmod(mload(0x760), sub(f_q, mload(0x780)), f_q))
mstore(0x1c80, mulmod(mload(0x1c60), mload(0x1c40), f_q))
mstore(0x1ca0, addmod(mload(0x1c20), mload(0x1c80), f_q))
mstore(0x1cc0, mulmod(mload(0xc20), mload(0xc20), f_q))
mstore(0x1ce0, mulmod(mload(0x1cc0), mload(0xc20), f_q))
mstore(0x1d00, mulmod(mload(0x1ce0), mload(0xc20), f_q))
mstore(0x1d20, mulmod(1, mload(0xc20), f_q))
mstore(0x1d40, mulmod(1, mload(0x1cc0), f_q))
mstore(0x1d60, mulmod(1, mload(0x1ce0), f_q))
mstore(0x1d80, mulmod(mload(0x1ca0), mload(0xc40), f_q))
mstore(0x1da0, mulmod(mload(0x960), mload(0x520), f_q))
mstore(0x1dc0, mulmod(mload(0x1da0), mload(0x520), f_q))
mstore(0x1de0, mulmod(mload(0x520), 9741553891420464328295280489650144566903017206473301385034033384879943874347, f_q))
mstore(0x1e00, addmod(mload(0x8e0), sub(f_q, mload(0x1de0)), f_q))
mstore(0x1e20, mulmod(mload(0x520), 1, f_q))
mstore(0x1e40, addmod(mload(0x8e0), sub(f_q, mload(0x1e20)), f_q))
mstore(0x1e60, mulmod(mload(0x520), 8374374965308410102411073611984011876711565317741801500439755773472076597347, f_q))
mstore(0x1e80, addmod(mload(0x8e0), sub(f_q, mload(0x1e60)), f_q))
mstore(0x1ea0, mulmod(mload(0x520), 11211301017135681023579411905410872569206244553457844956874280139879520583390, f_q))
mstore(0x1ec0, addmod(mload(0x8e0), sub(f_q, mload(0x1ea0)), f_q))
mstore(0x1ee0, mulmod(mload(0x520), 3615478808282855240548287271348143516886772452944084747768312988864436725401, f_q))
mstore(0x1f00, addmod(mload(0x8e0), sub(f_q, mload(0x1ee0)), f_q))
mstore(0x1f20, mulmod(13213688729882003894512633350385593288217014177373218494356903340348818451480, mload(0x1da0), f_q))
mstore(0x1f40, mulmod(mload(0x1f20), 1, f_q))
{
            let result := mulmod(mload(0x8e0), mload(0x1f20), f_q)
result := addmod(mulmod(mload(0x520), sub(f_q, mload(0x1f40)), f_q), result, f_q)
mstore(8032, result)
        }
mstore(0x1f80, mulmod(8207090019724696496350398458716998472718344609680392612601596849934418295470, mload(0x1da0), f_q))
mstore(0x1fa0, mulmod(mload(0x1f80), 8374374965308410102411073611984011876711565317741801500439755773472076597347, f_q))
{
            let result := mulmod(mload(0x8e0), mload(0x1f80), f_q)
result := addmod(mulmod(mload(0x520), sub(f_q, mload(0x1fa0)), f_q), result, f_q)
mstore(8128, result)
        }
mstore(0x1fe0, mulmod(7391709068497399131897422873231908718558236401035363928063603272120120747483, mload(0x1da0), f_q))
mstore(0x2000, mulmod(mload(0x1fe0), 11211301017135681023579411905410872569206244553457844956874280139879520583390, f_q))
{
            let result := mulmod(mload(0x8e0), mload(0x1fe0), f_q)
result := addmod(mulmod(mload(0x520), sub(f_q, mload(0x2000)), f_q), result, f_q)
mstore(8224, result)
        }
mstore(0x2040, mulmod(19036273796805830823244991598792794567595348772040298280440552631112242221017, mload(0x1da0), f_q))
mstore(0x2060, mulmod(mload(0x2040), 3615478808282855240548287271348143516886772452944084747768312988864436725401, f_q))
{
            let result := mulmod(mload(0x8e0), mload(0x2040), f_q)
result := addmod(mulmod(mload(0x520), sub(f_q, mload(0x2060)), f_q), result, f_q)
mstore(8320, result)
        }
mstore(0x20a0, mulmod(1, mload(0x1e40), f_q))
mstore(0x20c0, mulmod(mload(0x20a0), mload(0x1e80), f_q))
mstore(0x20e0, mulmod(mload(0x20c0), mload(0x1ec0), f_q))
mstore(0x2100, mulmod(mload(0x20e0), mload(0x1f00), f_q))
mstore(0x2120, mulmod(13513867906530865119835332133273263211836799082674232843258448413103731898271, mload(0x520), f_q))
mstore(0x2140, mulmod(mload(0x2120), 1, f_q))
{
            let result := mulmod(mload(0x8e0), mload(0x2120), f_q)
result := addmod(mulmod(mload(0x520), sub(f_q, mload(0x2140)), f_q), result, f_q)
mstore(8544, result)
        }
mstore(0x2180, mulmod(8374374965308410102411073611984011876711565317741801500439755773472076597346, mload(0x520), f_q))
mstore(0x21a0, mulmod(mload(0x2180), 8374374965308410102411073611984011876711565317741801500439755773472076597347, f_q))
{
            let result := mulmod(mload(0x8e0), mload(0x2180), f_q)
result := addmod(mulmod(mload(0x520), sub(f_q, mload(0x21a0)), f_q), result, f_q)
mstore(8640, result)
        }
mstore(0x21e0, mulmod(12146688980418810893951125255607130521645347193942732958664170801695864621271, mload(0x520), f_q))
mstore(0x2200, mulmod(mload(0x21e0), 1, f_q))
{
            let result := mulmod(mload(0x8e0), mload(0x21e0), f_q)
result := addmod(mulmod(mload(0x520), sub(f_q, mload(0x2200)), f_q), result, f_q)
mstore(8736, result)
        }
mstore(0x2240, mulmod(9741553891420464328295280489650144566903017206473301385034033384879943874346, mload(0x520), f_q))
mstore(0x2260, mulmod(mload(0x2240), 9741553891420464328295280489650144566903017206473301385034033384879943874347, f_q))
{
            let result := mulmod(mload(0x8e0), mload(0x2240), f_q)
result := addmod(mulmod(mload(0x520), sub(f_q, mload(0x2260)), f_q), result, f_q)
mstore(8832, result)
        }
mstore(0x22a0, mulmod(mload(0x20a0), mload(0x1e00), f_q))
{
            let result := mulmod(mload(0x8e0), 1, f_q)
result := addmod(mulmod(mload(0x520), 21888242871839275222246405745257275088548364400416034343698204186575808495616, f_q), result, f_q)
mstore(8896, result)
        }
{
            let prod := mload(0x1f60)

                prod := mulmod(mload(0x1fc0), prod, f_q)
                mstore(0x22e0, prod)
            
                prod := mulmod(mload(0x2020), prod, f_q)
                mstore(0x2300, prod)
            
                prod := mulmod(mload(0x2080), prod, f_q)
                mstore(0x2320, prod)
            
                prod := mulmod(mload(0x2160), prod, f_q)
                mstore(0x2340, prod)
            
                prod := mulmod(mload(0x21c0), prod, f_q)
                mstore(0x2360, prod)
            
                prod := mulmod(mload(0x20c0), prod, f_q)
                mstore(0x2380, prod)
            
                prod := mulmod(mload(0x2220), prod, f_q)
                mstore(0x23a0, prod)
            
                prod := mulmod(mload(0x2280), prod, f_q)
                mstore(0x23c0, prod)
            
                prod := mulmod(mload(0x22a0), prod, f_q)
                mstore(0x23e0, prod)
            
                prod := mulmod(mload(0x22c0), prod, f_q)
                mstore(0x2400, prod)
            
                prod := mulmod(mload(0x20a0), prod, f_q)
                mstore(0x2420, prod)
            
        }
mstore(0x2460, 32)
mstore(0x2480, 32)
mstore(0x24a0, 32)
mstore(0x24c0, mload(0x2420))
mstore(0x24e0, 21888242871839275222246405745257275088548364400416034343698204186575808495615)
mstore(0x2500, 21888242871839275222246405745257275088548364400416034343698204186575808495617)
success := and(eq(staticcall(gas(), 0x5, 0x2460, 0xc0, 0x2440, 0x20), 1), success)
{
            
            let inv := mload(0x2440)
            let v
        
                    v := mload(0x20a0)
                    mstore(8352, mulmod(mload(0x2400), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0x22c0)
                    mstore(8896, mulmod(mload(0x23e0), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0x22a0)
                    mstore(8864, mulmod(mload(0x23c0), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0x2280)
                    mstore(8832, mulmod(mload(0x23a0), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0x2220)
                    mstore(8736, mulmod(mload(0x2380), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0x20c0)
                    mstore(8384, mulmod(mload(0x2360), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0x21c0)
                    mstore(8640, mulmod(mload(0x2340), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0x2160)
                    mstore(8544, mulmod(mload(0x2320), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0x2080)
                    mstore(8320, mulmod(mload(0x2300), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0x2020)
                    mstore(8224, mulmod(mload(0x22e0), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0x1fc0)
                    mstore(8128, mulmod(mload(0x1f60), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                mstore(0x1f60, inv)

        }
{
            let result := mload(0x1f60)
result := addmod(mload(0x1fc0), result, f_q)
result := addmod(mload(0x2020), result, f_q)
result := addmod(mload(0x2080), result, f_q)
mstore(9504, result)
        }
mstore(0x2540, mulmod(mload(0x2100), mload(0x20c0), f_q))
{
            let result := mload(0x2160)
result := addmod(mload(0x21c0), result, f_q)
mstore(9568, result)
        }
mstore(0x2580, mulmod(mload(0x2100), mload(0x22a0), f_q))
{
            let result := mload(0x2220)
result := addmod(mload(0x2280), result, f_q)
mstore(9632, result)
        }
mstore(0x25c0, mulmod(mload(0x2100), mload(0x20a0), f_q))
{
            let result := mload(0x22c0)
mstore(9696, result)
        }
{
            let prod := mload(0x2520)

                prod := mulmod(mload(0x2560), prod, f_q)
                mstore(0x2600, prod)
            
                prod := mulmod(mload(0x25a0), prod, f_q)
                mstore(0x2620, prod)
            
                prod := mulmod(mload(0x25e0), prod, f_q)
                mstore(0x2640, prod)
            
        }
mstore(0x2680, 32)
mstore(0x26a0, 32)
mstore(0x26c0, 32)
mstore(0x26e0, mload(0x2640))
mstore(0x2700, 21888242871839275222246405745257275088548364400416034343698204186575808495615)
mstore(0x2720, 21888242871839275222246405745257275088548364400416034343698204186575808495617)
success := and(eq(staticcall(gas(), 0x5, 0x2680, 0xc0, 0x2660, 0x20), 1), success)
{
            
            let inv := mload(0x2660)
            let v
        
                    v := mload(0x25e0)
                    mstore(9696, mulmod(mload(0x2620), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0x25a0)
                    mstore(9632, mulmod(mload(0x2600), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                
                    v := mload(0x2560)
                    mstore(9568, mulmod(mload(0x2520), inv, f_q))
                    inv := mulmod(v, inv, f_q)
                mstore(0x2520, inv)

        }
mstore(0x2740, mulmod(mload(0x2540), mload(0x2560), f_q))
mstore(0x2760, mulmod(mload(0x2580), mload(0x25a0), f_q))
mstore(0x2780, mulmod(mload(0x25c0), mload(0x25e0), f_q))
mstore(0x27a0, mulmod(mload(0x7e0), mload(0x7e0), f_q))
mstore(0x27c0, mulmod(mload(0x27a0), mload(0x7e0), f_q))
mstore(0x27e0, mulmod(mload(0x27c0), mload(0x7e0), f_q))
mstore(0x2800, mulmod(mload(0x27e0), mload(0x7e0), f_q))
mstore(0x2820, mulmod(mload(0x2800), mload(0x7e0), f_q))
mstore(0x2840, mulmod(mload(0x2820), mload(0x7e0), f_q))
mstore(0x2860, mulmod(mload(0x2840), mload(0x7e0), f_q))
mstore(0x2880, mulmod(mload(0x2860), mload(0x7e0), f_q))
mstore(0x28a0, mulmod(mload(0x2880), mload(0x7e0), f_q))
mstore(0x28c0, mulmod(mload(0x840), mload(0x840), f_q))
mstore(0x28e0, mulmod(mload(0x28c0), mload(0x840), f_q))
mstore(0x2900, mulmod(mload(0x28e0), mload(0x840), f_q))
{
            let result := mulmod(mload(0x560), mload(0x1f60), f_q)
result := addmod(mulmod(mload(0x580), mload(0x1fc0), f_q), result, f_q)
result := addmod(mulmod(mload(0x5a0), mload(0x2020), f_q), result, f_q)
result := addmod(mulmod(mload(0x5c0), mload(0x2080), f_q), result, f_q)
mstore(10528, result)
        }
mstore(0x2940, mulmod(mload(0x2920), mload(0x2520), f_q))
mstore(0x2960, mulmod(sub(f_q, mload(0x2940)), 1, f_q))
mstore(0x2980, mulmod(mload(0x2960), 1, f_q))
mstore(0x29a0, mulmod(1, mload(0x2540), f_q))
{
            let result := mulmod(mload(0x6e0), mload(0x2160), f_q)
result := addmod(mulmod(mload(0x700), mload(0x21c0), f_q), result, f_q)
mstore(10688, result)
        }
mstore(0x29e0, mulmod(mload(0x29c0), mload(0x2740), f_q))
mstore(0x2a00, mulmod(sub(f_q, mload(0x29e0)), 1, f_q))
mstore(0x2a20, mulmod(mload(0x29a0), 1, f_q))
{
            let result := mulmod(mload(0x720), mload(0x2160), f_q)
result := addmod(mulmod(mload(0x740), mload(0x21c0), f_q), result, f_q)
mstore(10816, result)
        }
mstore(0x2a60, mulmod(mload(0x2a40), mload(0x2740), f_q))
mstore(0x2a80, mulmod(sub(f_q, mload(0x2a60)), mload(0x7e0), f_q))
mstore(0x2aa0, mulmod(mload(0x29a0), mload(0x7e0), f_q))
mstore(0x2ac0, addmod(mload(0x2a00), mload(0x2a80), f_q))
mstore(0x2ae0, mulmod(mload(0x2ac0), mload(0x840), f_q))
mstore(0x2b00, mulmod(mload(0x2a20), mload(0x840), f_q))
mstore(0x2b20, mulmod(mload(0x2aa0), mload(0x840), f_q))
mstore(0x2b40, addmod(mload(0x2980), mload(0x2ae0), f_q))
mstore(0x2b60, mulmod(1, mload(0x2580), f_q))
{
            let result := mulmod(mload(0x760), mload(0x2220), f_q)
result := addmod(mulmod(mload(0x780), mload(0x2280), f_q), result, f_q)
mstore(11136, result)
        }
mstore(0x2ba0, mulmod(mload(0x2b80), mload(0x2760), f_q))
mstore(0x2bc0, mulmod(sub(f_q, mload(0x2ba0)), 1, f_q))
mstore(0x2be0, mulmod(mload(0x2b60), 1, f_q))
mstore(0x2c00, mulmod(mload(0x2bc0), mload(0x28c0), f_q))
mstore(0x2c20, mulmod(mload(0x2be0), mload(0x28c0), f_q))
mstore(0x2c40, addmod(mload(0x2b40), mload(0x2c00), f_q))
mstore(0x2c60, mulmod(1, mload(0x25c0), f_q))
{
            let result := mulmod(mload(0x7a0), mload(0x22c0), f_q)
mstore(11392, result)
        }
mstore(0x2ca0, mulmod(mload(0x2c80), mload(0x2780), f_q))
mstore(0x2cc0, mulmod(sub(f_q, mload(0x2ca0)), 1, f_q))
mstore(0x2ce0, mulmod(mload(0x2c60), 1, f_q))
{
            let result := mulmod(mload(0x5e0), mload(0x22c0), f_q)
mstore(11520, result)
        }
mstore(0x2d20, mulmod(mload(0x2d00), mload(0x2780), f_q))
mstore(0x2d40, mulmod(sub(f_q, mload(0x2d20)), mload(0x7e0), f_q))
mstore(0x2d60, mulmod(mload(0x2c60), mload(0x7e0), f_q))
mstore(0x2d80, addmod(mload(0x2cc0), mload(0x2d40), f_q))
{
            let result := mulmod(mload(0x600), mload(0x22c0), f_q)
mstore(11680, result)
        }
mstore(0x2dc0, mulmod(mload(0x2da0), mload(0x2780), f_q))
mstore(0x2de0, mulmod(sub(f_q, mload(0x2dc0)), mload(0x27a0), f_q))
mstore(0x2e00, mulmod(mload(0x2c60), mload(0x27a0), f_q))
mstore(0x2e20, addmod(mload(0x2d80), mload(0x2de0), f_q))
{
            let result := mulmod(mload(0x620), mload(0x22c0), f_q)
mstore(11840, result)
        }
mstore(0x2e60, mulmod(mload(0x2e40), mload(0x2780), f_q))
mstore(0x2e80, mulmod(sub(f_q, mload(0x2e60)), mload(0x27c0), f_q))
mstore(0x2ea0, mulmod(mload(0x2c60), mload(0x27c0), f_q))
mstore(0x2ec0, addmod(mload(0x2e20), mload(0x2e80), f_q))
{
            let result := mulmod(mload(0x640), mload(0x22c0), f_q)
mstore(12000, result)
        }
mstore(0x2f00, mulmod(mload(0x2ee0), mload(0x2780), f_q))
mstore(0x2f20, mulmod(sub(f_q, mload(0x2f00)), mload(0x27e0), f_q))
mstore(0x2f40, mulmod(mload(0x2c60), mload(0x27e0), f_q))
mstore(0x2f60, addmod(mload(0x2ec0), mload(0x2f20), f_q))
{
            let result := mulmod(mload(0x680), mload(0x22c0), f_q)
mstore(12160, result)
        }
mstore(0x2fa0, mulmod(mload(0x2f80), mload(0x2780), f_q))
mstore(0x2fc0, mulmod(sub(f_q, mload(0x2fa0)), mload(0x2800), f_q))
mstore(0x2fe0, mulmod(mload(0x2c60), mload(0x2800), f_q))
mstore(0x3000, addmod(mload(0x2f60), mload(0x2fc0), f_q))
{
            let result := mulmod(mload(0x6a0), mload(0x22c0), f_q)
mstore(12320, result)
        }
mstore(0x3040, mulmod(mload(0x3020), mload(0x2780), f_q))
mstore(0x3060, mulmod(sub(f_q, mload(0x3040)), mload(0x2820), f_q))
mstore(0x3080, mulmod(mload(0x2c60), mload(0x2820), f_q))
mstore(0x30a0, addmod(mload(0x3000), mload(0x3060), f_q))
{
            let result := mulmod(mload(0x6c0), mload(0x22c0), f_q)
mstore(12480, result)
        }
mstore(0x30e0, mulmod(mload(0x30c0), mload(0x2780), f_q))
mstore(0x3100, mulmod(sub(f_q, mload(0x30e0)), mload(0x2840), f_q))
mstore(0x3120, mulmod(mload(0x2c60), mload(0x2840), f_q))
mstore(0x3140, addmod(mload(0x30a0), mload(0x3100), f_q))
mstore(0x3160, mulmod(mload(0x1d20), mload(0x25c0), f_q))
mstore(0x3180, mulmod(mload(0x1d40), mload(0x25c0), f_q))
mstore(0x31a0, mulmod(mload(0x1d60), mload(0x25c0), f_q))
{
            let result := mulmod(mload(0x1d80), mload(0x22c0), f_q)
mstore(12736, result)
        }
mstore(0x31e0, mulmod(mload(0x31c0), mload(0x2780), f_q))
mstore(0x3200, mulmod(sub(f_q, mload(0x31e0)), mload(0x2860), f_q))
mstore(0x3220, mulmod(mload(0x2c60), mload(0x2860), f_q))
mstore(0x3240, mulmod(mload(0x3160), mload(0x2860), f_q))
mstore(0x3260, mulmod(mload(0x3180), mload(0x2860), f_q))
mstore(0x3280, mulmod(mload(0x31a0), mload(0x2860), f_q))
mstore(0x32a0, addmod(mload(0x3140), mload(0x3200), f_q))
{
            let result := mulmod(mload(0x660), mload(0x22c0), f_q)
mstore(12992, result)
        }
mstore(0x32e0, mulmod(mload(0x32c0), mload(0x2780), f_q))
mstore(0x3300, mulmod(sub(f_q, mload(0x32e0)), mload(0x2880), f_q))
mstore(0x3320, mulmod(mload(0x2c60), mload(0x2880), f_q))
mstore(0x3340, addmod(mload(0x32a0), mload(0x3300), f_q))
mstore(0x3360, mulmod(mload(0x3340), mload(0x28e0), f_q))
mstore(0x3380, mulmod(mload(0x2ce0), mload(0x28e0), f_q))
mstore(0x33a0, mulmod(mload(0x2d60), mload(0x28e0), f_q))
mstore(0x33c0, mulmod(mload(0x2e00), mload(0x28e0), f_q))
mstore(0x33e0, mulmod(mload(0x2ea0), mload(0x28e0), f_q))
mstore(0x3400, mulmod(mload(0x2f40), mload(0x28e0), f_q))
mstore(0x3420, mulmod(mload(0x2fe0), mload(0x28e0), f_q))
mstore(0x3440, mulmod(mload(0x3080), mload(0x28e0), f_q))
mstore(0x3460, mulmod(mload(0x3120), mload(0x28e0), f_q))
mstore(0x3480, mulmod(mload(0x3220), mload(0x28e0), f_q))
mstore(0x34a0, mulmod(mload(0x3240), mload(0x28e0), f_q))
mstore(0x34c0, mulmod(mload(0x3260), mload(0x28e0), f_q))
mstore(0x34e0, mulmod(mload(0x3280), mload(0x28e0), f_q))
mstore(0x3500, mulmod(mload(0x3320), mload(0x28e0), f_q))
mstore(0x3520, addmod(mload(0x2c40), mload(0x3360), f_q))
mstore(0x3540, mulmod(1, mload(0x2100), f_q))
mstore(0x3560, mulmod(1, mload(0x8e0), f_q))
mstore(0x3580, 0x0000000000000000000000000000000000000000000000000000000000000001)
                    mstore(0x35a0, 0x0000000000000000000000000000000000000000000000000000000000000002)
mstore(0x35c0, mload(0x3520))
success := and(eq(staticcall(gas(), 0x7, 0x3580, 0x60, 0x3580, 0x40), 1), success)
mstore(0x35e0, mload(0x3580))
                    mstore(0x3600, mload(0x35a0))
mstore(0x3620, mload(0x100))
                    mstore(0x3640, mload(0x120))
success := and(eq(staticcall(gas(), 0x6, 0x35e0, 0x80, 0x35e0, 0x40), 1), success)
mstore(0x3660, mload(0x2e0))
                    mstore(0x3680, mload(0x300))
mstore(0x36a0, mload(0x2b00))
success := and(eq(staticcall(gas(), 0x7, 0x3660, 0x60, 0x3660, 0x40), 1), success)
mstore(0x36c0, mload(0x35e0))
                    mstore(0x36e0, mload(0x3600))
mstore(0x3700, mload(0x3660))
                    mstore(0x3720, mload(0x3680))
success := and(eq(staticcall(gas(), 0x6, 0x36c0, 0x80, 0x36c0, 0x40), 1), success)
mstore(0x3740, mload(0x320))
                    mstore(0x3760, mload(0x340))
mstore(0x3780, mload(0x2b20))
success := and(eq(staticcall(gas(), 0x7, 0x3740, 0x60, 0x3740, 0x40), 1), success)
mstore(0x37a0, mload(0x36c0))
                    mstore(0x37c0, mload(0x36e0))
mstore(0x37e0, mload(0x3740))
                    mstore(0x3800, mload(0x3760))
success := and(eq(staticcall(gas(), 0x6, 0x37a0, 0x80, 0x37a0, 0x40), 1), success)
mstore(0x3820, mload(0x1a0))
                    mstore(0x3840, mload(0x1c0))
mstore(0x3860, mload(0x2c20))
success := and(eq(staticcall(gas(), 0x7, 0x3820, 0x60, 0x3820, 0x40), 1), success)
mstore(0x3880, mload(0x37a0))
                    mstore(0x38a0, mload(0x37c0))
mstore(0x38c0, mload(0x3820))
                    mstore(0x38e0, mload(0x3840))
success := and(eq(staticcall(gas(), 0x6, 0x3880, 0x80, 0x3880, 0x40), 1), success)
mstore(0x3900, mload(0x1e0))
                    mstore(0x3920, mload(0x200))
mstore(0x3940, mload(0x3380))
success := and(eq(staticcall(gas(), 0x7, 0x3900, 0x60, 0x3900, 0x40), 1), success)
mstore(0x3960, mload(0x3880))
                    mstore(0x3980, mload(0x38a0))
mstore(0x39a0, mload(0x3900))
                    mstore(0x39c0, mload(0x3920))
success := and(eq(staticcall(gas(), 0x6, 0x3960, 0x80, 0x3960, 0x40), 1), success)
mstore(0x39e0, 0x220bd1ac082a64b02cc0523d637f22ca3704c7ec1d776d9e0118dbd7555c435f)
                    mstore(0x3a00, 0x0536208018b5b32f9c59e902f70d452ea1844c9d556bcc471689c72c0283b04a)
mstore(0x3a20, mload(0x33a0))
success := and(eq(staticcall(gas(), 0x7, 0x39e0, 0x60, 0x39e0, 0x40), 1), success)
mstore(0x3a40, mload(0x3960))
                    mstore(0x3a60, mload(0x3980))
mstore(0x3a80, mload(0x39e0))
                    mstore(0x3aa0, mload(0x3a00))
success := and(eq(staticcall(gas(), 0x6, 0x3a40, 0x80, 0x3a40, 0x40), 1), success)
mstore(0x3ac0, 0x0c8564ccdedaa665e2a6d7a62df66d301f768431696539a7a83c8b0945597d51)
                    mstore(0x3ae0, 0x0967706cd514e5b24c84c61b14bf7cdec62bd7439e2082bfcd7da8ce699892d0)
mstore(0x3b00, mload(0x33c0))
success := and(eq(staticcall(gas(), 0x7, 0x3ac0, 0x60, 0x3ac0, 0x40), 1), success)
mstore(0x3b20, mload(0x3a40))
                    mstore(0x3b40, mload(0x3a60))
mstore(0x3b60, mload(0x3ac0))
                    mstore(0x3b80, mload(0x3ae0))
success := and(eq(staticcall(gas(), 0x6, 0x3b20, 0x80, 0x3b20, 0x40), 1), success)
mstore(0x3ba0, 0x05026454e438efd95332b6aef358af9d0a2512c3fec031fb32ed4c0733c7a159)
                    mstore(0x3bc0, 0x0295f18fe667aa5d0ac71264fa000fbd269f141b06bbdb90f451e771558ebf54)
mstore(0x3be0, mload(0x33e0))
success := and(eq(staticcall(gas(), 0x7, 0x3ba0, 0x60, 0x3ba0, 0x40), 1), success)
mstore(0x3c00, mload(0x3b20))
                    mstore(0x3c20, mload(0x3b40))
mstore(0x3c40, mload(0x3ba0))
                    mstore(0x3c60, mload(0x3bc0))
success := and(eq(staticcall(gas(), 0x6, 0x3c00, 0x80, 0x3c00, 0x40), 1), success)
mstore(0x3c80, 0x16e35b1e6e9aadac7a76e772e9f6e26e19a9bf3e15132e40562daf40e738ffe8)
                    mstore(0x3ca0, 0x10573160e2cd71549a935ca7a69e5bbe279fd2030becc3cd147bd6b70198b842)
mstore(0x3cc0, mload(0x3400))
success := and(eq(staticcall(gas(), 0x7, 0x3c80, 0x60, 0x3c80, 0x40), 1), success)
mstore(0x3ce0, mload(0x3c00))
                    mstore(0x3d00, mload(0x3c20))
mstore(0x3d20, mload(0x3c80))
                    mstore(0x3d40, mload(0x3ca0))
success := and(eq(staticcall(gas(), 0x6, 0x3ce0, 0x80, 0x3ce0, 0x40), 1), success)
mstore(0x3d60, 0x16ba3ced29683ba28d0c1540e084f74e2bcc3a72d9ee4e38c46889faab004f3c)
                    mstore(0x3d80, 0x27637a019d9541e1cc506963bd77a5bcbced4a919ebfd930d0daee79c6312cab)
mstore(0x3da0, mload(0x3420))
success := and(eq(staticcall(gas(), 0x7, 0x3d60, 0x60, 0x3d60, 0x40), 1), success)
mstore(0x3dc0, mload(0x3ce0))
                    mstore(0x3de0, mload(0x3d00))
mstore(0x3e00, mload(0x3d60))
                    mstore(0x3e20, mload(0x3d80))
success := and(eq(staticcall(gas(), 0x6, 0x3dc0, 0x80, 0x3dc0, 0x40), 1), success)
mstore(0x3e40, 0x23b7ac47c7c6ec671ab2e843ac7028cbf96f3d9b9592f6bf7aeff65cfa9b1bff)
                    mstore(0x3e60, 0x169f43bcbbefff3a2eb8d67c7d8d627ae0304a3a68f3025bcc9ebaadc3df30ce)
mstore(0x3e80, mload(0x3440))
success := and(eq(staticcall(gas(), 0x7, 0x3e40, 0x60, 0x3e40, 0x40), 1), success)
mstore(0x3ea0, mload(0x3dc0))
                    mstore(0x3ec0, mload(0x3de0))
mstore(0x3ee0, mload(0x3e40))
                    mstore(0x3f00, mload(0x3e60))
success := and(eq(staticcall(gas(), 0x6, 0x3ea0, 0x80, 0x3ea0, 0x40), 1), success)
mstore(0x3f20, 0x041413954a796750cf7981cc69d9eddcd16c522a60d59708ac43497885165159)
                    mstore(0x3f40, 0x013cbf83743e0ce84526c11074d3ad29b91218673e390bce1cd1173608afcca2)
mstore(0x3f60, mload(0x3460))
success := and(eq(staticcall(gas(), 0x7, 0x3f20, 0x60, 0x3f20, 0x40), 1), success)
mstore(0x3f80, mload(0x3ea0))
                    mstore(0x3fa0, mload(0x3ec0))
mstore(0x3fc0, mload(0x3f20))
                    mstore(0x3fe0, mload(0x3f40))
success := and(eq(staticcall(gas(), 0x6, 0x3f80, 0x80, 0x3f80, 0x40), 1), success)
mstore(0x4000, mload(0x400))
                    mstore(0x4020, mload(0x420))
mstore(0x4040, mload(0x3480))
success := and(eq(staticcall(gas(), 0x7, 0x4000, 0x60, 0x4000, 0x40), 1), success)
mstore(0x4060, mload(0x3f80))
                    mstore(0x4080, mload(0x3fa0))
mstore(0x40a0, mload(0x4000))
                    mstore(0x40c0, mload(0x4020))
success := and(eq(staticcall(gas(), 0x6, 0x4060, 0x80, 0x4060, 0x40), 1), success)
mstore(0x40e0, mload(0x440))
                    mstore(0x4100, mload(0x460))
mstore(0x4120, mload(0x34a0))
success := and(eq(staticcall(gas(), 0x7, 0x40e0, 0x60, 0x40e0, 0x40), 1), success)
mstore(0x4140, mload(0x4060))
                    mstore(0x4160, mload(0x4080))
mstore(0x4180, mload(0x40e0))
                    mstore(0x41a0, mload(0x4100))
success := and(eq(staticcall(gas(), 0x6, 0x4140, 0x80, 0x4140, 0x40), 1), success)
mstore(0x41c0, mload(0x480))
                    mstore(0x41e0, mload(0x4a0))
mstore(0x4200, mload(0x34c0))
success := and(eq(staticcall(gas(), 0x7, 0x41c0, 0x60, 0x41c0, 0x40), 1), success)
mstore(0x4220, mload(0x4140))
                    mstore(0x4240, mload(0x4160))
mstore(0x4260, mload(0x41c0))
                    mstore(0x4280, mload(0x41e0))
success := and(eq(staticcall(gas(), 0x6, 0x4220, 0x80, 0x4220, 0x40), 1), success)
mstore(0x42a0, mload(0x4c0))
                    mstore(0x42c0, mload(0x4e0))
mstore(0x42e0, mload(0x34e0))
success := and(eq(staticcall(gas(), 0x7, 0x42a0, 0x60, 0x42a0, 0x40), 1), success)
mstore(0x4300, mload(0x4220))
                    mstore(0x4320, mload(0x4240))
mstore(0x4340, mload(0x42a0))
                    mstore(0x4360, mload(0x42c0))
success := and(eq(staticcall(gas(), 0x6, 0x4300, 0x80, 0x4300, 0x40), 1), success)
mstore(0x4380, mload(0x360))
                    mstore(0x43a0, mload(0x380))
mstore(0x43c0, mload(0x3500))
success := and(eq(staticcall(gas(), 0x7, 0x4380, 0x60, 0x4380, 0x40), 1), success)
mstore(0x43e0, mload(0x4300))
                    mstore(0x4400, mload(0x4320))
mstore(0x4420, mload(0x4380))
                    mstore(0x4440, mload(0x43a0))
success := and(eq(staticcall(gas(), 0x6, 0x43e0, 0x80, 0x43e0, 0x40), 1), success)
mstore(0x4460, mload(0x880))
                    mstore(0x4480, mload(0x8a0))
mstore(0x44a0, sub(f_q, mload(0x3540)))
success := and(eq(staticcall(gas(), 0x7, 0x4460, 0x60, 0x4460, 0x40), 1), success)
mstore(0x44c0, mload(0x43e0))
                    mstore(0x44e0, mload(0x4400))
mstore(0x4500, mload(0x4460))
                    mstore(0x4520, mload(0x4480))
success := and(eq(staticcall(gas(), 0x6, 0x44c0, 0x80, 0x44c0, 0x40), 1), success)
mstore(0x4540, mload(0x920))
                    mstore(0x4560, mload(0x940))
mstore(0x4580, mload(0x3560))
success := and(eq(staticcall(gas(), 0x7, 0x4540, 0x60, 0x4540, 0x40), 1), success)
mstore(0x45a0, mload(0x44c0))
                    mstore(0x45c0, mload(0x44e0))
mstore(0x45e0, mload(0x4540))
                    mstore(0x4600, mload(0x4560))
success := and(eq(staticcall(gas(), 0x6, 0x45a0, 0x80, 0x45a0, 0x40), 1), success)
mstore(0x4620, mload(0x45a0))
                    mstore(0x4640, mload(0x45c0))
mstore(0x4660, 0x198e9393920d483a7260bfb731fb5d25f1aa493335a9e71297e485b7aef312c2)
            mstore(0x4680, 0x1800deef121f1e76426a00665e5c4479674322d4f75edadd46debd5cd992f6ed)
            mstore(0x46a0, 0x090689d0585ff075ec9e99ad690c3395bc4b313370b38ef355acdadcd122975b)
            mstore(0x46c0, 0x12c85ea5db8c6deb4aab71808dcb408fe3d1e7690c43d37b4ce6cc0166fa7daa)
mstore(0x46e0, mload(0x920))
                    mstore(0x4700, mload(0x940))
mstore(0x4720, 0x17cc93077f56f654da727c1def86010339c2b4131094547285adb083e48c197b)
            mstore(0x4740, 0x285b1f14edd7e6632340a37dfae9005ff762edcfecfe1c732a7474c0708bef80)
            mstore(0x4760, 0x0ec56ea3f31a7c4b5100ea8711a5ee83b453955652ed813695efb84f0ad28e6e)
            mstore(0x4780, 0x04b6b43b964556568e63decd8c5061d88e50364110657e7575452e3b3c9e7d77)
success := and(eq(staticcall(gas(), 0x8, 0x4620, 0x180, 0x4620, 0x20), 1), success)
success := and(eq(mload(0x4620), 1), success)

            // Revert if anything fails
            if iszero(success) { revert(0, 0) }

            // Return empty bytes on success
            return(0, 0)

        }
    }
}
        