// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {ZKMToken} from "./ZKMToken.sol";
import {Halo2Verifier} from "./Halo2Verifier.sol";
import {Halo2VerifyingKey} from "./Halo2VerifyingKey.sol";

/// @title ZKMAirdrop — Privacy-preserving ZKM token claim contract (Halo2-KZG)
/// @notice Fully immutable. No admin, no owner, no pause, no upgrade.
/// @dev Uses production Halo2-KZG proof verification with full ecPairing.
///      Public inputs are passed as uint256[] — matches halo2-solidity-verifier.
contract ZKMAirdrop {
    ZKMToken public immutable token;
    /// @notice Halo2 verifier contract (generated by halo2-solidity-verifier).
    Halo2Verifier public immutable verifier;
    /// @notice Halo2 verifying key contract (contains circuit VK constants).
    Halo2VerifyingKey public immutable verifyingKey;
    bytes32 public immutable merkleRoot;

    uint256 public constant CLAIM_AMOUNT = 10_000e18; // 10,000 ZKM
    uint256 public constant MAX_CLAIMS = 1_000_000;
    uint256 public constant CLAIM_DEADLINE = 1_798_761_600; // 2027-01-01 00:00:00 UTC

    /// @notice Exact Halo2-KZG proof byte length.
    /// @dev This is the authoritative length enforced inside `Halo2Verifier.sol`
    ///      (`eq(0x1600, calldataload(PROOF_LEN_CPTR))`, where 0x1600 = 5632) and
    ///      is fixed by the circuit's commitment structure. A pre-check here gives
    ///      a clearer revert than the verifier's boolean return. If the circuit is
    ///      ever regenerated such that the length changes, the verifier's hardcoded
    ///      `0x1600` changes too (and the VK digest changes, invalidating all prior
    ///      proofs), so this constant MUST be updated in lockstep with
    ///      `Halo2Verifier.sol`. There is intentionally no "tolerance range": a
    ///      proof whose length differs is for a different circuit and must be
    ///      rejected.
    uint256 public constant PROOF_LENGTH = 5632;

    uint256 public totalClaims;
    mapping(bytes32 => bool) public usedNullifiers;

    event Claimed(bytes32 indexed nullifier, uint256 amount, address indexed recipient, uint256 totalClaims);

    constructor(address _token, address _verifier, address _verifyingKey, bytes32 _merkleRoot) {
        token = ZKMToken(_token);
        verifier = Halo2Verifier(_verifier);
        verifyingKey = Halo2VerifyingKey(_verifyingKey);
        merkleRoot = _merkleRoot;
    }

    /// @notice Claim ZKM tokens with a valid Halo2 proof.
    /// @param proof The Halo2 KZG proof bytes.
    /// @param nullifier The claim's nullifier (poseidon(key, domain)).
    /// @param recipient Address to receive 10,000 ZKM.
    ///
    /// @dev Checks-Effects-Interactions (CEI) pattern:
    ///      1. Checks: deadline, cap, nullifier, recipient, proof length, proof validity
    ///      2. Effects: mark nullifier, increment totalClaims
    ///      3. Interactions: token.mint() — external call to immutable ZKMToken
    ///
    ///      ZKMToken.mint() is a simple ERC-20 with no callbacks or hooks.
    ///      The minter is immutable (set at construction), so even if token.mint()
    ///      were to re-enter, it cannot re-enter claim() because:
    ///      - usedNullifiers[nullifier] is already true (set before mint)
    ///      - totalClaims is already incremented (set before mint)
    ///
    /// @dev Gas: Real Halo2-KZG proof verification with ecPairing costs ~350-500K gas.
    ///      The total claim transaction is estimated at ~400-550K gas.
    ///      The FALLBACK_GAS_LIMIT in the CLI is 700K to account for variance.
    function claim(bytes calldata proof, bytes32 nullifier, address recipient) external {
        // Check basic invariants FIRST (cheap checks before expensive verification)
        require(block.timestamp < CLAIM_DEADLINE, "Claim period ended");
        require(totalClaims < MAX_CLAIMS, "Claim cap reached");
        require(!usedNullifiers[nullifier], "Already claimed");
        require(recipient != address(0), "Recipient cannot be zero");

        // Validate proof length exactly matches the Halo2Verifier's expected
        // size (see PROOF_LENGTH doc). The verifier re-checks this authoritatively.
        require(proof.length == PROOF_LENGTH, "Invalid proof length");

        // Construct public inputs: [merkleRoot, nullifier, recipient]
        uint256[] memory publicInputs = new uint256[](3);
        publicInputs[0] = uint256(merkleRoot);
        publicInputs[1] = uint256(nullifier);
        publicInputs[2] = uint256(uint160(recipient));

        // Verify Halo2 proof via the production verifier contract.
        // Uses full KZG pairing verification via BN254 ecPairing precompile.
        require(verifier.verifyProof(address(verifyingKey), proof, publicInputs), "Invalid proof");

        // Mark claimed and mint
        usedNullifiers[nullifier] = true;
        totalClaims++;
        token.mint(recipient, CLAIM_AMOUNT);

        emit Claimed(nullifier, CLAIM_AMOUNT, recipient, totalClaims);
    }

    function isClaimed(bytes32 nullifier) external view returns (bool) {
        return usedNullifiers[nullifier];
    }

    function claimsRemaining() external view returns (uint256) {
        return totalClaims >= MAX_CLAIMS ? 0 : MAX_CLAIMS - totalClaims;
    }

    function isClaimWindowOpen() external view returns (bool) {
        return block.timestamp < CLAIM_DEADLINE && totalClaims < MAX_CLAIMS;
    }
}
